### ISSUE TITLE
extra attributes

### ISSUE THREAD

**Issue by Enalmada** [garmeeh/next-seo#1]
I came across this component that seems to attempt similar concept:
https://github.com/cereallarceny/cra-ssr/blob/master/src/app/components/page/index.js

Just posting it here for your consideration about some things that next-seo may not support but could be common needs.

**Comment by garmeeh** [comment]
Hi @Enalmada thanks for the link 😄 Currently working on documenting V1.0 release at the moment but will definitely take look through afterwards and see could I add some features I am missing. 

If there are features you would like please let me know and I can see what I can do.
