### ISSUE TITLE
JSON-LD not working in v5.5.0

### ISSUE THREAD

**Issue by tom-boyd-frasers** [garmeeh/next-seo#1003]
**Describe the bug**
 JSON-LD type doesn't return any script in v5.5.0, but works fine in v5.4.0.

**Reproduction**
Using any of the  JSON-LD types in [README.md](https://github.com/garmeeh/next-seo#readme). Specifically product.

**Expected behavior**
Return a div with a script

**Comment by gpadbidri** [comment]
Yes..Observed the same

**Comment by SeanDemps** [comment]
Verified next-seo v5.5.0 on next v12.3.1: no issues found, script appears as expected.

Can you please create a new issue with more specific recreation steps if the issue persists?

**Comment by tom-boyd-frasers** [comment]
I was on next v12.2.4

**Comment by garmeeh** [comment]
Thanks @SeanDemps 🙏
