### ISSUE TITLE
Order and Invoice Structured Data are not implemented

### ISSUE THREAD

**Issue by gpadbidri** [garmeeh/next-seo#1008]
As per the scehma org we have Structured Data for Invoce and Order (https://schema.org/Order)
Why have we not yet implemented them ? Any specific reason for not doing the same ? Or it is discontinued ?

**Comment by garmeeh** [comment]
Hey @gpadbidri the goal of this library is for SEO. Not sure how an Order would fit into SEO as it is not something you would likely index on Google. 

I loosely follow what Google recommends on their feature guide [here](https://developers.google.com/search/docs/appearance/structured-data/article)
