### ISSUE TITLE
Use `siteName` instead of `site_name`

### ISSUE THREAD

**Issue by phuctm97** [garmeeh/next-seo#1011]
**Describe the bug**

All props are currently camelCase exception for openGraph.site_name. Would be nice to have `siteName` as an alternative.

**Expected behavior**
Have optional `openGraph.siteName`, use `openGraph.site_name` if provided to avoid breaking changes, otherwise, use `openGraph.siteName`.

**Comment by GlennGuegan** [comment]
Hello, In hacktoberfest context it's ok to contribute on this issue ?

**Comment by garmeeh** [comment]
Now in v5.8.0
