### ISSUE TITLE
BreadcrumbJsonLd does not accept additional props

### ISSUE THREAD

**Issue by aumi364** [garmeeh/next-seo#1039]
**Describe the bug**
BreadcrumbJson does not accept addiotional custom prop from schema, as other schema can accept additional extra props.

**Reproduction**
To produce you need to add custom prop in BreadcrumbJson Ld

**Expected behavior**
Accepted behavior is we should see the additional prop in the schema

**Additional context**
![image](https://user-images.githubusercontent.com/16230189/196892293-b18a210c-bc05-493f-9b2f-3046528f31d1.png)
I  have figured out that '...rest' is missing in this portion hope this helps.

**Comment by divinenaman** [comment]
Hey @garmeeh can you assign me this issue ?

**Comment by divinenaman** [comment]
@garmeeh sorry for the late request but can you add hacktober label

**Comment by garmeeh** [comment]
Hey @divinenaman the label is on the pull request 😉

I think it takes a few days once merged to be "accepted" on the Hacktober site
