### ISSUE TITLE
Not possible to add HTML to the description props for JobPositions

### ISSUE THREAD

**Issue by 28development** [garmeeh/next-seo#1053]
Currently, it is only possible to add a string to the description prop using the

`<JobPostingJsonLd`

schema. It should be possible to add HTML markup to that description as described here.

https://developers.google.com/search/docs/appearance/structured-data/job-posting

Currently, something like this does not work
```
      <JobPostingJsonLd
        description={<JobPositionDescriptionJsonld jobPosition={jobPosition} />}
```

**Comment by garmeeh** [comment]
You will need to add it as a string:

```
<JobPostingJsonLd
        description="<p>Job description</p><ul><li>requirement 1</li><li>requirement 2</li></ul>"
```

It will then render it for your escaped. 

JSON-LD spec requires all entities to be escaped, I'm looking to double confirm with Google that they decode the html too.
