### ISSUE TITLE
ArticleJsonLd The author may be an organization

### ISSUE THREAD

**Issue by MixMe** [garmeeh/next-seo#1093]
https://developers.google.com/search/docs/appearance/structured-data/article

Author: 
[Person](https://schema.org/Person) or [Organization](https://schema.org/Organization)

The author of the article. To help Google best understand authors across various features, we recommend following the [author markup best practices](https://developers.google.com/search/docs/appearance/structured-data/article#author-bp).

**Comment by ilyichv** [comment]
With this PR it should be feasible #1105

**Comment by joggienl** [comment]
I was looking for this!

It would be nice to be able to add an organization as author instead of a person (as defined by the schema).

@ilyichv does that PR also do it for ArticleJsonLd (because it states `NewsArticleJsonLd`)?

**Comment by joggienl** [comment]
I see, nicely done!

Not sure if needed, I checkt the `setAuthor` method, there are in fact more files affected by that pr. I see usage in `qaPage`, `recipe`, `videoGame` and `carousel`. I assume that those need to be checked (and tested) as wel.

**Comment by ilyichv** [comment]
As you can see I'm defaulting the type to person if not provided 
'@type': author?.type ?? 'Person'

This won't be a breaking change!

**Comment by garmeeh** [comment]
PR was merged and release as part of v5.15.0

Feel free to open new issue if it doesn't cover all use cases.
