### ISSUE TITLE
No items detected with Rich Results Test - Google Search Console

### ISSUE THREAD

**Issue by 1377sayaba** [garmeeh/next-seo#1097]
I used the  FAQPageJsonLd and this working when i test with [shema.org](https://validator.schema.org/#url=https%3A%2F%2Fbamachoub.com%2Ffaq%2Fcat%2F12698374) 
BUT
when i test with [Rich Results Test - Google Search Console](https://search.google.com/test/rich-results) ، the results of test is No items detected 
[https://search.google.com/test/rich-results/result?id=TqwFlGVMJQ4n1AAU_P4tbA](https://search.google.com/test/rich-results/result?id=TqwFlGVMJQ4n1AAU_P4tbA)

[my page 
](https://bamachoub.com/faq/cat/12698374)
why is this happening ?

**Comment by garmeeh** [comment]
Hey @1377sayaba when checking your site I noticed if you disable javascript, your page does not render. 

Google will not use javascript, this is why the tags are not showing in the google tester. 

I usually see this issue when NextSeo is conditionally rendered client side after a useEffect or data fetch.

**Comment by 1377sayaba** [comment]
Thank you
that is right
i used [getServerSideProps of nextjs](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props) for SSR and SEO .
do you suggest any solution for this issue?
