### ISSUE TITLE
Full Twitter options

### ISSUE THREAD

**Issue by jamesemwallis** [garmeeh/next-seo#11]
Does next-seo have the ability to set the twitter description and image inside the Twitter object? I can't see anything documented in the readme.

Thanks

**Comment by garmeeh** [comment]
Hey @jamesemwallis, Twitter will read from the Open Grpah tags. So if you set the description and images for open graph, Twitter will use them.

**Comment by jamesemwallis** [comment]
@garmeeh Thank you.
