### ISSUE TITLE
Multiple alternate languages

### ISSUE THREAD

**Issue by petertulala** [garmeeh/next-seo#114]
`languageAlternate` currently takes only 1 object (i.e. only 1 alternative language). But typically, each page has multiple language alternatives:

```
<link rel="alternate" hrefLang="en" href="http://example.com/page" />
<link rel="alternate" hrefLang="de" href="http://example.com/de/page" />
<link rel="alternate" hrefLang="es" href="http://example.com/es/page" />
<link rel="alternate" hrefLang="x-default" href="http://example.com/page" />
```

Is there a chance to support this?

Possible solution might be to provide an array to `languageAlternate`:

```
languageAlternate={[
  {
    hrefLang: 'en',
    href: 'http://example.com/page',
  },
  {
    hrefLang: 'de',
    href: 'http://example.com/de/page',
  },
  ...
]}
```

**Comment by petertulala** [comment]
I've created a pull request for this change.

**Comment by fanofdbz** [comment]
I am facing the same issue, is there any alternative for this in the current version, or we are referring to @petertulala's code?

**Comment by garmeeh** [comment]
Hey @fanofdbz, once PR #115 is merged, it will have support for multiple languages.
