### ISSUE TITLE
nextjs13 deprecating head.js

### ISSUE THREAD

**Issue by sharpsteelsoftware1** [garmeeh/next-seo#1172]
According to https://beta.nextjs.org/docs/api-reference/metadata head.js will be deprecated. Any thoughts on what it means for the future of this library?

**Comment by Arjan-Zuidema** [comment]
https://beta.nextjs.org/docs/api-reference/metadata

Looks like Next's 13.2 makes this package obsolete

**Comment by garmeeh** [comment]
Hey @sharpsteelsoftware1 / @Arjan-Zuidema 👋 

I had the pleasure of meeting with the Next.js team on the new meta data api and was able to give early feedback on it. 

A small % of `next-seo` will be replaced by the meta data api eventually. The rest of `next-seo` will be useful JSON-LD. 

At the moment the new meta data api is only available in the `app` directory which is not yet stable or production ready. So this library will be still used in `pages`. 

I don't see the core of this library being removed anytime soon as many enterprise sites rely on `next-seo` and I can't see them migrating to `app` directory` fully anytime soon.

**Comment by garmeeh** [comment]
Hey @justiny there was some specific docs for the `app` directory. I have updated the main docs now to reflect how it works with the `app` directory.
