### ISSUE TITLE
ItemList needed - a similar scheme to BreadcrumbList.

### ISSUE THREAD

**Issue by pixelkoduje** [garmeeh/next-seo#1184]
Are you able to add an ItemList(ItemListOrderAscending)? It is used in stores to return products in the form of a list on a given subpage.
(The scheme is similar or even almost identical to BreadcrumbList)

https://schema.org/ItemListOrderAscending
![image](https://user-images.githubusercontent.com/102321542/224492461-b5536658-9be4-46d1-95ed-8e12366623b7.png)

**Comment by pixelkoduje** [comment]
Is this project still in development? Because I haven't seen any movement for 3-4 months. And if it is to be fully useful in ecommerce, it would be nice to introduce what I wrote.

**Comment by garmeeh** [comment]
Hey @pixelkoduje yes the project is still in development. I usually do a batch of work once a quarter on the project unless there any critical issues. I should be doing the next round of development at the end of the month. 

I think this might suit your purpose? https://github.com/garmeeh/next-seo#carousel

**Comment by garmeeh** [comment]
If not feel free to open pull request that extends the breadcrumb component to switch the type.

**Comment by pixelkoduje** [comment]
Dude, I don't know how to comment on this. Google doesn't work like a food joint. I'll have a burger or spaghetti. It must be exactly the scheme that google assumes. And this scheme is not unnecessary. This is the main part of ecommerce. By the way, I work and help in projects, but now I'm working on my own project. It would be bad if I was working on two - or someone else's, so that something in the project would work for me. That's what libraries are for, to help us, not the other way around.

Item List is needed - Item ListOder (which tells google what products are on a given subpage)

**Comment by garmeeh** [comment]
This is a feee and open source library. As I said feel free to open a pull request.
