### ISSUE TITLE
Work as a plugin

### ISSUE THREAD

**Issue by NathanielHill** [garmeeh/next-seo#12]
As it stands, it's a standalone component that you have to inject and manage the config object for. Would be nice if it worked as a plugin that injected itself and config could simply be dropped into `next.config.js`.

This would also allow people using `next-compose-plugins` for example to more easily change the configuration dynamically.

**Comment by garmeeh** [comment]
Hey @NathanielHill, I spent a little time looking into using `next.config.js` and wondering would it be a good fit for `next-seo` 🤔 

As it stands you can use `next-seo` without injecting any config object. I use the `next-seo.config.js` file as a handy place to keep the initial default SEO. 

If you have an example of how you see it working with `next.config.js` I can take another look.

**Comment by garmeeh** [comment]
Going to close this issue, based on some feedback from Tim on this, it would be best not to set the config in `next.config.js`.
