### ISSUE TITLE
NextSeo Page level is not overriding the Default SEO

### ISSUE THREAD

**Issue by innonguyen** [garmeeh/next-seo#1257]
**Describe the bug**

Background
1. I had a Default SEO configured
2. I had a customize NextSEO in the page /about (I called it PageSEO)

Situation
1. PageSEO worked on localhost
2. PageSEO worked when I deployed to production and use "Localhost Open Graph Debugger" for Chrome to wrap the original url (https://mysite.com/about) with a new url (https://og.nullnull.dev/site/<some_path>) and checked it on Sharing Debugger of Facebook (https://developers.facebook.com/tools/debug)
2. PageSEO **not working** when I use direct url (https://mysite.com/about) to check on Sharing Debugger. It showed DefaultSEO.

**Expected behavior**
I expected Sharing Debugger to display PageSEO instead of DefaultSEO.

**Additional context**
I'm thinking it's a flaw in next-seo pagage or the Facebook Sharing Debugger Cache.
Do you have any idea?

**Comment by garmeeh** [comment]
Could you provide a small re-creation of this?

**Comment by innonguyen** [comment]
Hi, I figured out the problem. It blocked by redux-persist. Just remove it.
