### ISSUE TITLE
Facebook Application ID has been deprecated and should be deleted

### ISSUE THREAD

**Issue by Bowens20832** [garmeeh/next-seo#1260]
I opened a discussion here, but I have not received any feedback yet :( #1256 

Hey everyone 👋

The Facebook App ID seems to be very dated, and not a functional utility to users at this moment in time.

Facebook has rebranded to Meta.
Facebook Pixel is now refered to Meta Pixel.
Facebook insights have been removed.
Facebook does not provide an "APP_ID" anymore, and this confuses users.
Facebook now provides a "Facebook_Pixel_ID".
Facebook now provides a Meta Pixel, but providing it the "Facebook_App_ID" variable in the Next-SEO component has no effect on the new Meta businees manager.
Should we propose to possibly completly upgrade this feature to support the new Meta Pixel?

Vercel provides a simple example of migrating to the new Pixel ID: https://github.com/vercel/next.js/tree/canary/examples/with-facebook-pixel

See this issue here: https://github.com/elegantframework/elegant-cli/issues/51

If we updated Next-Seo to this new Pixel, I would be able to close the issue mentioned above without writing any core code on our project 😄

**Comment by garmeeh** [comment]
Hey @Bowens20832, a pull request to add the new features would be amazing.

I think we should keep the old one for now and we can remove later. This is just to avoid a breaking change as some people may still be expecting it to be there so could be testing for it.
