### ISSUE TITLE
`useAppDir` is not being accepted as props

### ISSUE THREAD

**Issue by arunavo4** [garmeeh/next-seo#1271]
**Describe the bug**
I have added the `useAppDir` prop to the head.js and layout.js files as instructed. Also, this (article)[https://blog.logrocket.com/manage-seo-next-js-with-next-seo/] has a good guide but it results in this error.

```

./app/head.tsx:6:28
Type error: Type '{ useAppDir: boolean; titleTemplate: string; defaultTitle: string; openGraph: { type: string; url: string; title: string; description: string; images: { url: string; width: number; height: number; alt: string; }[]; }; twitter: { ...; }; }' is not assignable to type 'IntrinsicAttributes & NextSeoProps'.
  Property 'useAppDir' does not exist on type 'IntrinsicAttributes & NextSeoProps'.

  4 | 
  5 | export default async function Head() {
> 6 |   return <NextSeo {...SEO} useAppDir={true} />;
    |                            ^
  7 | }
  8 | 
```

**Reproduction**
[Codespace Link](https://codespaces.new/arunavo4/OtherViewAgency/tree/dev?quickstart=1)

**Expected behavior**

**Additional context**

**Comment by garmeeh** [comment]
Hey @arunavo4 thanks for the very clear issue 👌 

This is actually expected. While app directory was still in beta we had this. The next team added most of the core next-seo meta tags to head. You can check out the docs [here](https://nextjs.org/docs/app/building-your-application/optimizing/metadata#usage)

You can still use next-seo for all your JSON-LD needs.
