### ISSUE TITLE
dynamic page ProductJsonLd, No items detected from google

### ISSUE THREAD

**Issue by h9ee** [garmeeh/next-seo#1278]
when I use ProductJsonLd, [google validator](https://search.google.com/test/rich-results) not detected.

this one of my links:  [product](https://www.iperfum.com/product/%D8%A7%D8%AF%DA%A9%D9%84%D9%86-%DA%A9%D8%B1%DB%8C%D8%B4%D9%86-%D9%84%D8%A7%D9%85%DB%8C%D8%B3-%D8%A7%D9%88%D8%B1%DB%8C-%D9%88%D8%A7%D9%86-%D8%B2%D9%86%D8%A7%D9%86%D9%87--%D8%A7%D9%88%D8%B1%D8%AC%DB%8C%D9%86%D8%A7%D9%84)

I have JSON-LD on pages. But when I test in google validator, it doesn't recognize anything

Next: 13.4.6 App Router => useAppDir={true}
React: 18.2.0
next-seo: "^6.0.0"

**Comment by garmeeh** [comment]
Hey @h9ee I think it might be due to `.gif` for the image urls used in JSON-LD and `og:url` 

If you update these and try.

**Comment by h9ee** [comment]
> 
Thanks for the answer but no, this product has .gif but other products don't have it, but JSON-LD not detected.
For example: [Product](https://www.iperfum.com/product/%D8%A7%D8%AF%DA%A9%D9%84%D9%86-%D8%A7%D9%88%D8%B1%D8%AC%DB%8C%D9%86%D8%A7%D9%84-%DA%A9%D8%A7%D9%BE%D8%AA%D8%A7%D9%86-%D8%A8%D9%84%DA%A9-%D8%A7%D9%85%D8%A7%D8%B1%D8%A7%D8%AA)

**Comment by RainGrid** [comment]
@h9ee Google says something wrong with the images urls 
![изображение](https://github.com/garmeeh/next-seo/assets/5560310/360358cf-b574-45ea-a49e-d8e1f362e70e)
