### ISSUE TITLE
Working on frontend only

### ISSUE THREAD

**Issue by ivtod** [garmeeh/next-seo#128]
I'm trying to implement the basic example inside an app that already use `_app.js` and `_document.js`

This is my `test.js` page:

```
import React from 'react';
import { NextSeo } from 'next-seo';

export default () => (
  <>
    <NextSeo
      title="Simple Usage Example"
      description="A short description goes here."
    />
    <p>Simple Usage</p>
  </>
);
```

I can see it working only client-side, if I view page source the title and description are not set.
If I remove `_app.js` and `_document.js` I can see the title and description correctly in the page source.

What am I missing?

Thanks!

**Comment by raindecastro** [comment]
Same here, for some reason my tags are only rendering on client side.

**Comment by jethromay** [comment]
Experiencing this currently.

**Comment by brookslyrette** [comment]
Started seeing this issue as well.

**Comment by petermarks12** [comment]
Yes, experiencing same thing and I think its due to next-redux wrapper.  Any solution to make it work with redux ?

**Comment by ivtod** [comment]
In my case, I have a component that wraps **pages**;
I was conditionally rendering the **page** content:

``` 		
<div>
{
    !loading && props.children
}
</div>
```

Of course the code inside the page responsible to propagate NextSEO attributes at server side rendering time can't work because the component is not "mounted" yet.
Simply hiding the page content made it work correctly:

```
<div className={classnames({'d-none': loading})}>
{
    props.children
}
</div>
```

Hope it helps

**Comment by garmeeh** [comment]
I have created a CodeSandbox [here](https://codesandbox.io/s/tiess) to try re-create but not seeing the issue. Could someone try fork it maybe and provide a recreation?

**Comment by talentlessguy** [comment]
Can confirm, when `next export` or `next build` it doesn't generate any meta tags in both cases

**Comment by shaunsaker** [comment]
I ran into the same issue but I seem to have solved it by adding `DefaultSeo` to _document.js:

```jsx
 return (
      <Html lang="en">
        <Head>
          <DefaultSeo {...seo} />

          {/* other stuff */}
        </Head>

        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
```

and then customised in my layouts:

```jsx
return (
   <Page>
      <NextSeo
        title={customTitle}
      />

    {/* other stuff */}
  </Page>
```

Now my export seems to have the default head html.

**Comment by garmeeh** [comment]
@shaunsaker I would not recommend adding `<DefaultSeo/>` within `next/head` it can cause unexpected behaviour. You should be able to use them side by side.

**Comment by garmeeh** [comment]
@talentlessguy 
> Can confirm, when next export or next build it doesn't generate any meta tags in both cases

Please see the CodeSandbox [here](https://codesandbox.io/s/tiess). This works as expected with `next build` and `next export`.

**Comment by shaunsaker** [comment]
@garmeeh Thanks, I was seeing inconsistent results. I added `DefaultSeo` to _app.js adjacent to NextHead instead and it's exporting the static html correctly.

**Comment by vvmspace** [comment]
> @talentlessguy
> 
> > Can confirm, when next export or next build it doesn't generate any meta tags in both cases
> 
> Please see the CodeSandbox [here](https://codesandbox.io/s/tiess). This works as expected with `next build` and `next export`.


Same problem with list of EventJsonLd.

If I understanding **next export** means building  static html pages.
But what about **npm run dev**?

**Comment by talentlessguy** [comment]
@vvmspace `npm run dev` launches an universal Next.js app in "dynamic" mode, where you can use server side features in gip. `next export` exports pages in "static" mode.

not related to next-seo though, it is written in the docs of Next.js

**Comment by PeterMerkert** [comment]
> **date:** My issue was casued by an redux container component that was wrapping `Component` in `_app.js`.

I can confirm that this was a problem for us as well. We switched using plain React hooks and context and it works immediately. I assume the redux provider wrapping results in a first render without content, which results in not taken the page specific SEO tags into account.

**Comment by carlosHerz** [comment]
I am still having this issue when i run next build && next export my meta datas are not pre-rendered and instead are added on client side :/

**Comment by heyitsarpit** [comment]
Having this same issue, I'm not using redux or any other context wrappers.

**Comment by asotog** [comment]
having same issue

**Comment by jonalvarezz** [comment]
I hit this issue on Next v12.

I noticed it worked fine for another project that was on Next v11. Downgrading fixed it.

**Comment by jerome-chen** [comment]
Having the same issues and still not solved.

**Comment by EvilaMany** [comment]
Still not resolved
