### ISSUE TITLE
languageAttribute and facebookId not set 

### ISSUE THREAD

**Issue by mercteil** [garmeeh/next-seo#129]
Hi,

I try to implement the alternate language tag but I end up having the head node without the alternate attribute, also the facebookAppId is not set. 

However the title and description tags are set, so the default config is basically working.

Is there anything I do not understand or there an issue with the lib ?

Default config.js
```javascript
export default {
  title,
  description,
  facebook: {
    appId: process.env.FACEBOOK_APP_ID || '',
  },
  languageAlternate: {
    hrefLang: 'de',
    href: 'https://example.com/de/',
  },
};

```

_app.js
```
<>
        <DefaultSeo {...SEO} />
        <Provider store={store}>
          <Component {...pageProps} />
          <ToastContainer />
        </Provider>
      </>
```

**Comment by mercteil** [comment]
Definitely not working properly. I have

**Comment by mercteil** [comment]
In doc it says `languageAlternate` (use object or array).

This works
```
  languageAlternates: [
    {
      hrefLang: 'de',
      href: 'https://example.com/de/',
    },
  ],
```

This doesn't work
```
  languageAlternates: {
      hrefLang: 'de',
      href: 'https://example.com/de/',
    },
```

This doesn't work
```
  languageAlternate: {
      hrefLang: 'de',
      href: 'https://example.com/de/',
    },
```

**Comment by DucSilva** [comment]
how to fix it?
