### ISSUE TITLE
Next seo in the App router

### ISSUE THREAD

**Issue by Suriyasanjay** [garmeeh/next-seo#1293]
```
import React from 'react'
import { NextSeo } from 'next-seo'

const page = () => {
    return (
        <>
            <NextSeo
                title="Job List"
                description="Build digital experiences for any tech stack, visually."
            />
        </>
    )
}
export default page
```

**In Terminal**
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
 ⨯ TypeError: Cannot read properties of null (reading 'useContext')
    at stringify (<anonymous>)
 ⨯ TypeError: Cannot read properties of null (reading 'useContext')
    at stringify (<anonymous>)
digest: "404728629"

**In Browser**

Unhandled Runtime Error
Error: Cannot read properties of null (reading 'useContext')

**Comment by garmeeh** [comment]
For standard SEO meta data you should use Next.js [Metadata API](https://nextjs.org/docs/app/building-your-application/optimizing/metadata#usage)

For the app directory `next-seo`  is still useful for [JSON-LD](https://github.com/garmeeh/next-seo#json-ld)

**Comment by abe312** [comment]
@garmeeh also getting the same error when using JSON-LD

**Comment by eddundead** [comment]
> For standard SEO meta data you should use Next.js [Metadata API](https://nextjs.org/docs/app/building-your-application/optimizing/metadata#usage)
> 
> For the app directory `next-seo` is still useful for [JSON-LD](https://github.com/garmeeh/next-seo#json-ld)

what is the sense of keeping next-seo name for this package if it not solving the original problem? And not pushing SEO for the page?
