### ISSUE TITLE
Import both _defaultSEO2 and _blog2

### ISSUE THREAD

**Issue by brianjolly** [garmeeh/next-seo#13]
Hi There,

We are using the [standard js style](https://standardjs.com/) and I can't seem to make it happy when importing both the default `_defaultSEO2` and `_blog2` in the same page without linter errors.

For example:
`import { default as NextSeo, BlogJsonLd } from 'next-seo'`
gives this lint error:
`Use default import syntax to import 'NextSeo'.`

Also trying: 
```
import { default as NextSeo } from 'next-seo'
import { BlogJsonLd } from 'next-seo'
```
or 
```
import NextSeo from 'next-seo'
import { BlogJsonLd } from 'next-seo'
```
both give
`'next-seo' imported multiple times.`

Do you know if there is a better way I could import these and still keep the linter free of errors?

Thank You!

**Comment by garmeeh** [comment]
Hey @brianjolly, could you try:

```
import NextSeo, { BlogJsonLd } from 'next-seo';
```

**Comment by brianjolly** [comment]
Hi @garmeeh , that works perfect. Thank You!!!
