### ISSUE TITLE
Is it possible to add custom LD objects ?

### ISSUE THREAD

**Issue by mercteil** [garmeeh/next-seo#131]
I see some fields are not supported by the lib.

Is it possible to add custom LD data objects, that will not be validated by the lib?

**Comment by garmeeh** [comment]
I can take a look at this. Could you give me an example to work with?

**Comment by mercteil** [comment]
For instance I want to add a graph with multiple products:

```
{
  "@context": "http://schema.org",
  "@graph": [
{
  "@type": "Product",
  "name": "tshirt",
  "description": "test copy 1.",
  "image": "image.jpg"
},
{
  "@type": "Product",
  "name": "tshirt 2",
  "description": "test copy 2.",
  "image": "image2.jpg"
}
]
}
```

**Comment by mercteil** [comment]
Also I would like to add multiple offers in EUR and in USD for example ...

**Comment by danielcolgan** [comment]
I'm trying to add sitelinks search box, see: https://developers.google.com/search/docs/data-types/sitelinks-searchbox#example, up ❤️

**Comment by paambaati** [comment]
@garmeeh +1 for this feature. Because this library doesn't support every Schema option, and because Schema could also change, it would be nice to have an escape hatch of sorts.

Something like —

```jsx
<LogoJsonLd
    logo="http://www.your-site.com/images/logo.jpg"
    url="http://www.your-site.com"
    custom={{
        alt: 'Your site logo'
    }}
/>
```

Assuming `alt` is a Schema object that isn't currently supported by `LogoJsonLd`. Everything in `custom` will be passed on to the JSON+LD object as-is.

**Comment by thiras** [comment]
+1 for the feature

**Comment by svassaux** [comment]
very good proposition, +1 too

**Comment by anttiku** [comment]
+1 for this feature. There will always be different versions of schemas, so custom ones should be possible. I.e. `WebPageJsonLd` could have `name` & `primaryImageOfPage`

**Comment by yfhui** [comment]
strongly requesting this feature. The LD structure is changing time to time but this lib could not catch up
