### ISSUE TITLE
Next.js does not display meta tags in Next.js 14

### ISSUE THREAD

**Issue by mxcdh** [garmeeh/next-seo#1356]
I have a strange problem with next-seo and next.js 14. In next.js 13, next-seo works without any issues. However, in next.js 14, only the metadata is working. The example code shows that the metadata is functioning, but the next-seo is not (the page is without a title).

```
...

export const metadata: Metadata = {
  title: "Create Next App111",
  description: "Generated by create next app",
};

const App = () => {
  return (
    <>
...

```

```
import { NextSeo } from "next-seo";
import Head from "next/head";
...


const App = () => {
  return (
    <>
      <Head>
        <NextSeo
          title="Simple Usage Example"
          description="A short description goes here."
        />
      </Head>

```

NextSeo is not working on Next.js 14. How can I fix it?

**Comment by yoopark** [comment]
Same issue.

**Comment by garmeeh** [comment]
Looks like you are using `<NextSeo />` component within the app directory. For standard meta data you can use built in features of [next.js](https://nextjs.org/docs/app/building-your-application/optimizing/metadata#usage)

**Comment by jhoanborges** [comment]
so is this not compatible with next 14 ?  i had the same problem.
