### ISSUE TITLE
JSON-LD components should accept `key` so that they handle multiple instances per page.

### ISSUE THREAD

**Issue by mikestopcontinues** [garmeeh/next-seo#136]
The title says it all. The JSON-LD spec allows for multiple instances, essential for blog rolls or search pages. `key` seems like the most canonical way to handle this behavior, perhaps retaining the default key as a prefix. What do you think?

**Comment by mikestopcontinues** [comment]
Switched PR from `key` to `id` because `key` doesn't get passed by React.

**Comment by garmeeh** [comment]
Hey @mikestopcontinues, for blog rolls or search pages I think you would be better off using something like [CollectionPage](http://schema.org/CollectionPage) maybe 🤔 

Each of the Schemas on the PR would only be used once on a page so I don't think there would be a use for exposing the key. 

This question and answer goes gives good context: 

https://webmasters.stackexchange.com/questions/99095/schema-org-collectionpage-for-list-of-blog-posts-by-specific-author


But once each of your item pages / blog pages has the Schema in place, your SEO will be in a good place.

**Comment by mikestopcontinues** [comment]
Hey @garmeeh, I don't think CollectionPage fits the bill, especially since it's not officially supported in [google's search docs](https://developers.google.com/search/docs/data-types/article). A page containing multiple articles, courses, offers, etc. should have either multiple json-ld tags for each, or an array of those present on the page. I definitely overcompensated in my PR (Logo, Breadcrumb), but wouldn't most of the schemas plausibly be used more than once per page on a variety of sites?

**Comment by garmeeh** [comment]
Yeah when I originally researched this I decided to not add in CollectionPage as it's not really supported by Google.  From my understanding there would never be a case where a schema would be used more than once on a page. There is a generally a schema that will fit the bill for the page. 

For example if you are talking just about a blog listings page you could go with something like [Blog](https://schema.org/Blog). But again this is no technically supported by Google. But I'm sure they still parse it. 

I think Google might suggest using [Carousel](https://developers.google.com/search/docs/data-types/carousel) to add a collection of their supported items 🤔

**Comment by marco-000** [comment]
Hello @garmeeh, are there any plans for the Carousel component?

**Comment by garmeeh** [comment]
Hey @marco-000 yeah Carousel is something I would like to add in the near future.

**Comment by tomgreeEn** [comment]
I'm also interested in this - if you don't recommend reusing multiple instances of schemas on page, what would be the best way to add multiple Products to a higher level Product List page using next-seo?
