### ISSUE TITLE
GatsbyJS port of next-seo

### ISSUE THREAD

**Issue by ifiokjr** [garmeeh/next-seo#138]
### Description

This is purely to say thank you for this library. I've enjoyed using it so much I decided to port it over to [GatsbyJS](https://www.gatsbyjs.org/). 

I've released the first version of [**gatsby-plugin-next-seo**](https://github.com/ifiokjr/gatsby-plugin-next-seo). 

Unfortunately better names like [gatsby-seo](https://www.npmjs.com/package/gatsby-seo) and [gatsby-plugin-seo](https://www.npmjs.com/package/gatsby-plugin-seo) were already taken 😢  

I've added the same tests and it has the same features as `next-seo`. 

- Server side rendering (SSR)
- Default configuration via `gatsby-config.js`

So if you happen to love `next-seo` as much as I do and would like to use the same API in any of your gatsby projects please give it a try.

**Comment by garmeeh** [comment]
👏 Deadly! Really glad you found it useful and were able to port it. I will defiantly keep an eye on it and port over any new features that are added on your end 😄 

Please feel free to open a PR adding a link to the Gatsby version from here also.
