### ISSUE TITLE
Meta tags are placed inside body instead of head tag.

### ISSUE THREAD

**Issue by Shivamaggw** [garmeeh/next-seo#1387]
Hello @garmeeh 

I'm using Next 13 with 15.5.0 version of next-seo.
After reading the source code, I understood that the plugin is generating and returning the array of the meta tags and returning it. By this logic, the tags should be visible inside the dom according to where I used the <NextSeo> component. Which might be the body in most cases. The usage example provided in the documentation also placed the <NextSeo> component adjacent to a paragraph tag.

Reference: https://github.com/garmeeh/next-seo/tree/v5.15.0#:~:text=(%0A%20%20%3C%3E-,%3CNextSeo,-title%3D%22Simple
![image](https://github.com/garmeeh/next-seo/assets/29908380/d386ab0e-3b69-42dc-87ff-98d266860ed0)

**Reproduction**
The reproduction of this issue hasn't been possible for me to be created in a Sackblitz yet.
Weirdly in my app, the tags are inside the head tag of the source HTML in the browser in some pages, and in the rest, it's appearing in the Body tag, hence SEO and Mea data extraction isn't working as expected.

**Additional info about my implementation**
1. I'm using an app router with a common layout file in the root of the app
2. Default SEO is not being used in the app.
3. Next Version: 13.1.0
4. Next-Seo version: 5.15.0

**Questions**
1. Is there any identified reason of why tags could be inside the body?
6. How are tags expected to be in the head when the plugin component just creates and returns the meta tags at the place of its usage in the code?

Thanks in Advance!!

**Comment by Shivamaggw** [comment]
@garmeeh - Thanks a ton for the Super quick response.

I agree that migrating to Next 14 would be a great path. However, due to constraints, I can't upgrade my NextJs version. Would be a super great help if anyone in the community could help with their insights or any near-above-mentioned encounters.

**Comment by garmeeh** [comment]
@Shivamaggw would you be able to update to `v13.2.0` of Next.js? 🤞 

The metadata was added in this version.

**Comment by Shivamaggw** [comment]
@garmeeh, Okay yes! I probably overlooked it. Let me try that. Thanks for the suggestions.
