### ISSUE TITLE
Adding stylesheets and script to head

### ISSUE THREAD

**Issue by VictorBaudot** [garmeeh/next-seo#141]
Hello, I'm currently just using next/head and I'm wondering where I should put my stylesheets links and scripts that I was previously putting in the Head component?

**Comment by garmeeh** [comment]
Hey @VictorBaudot, so `next-seo` is designed to supplement `next/head` so you can leave all non SEO related items within `next/head`.

**Comment by kamal-choudhary** [comment]
I'm also confused what is the best practice to add `<NextSEO />` and also the `<Head>` for the custom `script` and `link` tags in the same page.

Currently, I'm using it like this.

```
<NextSeo {...SEO} />
       <Head>
        <link
          rel="stylesheet"
          type="text/css"
          href="https://example.com/styles.css"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(myCustomSchemaData) }}
        />
      </Head>
       <BreadcrumbJsonLd
        itemListElements={[
          {
            position: 1,
            name: "Home",
            item: `${process.env.NEXT_PUBLIC_BASE_URL}`,
          },
        ]}
      />
```

The tags are rendered correctly in the `<head>` tag, but I feel that it is not the best approach.
