### ISSUE TITLE
opengraph attributes inherit from main attributes

### ISSUE THREAD

**Issue by Enalmada** [garmeeh/next-seo#15]
I feel like opengraph title/description/url attributes should default to the regular title/description/canonical if not set.  Having to pass the same things in twice seems redundant for the avg use case....I suspect most people generally want title/description/url/canonical to be the same in both places.   It would be more convenient if og attributes were more like overrides.

**Comment by Enalmada** [comment]
I can't think of why someone wouldn't want them in this day and age either but I think that is a reasonable requirement if documented in readme.  Most people using opengraph tags will likely have something like this in their config/base:
```
openGraph: {
        type: "website",
        locale: "<locale>",
        site_name: "MySite.com",
        defaultImageWidth: 1000,
        defaultImageHeight: 523,
    }
```

**Comment by garmeeh** [comment]
Cool, I will look to add this V2. Hoping to get time over the next few weeks to start working on some improvements.

So I will add:

```
title -> og:title
description -> og:description
canonical -> og:url
```

And also apply the title template to `og:title`.

**Comment by nagman** [comment]
Waiting forward!

**Comment by johnruane** [comment]
Can anyone confirm the correct behaviour of the OG tags. I noticed that when the opengraph object is passed with missing data (title, description, url) the fields do inherit the respective main fields. I thought this was a bug in my code. I can't find this behaviour documented anywhere.
