### ISSUE TITLE
Sharing the web url on whatsapp image not showing

### ISSUE THREAD

**Issue by findela** [garmeeh/next-seo#152]
I have written code in the way which should show image on whatsapp while sharing link,by the way on Facebook and other social platform, image is showing perfectly, what went wrong for this,no clue -

My Code : 

`<NextSeo config=
						 {
							 {
								 title: this.firstLetterUpper(this.props.blogDetails.blogTitle),
								 titleTemplate: `Collegify | %s`,
								 copyright: 'Collegify has copyrights to all the content of this page',
								 keywords: _.map(this.props.blogDetails.tags, 'tagName').join(', '),
								 description: this.stringToHTML(this.props.blogText),
								 openGraph: {
									 url: env.APP_URI + this.props.router.asPath,
									 locale: 'en_IN',
									 title: this.firstLetterUpper(this.props.blogDetails.blogTitle),
									 type: 'website',
									 description: this.stringToHTML(this.props.blogText),
									 images: [
										 {
											 url:  `${this.state.blogImage !== '/static/images/blog/default-blog.png' ? env.FILE_URI : env.APP_URI}${this.state.blogImage}`,
											 width: 200,
											 type: 'image/png',
											 height: 200,
											 alt: this.firstLetterUpper(this.props.blogDetails.blogTitle),
										 }
									 ],
									 site_name: 'collegify',
								 },
							 }
						 }
					/>`

Output : 

![FireShot Capture 098 - WhatsApp - web whatsapp com](https://user-images.githubusercontent.com/8926058/73525113-821abd00-4434-11ea-8f0c-155ff4db4425.png)

Expected Output : 

![FireShot Capture 099 - WhatsApp - web whatsapp com](https://user-images.githubusercontent.com/8926058/73525186-b0000180-4434-11ea-8f81-8a04e622ac5c.png)

Is that file size matters?

**Comment by garmeeh** [comment]
Hey @findela can you make sure that the image URL is an absolute URL?

**Comment by findela** [comment]
Yes it's full qualified absolute URL, it's strange that it works only with images < 300 KB which I think so.

**Comment by garmeeh** [comment]
Hey @findela just doing a bit of checking and it does seem that 300kb is the max for whats app.
