### ISSUE TITLE
pages with Dynamic links (randomly generated)  doesn't show the OG data

### ISSUE THREAD

**Issue by shakesBeardZ** [garmeeh/next-seo#159]
in my application, I have a few pages that get opened with dynamically generated links like:
example.com/:id 
which will open a page called page1 for example, those pages with random links they don't render the OG data even if the data is there(I inspected the head tag).

the other pages with static names, they render the OG data with success.
I hope anyone here can have an explanation for that behavior.
Note: I always override the default SEO

**Comment by garmeeh** [comment]
Would you be able to provide an example reproducing the issue?
