### ISSUE TITLE
Passing custom meta tags

### ISSUE THREAD

**Issue by TLevesque** [garmeeh/next-seo#16]
Great package! I'm testing it as a Nextjs plugin and it works really good! 

Just wondering if it is possible to pass into the next-seo.config.js file some "custom" meta tag like author, keywords, ... (some of https://gist.github.com/lancejpollard/1978404) to handle all the head tags in one place?
Like ```export default {
  title: "My website",
  description: "Describing my website",
  canonical: "https://www.canonical.ie/b",
  keywords: "keywords stuffing",
  author: "A cool guy",
  openGraph: {...```

Or is it out of the scope of next-seo package?

**Comment by garmeeh** [comment]
Good question. I suppose my initial idea is to support the most common SEO tags and try to use the best practice tags. This way it covers most use cases and keeps the library reasonably small. 

I would recommend using `next/head` alongside `next-seo` to handle other meta tags along with rarer SEO related ones.

I am of course open to adding new tags if there is a strong use case for them.

For example, `keywords` is not really used anymore so I have omitted this one on purpose. The `author` tag is another one that is not really used. For that you could use the html `rel=author` or even better if it's a blog/article you could use one of the JSON-LD's for it.

--- 

Seperate to this, there maybe a way I can refactor the code to pass an array of meta tags to render. Something like:

```
meta: [
  {
   name: 'description',
   content: 'This is the description'
  },
  {
   name: 'keywords',
   content: 'nextjs, seo'
  }
]
```

This might be a way of allowing that flexibility.

**Comment by TLevesque** [comment]
Thanks Gary for this feedback! Yep, this refactor could be great to pass down some extra tags.
