### ISSUE TITLE
experimental flag polyfillsOptimization  does not work with this module

### ISSUE THREAD

**Issue by dohomi** [garmeeh/next-seo#178]
Hi Guys

I tried to enable 
```
experimental: {
      modern: true,
      polyfillsOptimization: true
}
```
This results into following error: 
```
ModuleNotFoundError: Module not found: Error: Can't resolve '@babel/runtime-corejs2/core-js/array/is-array'
```
This is early adopter code so I just wanted to bring this up in case the feature finally lands into NextJS core

**Comment by nodabladam** [comment]
I don't believe this is an experimental issue.  I just updated to next.js 9.2.3-canary.8 to test something and (without adding any experimental flags) got:
```
[ error ] ./node_modules/next-seo/lib/jsonld/localBusiness.js
Module not found: Can't resolve '@babel/runtime-corejs2/core-js/array/is-array' in '\node_modules\next-seo\lib\jsonld'
```

**Comment by manovotny** [comment]
@nodabladam that's because [v9.2.3-canary.1](https://github.com/zeit/next.js/releases/tag/v9.2.3-canary.1) enables the polyfills optimization by default without needing the experimental flag, so it is still an issue.

**Comment by nodabladam** [comment]
Agreed...I poorly worded an attempt to emphasize that it is very soon to be a problem for everyone.
