### ISSUE TITLE
Feature request: additionalLinkTags

### ISSUE THREAD

**Issue by oyeanuj** [garmeeh/next-seo#182]
Hi @garmeeh, thank you for creating this excellent library!

Like you have `additionalMetaTags`, I'm wondering if the library should also support `additionalLinkTags`?

My use-case is the following tags, which I think makes sense to be part of the default config more than separately in `_app.js`:

```html
<link rel="manifest" href="/manifest.json" />
<link
  rel="apple-touch-icon"
  sizes="196x196"
  href="/favicons/favicon-196x196.png"
/>
<link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#EC7952" />
<link
  rel="icon"
  type="image/png"
  href="/favicons/favicon-196x196.png"
  sizes="196x196"
/>
```

**Comment by Samia195** [comment]
Add the #511

**Comment by modbender** [comment]
Wow I also had that idea.

**Comment by Akshat-ops** [comment]
> Hi @garmeeh, thank you for creating this excellent library!
> 
> Like you have `additionalMetaTags`, I'm wondering if the library should also support `additionalLinkTags`?
> 
> My use-case is the following tags, which I think makes sense to be part of the default config more than separately in `_app.js`:
> 
> ```
> <link rel="manifest" href="/manifest.json" />
> <link
>   rel="apple-touch-icon"
>   sizes="196x196"
>   href="/favicon/favicon-196x196.png"
> />
> <link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#EC7952" />
> <link
>   rel="icon"
>   type="image/png"
>   href="/favicons/favicon-196x196.png"
>   sizes="196x196"
> />
> ```

**Comment by chrisbull** [comment]
Second this suggestion.
