### ISSUE TITLE
ProductJsonLd is not working

### ISSUE THREAD

**Issue by epg323** [garmeeh/next-seo#19]
ProductJsonLd is not working I get this error: 'Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `ProductDetails`.' 

I tried ArticleJsonLd and it does work.

**Comment by garmeeh** [comment]
Hey @epg323, sorry I missed the notification for this issue. 

Are you still having this issue and I will look into it?

I can't re-create on my side so if you had an example that would help.

**Comment by epg323** [comment]
Sorry about that I was out for vacation. The update fixed it no issues anymore. Thanks!

**Comment by garmeeh** [comment]
No problem. The white space shouldn't affect much, the `json` will still be valid.
