### ISSUE TITLE
EventJsonLd doesn't work

### ISSUE THREAD

**Issue by vvmspace** [garmeeh/next-seo#190]
I have components:
EventCardList and EventCard:
in EventCard im using:
```
<Card className={classes.root} style={{width: '100%'}}>
            <EventJsonLd
                name={event.name}
                startDate={event.date}
                // endDate={event.end_date}
                location={{
                    name: event.venue.name,
                    sameAs: `https://concert.moscow/${event.venue.alias}`,
                    address: {
                        streetAddress: event.venue.address,
                        addressLocality: 'Moscow',
                        addressRegion: 'Moscow region'
                    }
                }}
                url={`https://concert.moscow/concert/${event.alias || event.uuid}`}
                description={`Билеты без наценки и сервисного сбора от ${event.min_price} ₽`}
            />
...
</Card>
```
And I can not find it in page source.

I have overwrited pages/_document.jsx and have no _app.js. Also I'm using Material UI.

Is it bug or some my mistake?
Please help

Project is here (in branch concertmoscow):
https://github.com/vvmspace/next-template/tree/concertmoscow

EventCard component:
https://github.com/vvmspace/next-template/blob/concertmoscow/components/EventCard/index.js

EventCardList component:
https://github.com/vvmspace/next-template/tree/concertmoscow/components/EventCardList/EventCardList.js

_document.jsx
https://github.com/vvmspace/next-template/blob/concertmoscow/pages/_document.jsx

May be I'm newbie:) Thank you!

*Updated:*
It works, but only on frontend :-(

**Comment by garmeeh** [comment]
Hey, so from what I can see you will try load multiple EventCards on one page using the EventCardList component? 

This will not work. The EventJsonLd should exist at a page level. So there should only ever be on EventJsonLd on the page. 

Not sure if you are just seeing one and that is what is making it look broken?
