### ISSUE TITLE
Module not found after pruning devDependencies

### ISSUE THREAD

**Issue by genox** [garmeeh/next-seo#202]
Hi,

I get the following error message in production using next-seo@latest after stripping the project of devDependencies:

```Error: Cannot find module '@babel/runtime/helpers/interopRequireWildcard'
Require stack:
- /node_modules/next-seo/lib/index.js
- /.next/server/static/3sVp8qbx995daYZPgBBaY/pages/_app.js
- /node_modules/next/dist/next-server/server/load-components.js
- /node_modules/next/dist/next-server/server/api-utils.js
- /node_modules/next/dist/next-server/server/next-server.js
- /node_modules/next/dist/server/next.js
- /dist/server/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/node_modules/next-seo/lib/index.js:1:42)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/node_modules/next-seo/lib/index.js',
'/.next/server/static/3sVp8qbx995daYZPgBBaY/pages/_app.js',
    '/node_modules/next/dist/next-server/server/load-components.js',
    '/node_modules/next/dist/next-server/server/api-utils.js',
    '/node_modules/next/dist/next-server/server/next-server.js',
    '/node_modules/next/dist/server/next.js',
    '/dist/server/index.js'
  ]
}
(node:25484) UnhandledPromiseRejectionWarning: Error: Cannot find module '@babel/runtime/helpers/interopRequireWildcard'
Require stack:
- /node_modules/next-seo/lib/index.js
- /.next/server/static/3sVp8qbx995daYZPgBBaY/pages/_app.js
- /node_modules/next/dist/next-server/server/load-components.js
- /node_modules/next/dist/next-server/server/api-utils.js
- /node_modules/next/dist/next-server/server/next-server.js
- /node_modules/next/dist/server/next.js
- /dist/server/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/node_modules/next-seo/lib/index.js:1:42)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
(node:25484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:25484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Steps to reproduce:

- Build nextjs app
- Run my app locally and connect, everything seems to be fine
- Run either `npm prune --production` or `yarn install --production`
- Run app locally again, errors out on server side rendering with the above trace

I noticed that up to 4.1.0 everything works as expected, 4.2.0 seems to be introducing the issue.

Best regards,
Oliver

**Comment by RobbyUitbeijerse** [comment]
Hi @genox !

Any chance you are using a custom babel configuration for your project? I was running into the same issue, but only on next.js 9.3 (which introduced [auto polyfills](https://nextjs.org/blog/next-9-3#32-kb-smaller-runtime-15-kb-gzip)). Our babel config included the following:

**babel.config.js**

```
    [
      '@babel/plugin-transform-runtime',
      {
        corejs: 3,
      },
    ],
```

we removed this entire piece of config, and it resolved our issue with the missing @babel/runtime dep after pruning.

**Comment by genox** [comment]
Hej,

I do have a custom babel config for styled components and decorators. I ended up on a similar track and ended up adding `@babel/runtime-corejs2` to regular dependencies after I noticed that it was missing as an import from one of the source files of this module at compile time when I upgraded to NextJS 9.3. Maybe some other side effect ... don't ask me what's going on exactly, but it works™ on `nextjs@9.3` and the latest version of this `next-seo`.

**Comment by garmeeh** [comment]
Hey @genox, sounds like this is working as expected now.

Please re-open if I was mistaken.

**Comment by vimota** [comment]
I still ran into this error `Can't resolve '@babel/runtime-corejs2/core-js/array/is-array' in '/Users/vimota/code/vimota/node_modules/next-seo/lib/jsonld'` with no custom babel configuration.

Running `npm install --save-dev @babel/runtime-corejs2` resolved it, so perhaps it needs to be added as a dependency?

**Comment by RobbyUitbeijerse** [comment]
@garmeeh we are running into the same situation that @genox is describing in his latest comment now that we actually upgraded to next.js 9.3  (https://github.com/garmeeh/next-seo/issues/202#issuecomment-598394081) 

Adding @babel/runtime-corejs2 to the depedencies resolves the issue as it prevents it from betting removed while pruning the modules for production, but it's far from an elegant solution imho since it's not our depedency, it's a depedency from next-seo :-)

**Comment by RobbyUitbeijerse** [comment]
removed my comment - we are not experiencing this issue anymore from next@9.3 anymore
