### ISSUE TITLE
OpenGraph is not working in my Next JS project

### ISSUE THREAD

**Issue by 1BigBoom** [garmeeh/next-seo#203]
import React from 'react';
import { NextSeo } from 'next-seo';

export default () => (
  <>
    <NextSeo
      title="Using More of Config"
      description="This example uses more of the available config options."
      canonical="https://www.canonical.ie/"
      openGraph={{
        url: 'https://www.url.ie/a',
        title: 'Open Graph Title',
        description: 'Open Graph Description',
        images: [
          {
            url: 'https://www.example.ie/og-image-01.jpg',
            width: 800,
            height: 600,
            alt: 'Og Image Alt',
          },
          {
            url: 'https://www.example.ie/og-image-02.jpg',
            width: 900,
            height: 800,
            alt: 'Og Image Alt Second',
          },
          { url: 'https://www.example.ie/og-image-03.jpg' },
          { url: 'https://www.example.ie/og-image-04.jpg' },
        ],
        site_name: 'SiteName',
      }}
      twitter={{
        handle: '@handle',
        site: '@site',
        cardType: 'summary_large_image',
      }}
    />
    <p>SEO Added to Page</p>
  </>
);

**Comment by 1BigBoom** [comment]
"dependencies": {
    "next": "^9.2.2",
    "next-seo": "^4.4.0",
    "react": "^16.13.0",
    "react-dom": "^16.13.0"
}

**Comment by 1BigBoom** [comment]
Please help me

**Comment by jakapatb** [comment]
+1 
In my Project, It's work on localhost but not working on production.

dependencies
- "next": "9.3"
- "next-seo": "4.4.0"

PS. It was working on my project before upgrade Next.js (not sure 9.22 or 9.3).

**Comment by jakapatb** [comment]
Use this pattern for now util next-seo fixed.
```
import Head from 'next/head'
.
.
.
<Head>
    <meta property="og:title" content={'title'} />
    <meta name="og:description" content={'description'} />
</Head>
```

**Comment by garmeeh** [comment]
@1BigBoom I have checked the code example you have supplied and it works as expected. Can you provide a recreation for it so I can test further?

@jakapatb I have done some more manual testing around Open Graph and have verified it is working as expected. If you can provide a recreation I can investigate further.

**Comment by rolandtshen** [comment]
@garmeeh I think I'm experiencing a similar issue. Here's a page where I have next-seo enabled: https://read.imprint.to/post/5e89a275dcb11300c007c599. If you inspect element, you can see all the appropriate meta tags in the head, but none of the right tags show up when viewing page source (I think the crawlers use the page source to find meta tags). I'm fetching data via getInitialProps, and loading data into next-seo via props. Thanks for any help!

**Comment by garmeeh** [comment]
Hey @rolandtshen from taking a very quick look at your site I believe there may other issues. For a server rendered site if you disable javascript in the browser and reload the page it should render all of the HTML, but this is not the case for your site. This makes me think there is an issue server side with your app.

**Comment by rolandtshen** [comment]
Thanks, @garmeeh! Took a look, and found out my problem was that I was conditionally rendering my page based on whether or not some data was loaded. Since I was rendering null until the page loaded properly, the meta tags weren't being inserted in. Can confirm next-seo's working as intended now.

**Comment by amorriscode** [comment]
I noticed that I have the same problem. It works on Twitter and Slack, however on FB it does not. You can see the effect happening here. It looks like the default SEO overrides the page SEO in production.
