### ISSUE TITLE
Multiple <script type="application/ld+json"> tags in document

### ISSUE THREAD

**Issue by dmitrizzle** [garmeeh/next-seo#209]
An example is a `<Page />` that's an article with available breadcrumbs data. The `<Page />` consists of two components: `<Article />` itself and <BreadCrumbs />.

`<Page />`
```javascript
export default () => <>
  <Breadcrumbs />
  <Article />
</>
```

`<Artcile />`
```javascript
export default () => <>
  <NextSeo title={"Page"} />
  <ArticleJsonLd title={"Page"} />
  <p>Page</p>
</>
```

`<BreadCrumbs />`
```javascript
export default () => <>
  <BreadcrumbJsonLd itemListElements={[{ name: "Page", item: "domain.com/page"}]} />
  <p>Home > Page</p>
</>
```

With this setup, in HTML we'll end up with two `<script type="application/ld+json">` tags:
```
<head>
<script type="application/ld+json">{
  "@context": "http://schema.org",
  "@type": "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "domain.com/page"
  },
  "headline": "Page",
}</script>
<script type="application/ld+json">{
  "@context": "http://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "item": {
        "@id": "https://www.analog.cafe/photo-essays",
        "name": "Photo Essays"
      }
    }
  ]
}</script></head>
```

I'm not sure if this to cause any problems but certainly would like to know.

**Comment by italoayres** [comment]
This appears to be Ok, according with this StackOverflow topics:
[Best JSON-LD practices: using multiple <script> elements?](https://stackoverflow.com/questions/30723531/best-json-ld-practices-using-multiple-script-elements)
[Can I have multiple JSON-LD scripts in the same page?](https://webmasters.stackexchange.com/questions/96903/can-i-have-multiple-json-ld-scripts-in-the-same-page)

But I'm not sure if it is the library correct behavior.

**Comment by garmeeh** [comment]
Thanks @italoayres. 😄 Yes it's perfectly ok to have multiple JSON-LD scripts on the page.
