### ISSUE TITLE
Jest react test library

### ISSUE THREAD

**Issue by najandz** [garmeeh/next-seo#212]
Hi, 
I am super excited when I found this solution for SEO metadata and structured data. I would like to know if you guys can give me some idea how to write test with using Jest react test library to verify all the metadata and title of my page, 

Cheers,

**Comment by garmeeh** [comment]
Hey @najandz, thanks 😄 

I would normally test this kinda of thing with the likes of Cypress which of course does not answer your question. 

I don't have much experience in testing the actual page itself with Jest so not too sure how to advise you. I would suggest posting a question over on [here](https://github.com/zeit/next.js/discussions) or [here](https://spectrum.chat/next-js?tab=posts) about how to test what's in the head in general.

**Comment by najandz** [comment]
Thanks, @garmeeh for the quick reply, I've posted there, and I am looking forward to getting some leads.

Cheers,

**Comment by Ethaan** [comment]
@najandz see answer on https://github.com/vercel/next.js/discussions/11060
