### ISSUE TITLE
Additional Properties for SocialProfile

### ISSUE THREAD

**Issue by timReynolds** [garmeeh/next-seo#23]
Although not well documented the markup for social profile is normally used with other related properties like description, telephone, address and logo (org only) show in the valid JsonLd below; 

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Organization",
  "name": "your name",
  "description": "Some description", 
  "telephone": "+19172423826",
  "url": "http://www.your-site.com",
  "sameAs": [
    "http://www.facebook.com/your-profile",
    "http://instagram.com/yourProfile",
    "http://www.linkedin.com/in/yourprofile",
    "http://plus.google.com/your_profile"
  ],
    "address" :{
    "@type": "PostalAddress",
    "streetAddress": "123 William St",
    "addressLocality": "New York",
    "addressRegion": "NY",
    "postalCode": "10038",
    "addressCountry": "US"
  },
  "logo": "http://www.example.com/images/logo.png"
}
</script>
```

I'm happy to add support for these additional properties to social profile or I could as new structured data types as Logo and Local Business which is how the[ google documentation](https://developers.google.com/search/docs/data-types/local-business) refers to them, although technically they're supported in the same block as social information. 

@garmeeh I'm planning to do this work as I need it either locally or as a PR if you can provide some guidance on how you'd prefer this done. 

If any of this isn't clear please let me know.

**Comment by garmeeh** [comment]
Hey @timReynolds, yeah the above is how I would have always done it myself. When looking into the social profile I thought it might be a safer bet to go with how Google is now recommending it. 

I think adding Logo and Local Business as new data types would be the best way forward.

If adding these they would need to be covered by end to end tests in `jsonld.spec.js`. 

For Local Business, I would be happy with a minimal version to cover your use case. Maybe something like:

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Organization",
  "image": [
    "https://example.com/photos/1x1/photo.jpg",
    "https://example.com/photos/4x3/photo.jpg",
    "https://example.com/photos/16x9/photo.jpg"
   ],
  "@id": "http://www.example.com",
  "name": "Local Business",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "148 W 51st St",
    "addressLocality": "New York",
    "addressRegion": "NY",
    "postalCode": "10019",
    "addressCountry": "US"
  },
  "url": "http://www.example.com/restaurant-locations/manhattan",
  "telephone": "+12122459600"
}
</script>
```

I can then extend it to add opening hours and actions etc. once published with this minimal needed.

**Comment by timReynolds** [comment]
Sounds good, I’ll look into this over the next few days
