### ISSUE TITLE
Keywords?

### ISSUE THREAD

**Issue by heymartinadams** [garmeeh/next-seo#329]
First of, Gary, what a wonderful creation! **Thank you!** ✨ (If my business grows and can afford it, I’ll def sponsor you! We haven’t launched yet.)

Question: nowhere do I see a mention of SEO keywords. Any particular reason?

**Comment by frankn11** [comment]
I'm not sure about the reason, but you can use the `additionalMetaTags` prop.
https://github.com/garmeeh/next-seo#additional-meta-tags

**Comment by heymartinadams** [comment]
Great, thank you! 🎉
