### ISSUE TITLE
Default title prop

### ISSUE THREAD

**Issue by switz** [garmeeh/next-seo#366]
It would be nice to set a default title. Let's say the website is `Github`.

I'd do (in _app.js):

```
<NextSeo titleTemplate="%s - Github" defaultTitle="Github" />
```

If there's no title set later in the document, it would fall back to `Github`. If there is, it would be replaced with the title template, e.g. `Blog - Github`.

There's a few nice UX wins with this, happy to expand more if they're non-obvious.

**Comment by garmeeh** [comment]
Hey @switz, if you were add the following to `_app.js` would it achieve what you are looking for? 

```
<DefaultSeo titleTemplate="%s" title="- Github" />
```

**Comment by switz** [comment]
Well, I think `fallbackTitle` would make more sense for my use-case. But there may be other usecases that prefer the other. I'll always have a `titleTemplate` set (in app.js), but for example, if I set title to `Github` on the index page, it would return `Github - Github` (due to the title template). So if I was able to set `fallbackTitle` when there is no title set, it would negate the `titleTemplate`.

I believe this also has the benefit of having a preliminary title set in the case of html streaming, before the full page has rendered out, but I could be wrong, I'm not an expert in that.

**Comment by spostad7** [comment]
same issue,
any improvement on this @garmeeh?

**Comment by matteing** [comment]
This is hugely useful :)

**Comment by trevorblades** [comment]
@switz @garmeeh I just opened a PR that adds a `defaultTitle` param in the style of `react-helmet`. In short, if a `defaultTitle` is added, then pages with no `title` defined will still get the default value.

For example, let's say I had the following in my `_app.js`:

```js
<DefaultSeo titleTemplate="%s - MyApp" defaultTitle="MyApp" />
```

My home page might look like this:

```js
<NextSeo title="Sweet keywords" />
// renders <title>Sweet keywords - MyApp</title>
```

But another page in my website that doesn't have a `title` set would still render a `<title>` tag with "MyApp" only.

**Comment by switz** [comment]
Awesome work!

**Comment by trevorblades** [comment]
FYI, you can accomplish this "default/fallback title" behaviour by simply adding a `<title>` to your `_app.js` file:

```jsx
import Head from 'next/head';
import {DefaultSeo} from 'next-seo';

export default function App({Component, pageProps}) {
  return (
    <>
      <Head>
        <title>My default title</title>
      </Head>
      <DefaultSeo titleTemplate="%s - My app" />
      <Component {...pageProps} />
    </>
  );
}
```
