### ISSUE TITLE
disable googlebot tag

### ISSUE THREAD

**Issue by angus-kablamo** [garmeeh/next-seo#367]
Hey, I'd like to use this plugin for a project however the client's SEO team are requesting that we remove the googlebot tag as they consider it "noise covered by the robots tag". The request baffles me but would you accept a PR to add a prop to disable it?

**Comment by garmeeh** [comment]
😂 Yeah this one baffles me also. I can't see anyway it would hurt. 

Yeah I think adding a single boolean to disable the default tags wouldn't add much overhead. 

A PR sounds good to me 👍

**Comment by garmeeh** [comment]
Hey @angus-kablamo please feel free to follow up with a PR if still a requirement.

**Comment by angus-kablamo** [comment]
@garmeeh Apologies this took a while. Added a boolean in this PR https://github.com/garmeeh/next-seo/pull/458

**Comment by riccardogiorato** [comment]
Hey @garmeeh is there any news on this feature? Can you reopen this issue?
