### ISSUE TITLE
Module Not Found - Pruning For Production

### ISSUE THREAD

**Issue by kmdev1** [garmeeh/next-seo#369]
Hey there,

Firstly just wanted to say great little helper!

I was just wondering if you've been experiencing any issues recently strongly related to #202?

It appears that the babel runtime issue is back and it's causing us a few headaches 🤦 

Current versions that we're using are:

`"next-seo": "^4.5.0"`
`"next": "^9.4.0"`

**Comment by tonytoth** [comment]
@kmdev1 seems like installing `@babel/runtime-corejs2` fixed the problem.
