### ISSUE TITLE
Unable to add <title> AND <meta name="title" content="x">

### ISSUE THREAD

**Issue by janinel** [garmeeh/next-seo#377]
Our SEO team want to replicate the title in the metatags. To do this tried using additionalMetaTags  but it looks like the title and the additionMetaTag have a key of 'title' so <title>x</title> gets suppressed.

<NextSeo 
    title="x'
    additionalMetaTags=[{
      name: 'title',
      content: 'x'
    }] />

An easy fix would be to namespace the meta keys 
or (less impact) the title key
- what do you think?

**Comment by garmeeh** [comment]
Hey @janinel  yeah I can take a look at this and what impact it might have.

**Comment by idiglove** [comment]
Hi @garmeeh Can you give some context on how to fix this? I can take a look at it. What is the desired outcome?
