### ISSUE TITLE
Twitter cards not rendering images and title and description is always being fetched from the <DefaultSeo/> 

### ISSUE THREAD

**Issue by Anup-Borde** [garmeeh/next-seo#383]
Hi Garmeeh,

Thank you for this wonderful library. I have used it on a sample nextjs project and it works fine. However, when I tried using it on one of my websites I am not able to get the twitter cards working.
I am sharing a gist of my _app.jsx and with-lyout.jsx files for your reference please find the same below:-
https://gist.github.com/Anup-Borde/45a6ea4f3a4f13acfcfc1d89f8bdbea3
Please find a screenshot for the twitter card validator for your reference:-
https://imgur.com/a/Exu2Qk9
At first, I thought it was a next js issue so I updated the next js version but it still did not give me the desired result.
Following are the next js and next SEO versions I am using:-
 "next": "^9.4.4",
 "next-seo": "^4.5.0"
I have been struggling to get it to work for over a week now and I would like to get it fixed. Please help me resolve this issue at the earliest.
Once again I would like to thank you for next-seo.
Any help or suggestion to resolve this issue is appreciated.Thank you.

**Comment by MM3y3r** [comment]
We currently have the same issue in production. Quite a huge problem actually.

**Comment by garmeeh** [comment]
Will investigate this after work this evening. Will report back.

**Comment by okybr** [comment]
For the record: Downgrading `next-with-apollo` from 5.0.1 to 4.3.0 fixed the issue of me and @MM3y3r.

**Comment by garmeeh** [comment]
After investigating this I am thinking that this might be related to another library potentially. 

If you take a look at this Code Sandbox it seems to be working as expected? 

https://codesandbox.io/s/github/garmeeh/next-seo-test

Maybe I have miss understood the problem.

**Comment by Anup-Borde** [comment]
@MM3y3r are you able to resolve this issue. @okybr I am not using next-with-apollo @garmeeh  I am using the same version of next and next-seo that you are using. I am able to see the tags when I inspect but when I try to validate it on twitter card validator it isn't working. 
1)The image does not load
2)The og:title and og: description are always taken from the default SEO even though I see that they have been changed when I inspect the page.
Can you check why it isn't working on this page:-
https://www.earlysalary.com/blogs/how-many-ways-can-you-get-a-personal-loan-in-india-2

**Comment by okybr** [comment]
@garmeeh, as i said, it seems to be related to next-with-apollo which is not used in your code-sandbox.

**Comment by MM3y3r** [comment]
> For the record: Downgrading `next-with-apollo` from 5.0.1 to 4.3.0 fixed the issue of me and @MM3y3r.

Yes. We resolved it. Thank you!

**Comment by qlaffont** [comment]
Same issue for me : 

```
"dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.29",
    "@fortawesome/free-brands-svg-icons": "^5.13.1",
    "@fortawesome/free-regular-svg-icons": "^5.13.1",
    "@fortawesome/free-solid-svg-icons": "^5.13.1",
    "@fortawesome/react-fontawesome": "^0.1.11",
    "@uppy/core": "^1.11.0",
    "@uppy/dashboard": "^1.10.0",
    "@uppy/react": "^1.8.0",
    "@uppy/webcam": "^1.6.7",
    "@uppy/xhr-upload": "^1.6.0",
    "announcekit-react": "^2.0.1",
    "axios": "^0.19.2",
    "axios-hooks": "^1.10.0",
    "bloomer": "^0.6.5",
    "bulma": "^0.9.0",
    "classnames": "^2.2.6",
    "dotenv": "^8.2.0",
    "dotenv-webpack": "^1.8.0",
    "express": "^4.17.1",
    "find-cache-dir": "^3.3.1",
    "js-cookie": "^2.2.1",
    "next": "^9.4.4",
    "next-i18next": "^4.4.2",
    "next-seo": "^4.6.0",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-alert": "^7.0.1",
    "react-alert-template-oldschool-dark": "^1.0.1",
    "react-collapsible": "^2.8.0",
    "react-datepicker": "^3.0.0",
    "react-dom": "^16.13.1",
    "react-hook-form": "^5.7.2",
    "react-markdown": "^4.3.1",
    "react-transition-group": "^4.4.1",
    "response-time": "^2.3.2",
    "sass": "^1.26.8",
    "use-ssr": "^1.0.23",
    "webpack": "^4.43.0",
    "yup": "^0.29.1"
  },
  "devDependencies": {
    "@fortawesome/fontawesome-free": "^5.13.0",
    "@types/express": "^4.17.6",
    "@types/node": "^14.0.13",
    "@types/react": "^16.9.36",
    "@typescript-eslint/eslint-plugin": "^2.34.0",
    "@typescript-eslint/parser": "^2.34.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.1.0",
    "eslint-config-airbnb-typescript": "^7.2.1",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.21.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-react": "^7.20.0",
    "eslint-plugin-react-hooks": "^3.0.0",
    "husky": "^4.2.5",
    "lint-staged": "^10.2.9",
    "nodemon": "^2.0.4",
    "prettier": "^2.0.5",
    "ts-node": "^8.10.2",
    "typescript": "^3.9.5"
  }
```
