### ISSUE TITLE
ProductJsonLd uses http://schema.org/Thing instead of http://schema.org/Brand for brand field

### ISSUE THREAD

**Issue by VChertukhin** [garmeeh/next-seo#384]
Many thanks for this great package!
So, here's fragment of json-ld created with this package

`brand": {
      "@type": "Thing",
      "name": "SUN"
    },`
 
nonetheless Brand type exists which is far more relevant, I consider. Would PR with this changes be a good thing?

**Comment by garmeeh** [comment]
Hey @VChertukhin a PR would be brilliant to update this thanks 😄

**Comment by elkinny** [comment]
Hi! @garmeeh  any updates regarding this one?

**Comment by chrillep** [comment]
@garmeeh ping! https://github.com/garmeeh/next-seo/pull/879

**Comment by garmeeh** [comment]
This has been updated to be Brand.
