### ISSUE TITLE
Dynamic opengraph tags

### ISSUE THREAD

**Issue by assemmohamedali** [garmeeh/next-seo#386]
https://stackoverflow.com/questions/55329917/next-js-how-to-set-head-tags-dynamically

The link above describes the same problem I currently have. I tried lots of ways but nothing worked facebook/twitter/linkedin seem always fetch the default settings even if it has been overridden in client-side. They have never been able to see the changes as it happened in a page's HTML. Any thoughts?

**Comment by assemmohamedali** [comment]
@garmeeh hopefully you have an answer

**Comment by garmeeh** [comment]
Hey @assemmohamedali would you have a link to a live example so I could have a look at debugging?

**Comment by garmeeh** [comment]
This could be related to #383 which one of the comments mentioned it was related to Apollo which you look to be using.

**Comment by assemmohamedali** [comment]
> This could be related to #383 which one of the comments mentioned it was related to Apollo which you look to be using.

I will test your example first in the issue you mentioned. I don't use apollo at all but I doubt it to be from nextjs version (9.3.4 my current version).  Could you please confirm that this version works with you as expected?

I will share with you an example after your confirmation. Thank you.

**Comment by assemmohamedali** [comment]
@garmeeh I can confirm now that the issue comes from using react context and wrap a component by a provider.

```
<>
        <DefaultSeo
        opengraph={{ props }}
        />
      <AppProviders>
        <Component {...pageProps}  />
      </AppProviders>
   </>
```
AppProviders

```
<AuthProvider>
         <SnackbarProvider>
                {children}
          </SnackbarProvider>
</AuthProvider>
```

When removing the provider from _app everything works well

**Comment by assemmohamedali** [comment]
The problem that I was returning null in AuthProvider until some action finish.
