### ISSUE TITLE
Can't override default image width/height

### ISSUE THREAD

**Issue by llamerr** [garmeeh/next-seo#389]
I have `<DefaultSeo` which defines `openGraph` images with single image and it's width/height set in `_app.tsx`, which I override at product page with `<NextSeo`. The problem is I don't know product images dimensions, so I only replacing url. But it seems when I provide either of these:

```
images: [{
            url: `${CDN}${product.coverUrl}`,
          }]

images: [{
            url: `${CDN}${product.coverUrl}`,
            width: 0,
            height: 0,
          }]

images: [{
            url: `${CDN}${product.coverUrl}`,
            width: null,
            height: null,
          }]
```

width and height are ignored and replaced by default width and height, which in my case no longer correct.

**Comment by llamerr** [comment]
Probably related to this issue https://github.com/garmeeh/next-seo/issues/386

**Comment by llamerr** [comment]
As I understand, for my case it probably can be fixed by something like this in `next-seo/src/meta/buildTags.tsx`
![image](https://user-images.githubusercontent.com/1281970/84955216-8869b700-b0ff-11ea-918d-5fb821870b9b.png)

**Comment by garmeeh** [comment]
Hey @llamerr I will need to investigate this one a bit more but I think if you do set the defaults you will need to override them fully. I think this was a limitation of Next itself. I thought this was documented but just realised it is not. I will update the docs and look into it.

**Comment by Bigdragon13th** [comment]
@garmeeh @llamerr I came across this issue today as I have the exact same issue. I have the website's logo with defined width & height as Default SEO and needs to override the image on individual product page with no pre determined width & height. Any progress or workaround on this?
