### ISSUE TITLE
code-splitting

### ISSUE THREAD

**Issue by timneutkens** [garmeeh/next-seo#4]
With the latest Next.js canary with webpack 4, it should be possible to publish `.mjs` files where `import` and `export` are not transpiled. This will allow webpack to code-split next-seo.

**Comment by JeromeFitz** [comment]
Would a direct file copy from `./src/**/.(js|jsx)` (no `test` files) to `./dist/**.mjs` in conjunction with existing `babel`  (maybe forcing `.jsx` to `.js` as well) and then altering the `package.json` suffice?:

> `"main": "./dist",`

This would allow `node` to make its `index` choice (default to `.mjs` if available) while keeping browsers to `.js`, I believe.

```bash
./dist/index.js
./dist/index.mjs
./dist/jsonld/article.js
./dist/jsonld/article.mjs
...
```

🐖️ If so, I'll have a branch to piggyback on #31  Would just need to spend a little time moving from `.sh` to using `taskr` and keeping things consistent. 👍 

:boom: If not, please let me know other thoughts on a path to address this issue.

**Comment by rchandu** [comment]
Hi, I want to help on this. Started using this library recently in our company. Let me know if this is a fine first issue, then I can volunteer on this.

**Comment by timneutkens** [comment]
Still relevant. Should probably leverage https://www.npmjs.com/package/microbundle
