### ISSUE TITLE
Request for RealEstateListing

### ISSUE THREAD

**Issue by erhankaradeniz** [garmeeh/next-seo#400]
Hello,

I’d like to request the addition of a JSON-LD property; RealEstateListing - https://schema.org/RealEstateListing.

I might try to add a PR myself, but I wanted to mention it here already and don’t know if it was on the roadmap.

**Comment by garmeeh** [comment]
Hey @erhankaradeniz I have done a bit of research around real estate listings in the past and I am not sure they would any real value to SEO. 

Maybe you have a use case I am missing?

I think some of the best things to add to a real estate site can be:

`Event` for open viewings
`LocalBusiness` for the estate agent

Also FAQ could be valuable, although these now have to visible to the user on the page.
