### ISSUE TITLE
localBusiness JSON-LD openingHours validFrom options

### ISSUE THREAD

**Issue by navandstokes** [garmeeh/next-seo#410]
https://github.com/garmeeh/next-seo/blob/e3fcbafa0578c1da6d99f06720f24818612c923e/src/jsonld/localBusiness.tsx#L64-L69

When wanting to exclude validFrom and validThrough, Google throws a parsing error because of the extra comma after dayOfWeek.

**Comment by garmeeh** [comment]
@navandstokes this has been fixed and released in `next-seo@4.7.2` any issue with it please let me know.
