### ISSUE TITLE
Add Carousel

### ISSUE THREAD

**Issue by pueyo5** [garmeeh/next-seo#415]
Hi,

First of all I want to thank all the contributors for maintaining this project.
I need to add a JSONLD Carousel to my site. Are you planing to implement it? 
https://developers.google.com/search/docs/data-types/carousel

Thanks

**Comment by statebait** [comment]
Has this been picked up? If not, I could pick it up. @garmeeh

**Comment by statebait** [comment]
@garmeeh ? I know you must be really busy, sorry for bothering.

**Comment by pueyo5** [comment]
Still pending

**Comment by rodbs** [comment]
I'm also interested in adding Carousel.
Thanks!

**Comment by garmeeh** [comment]
Hey all, I tried to have a go at this but I am really busy at the moment in work and did not get very far. 

If anyone would like to have a go at it, that would be great 🙏

**Comment by statebait** [comment]
Great, expect a PR this week!

**Comment by Namya0303** [comment]
hey @statebait is this topic up for hacktoberfest 2020?

**Comment by statebait** [comment]
@Namya0303 not sure. The PR for this issue is already up though - https://github.com/garmeeh/next-seo/pull/518

**Comment by statebait** [comment]
This is released in https://github.com/garmeeh/next-seo/releases/tag/v4.13.0. Can be closed now.

**Comment by garmeeh** [comment]
👍 Thanks. (GitHub should have closed this 🤔)
