### ISSUE TITLE
Is there a way to customize the order which metas are rendered?

### ISSUE THREAD

**Issue by igormartimiano** [garmeeh/next-seo#433]
Hey there, I got multiple tags in the <head> in my app and some of them are links, which are placed at `_document.js`. Those links are always rendered before all the metas included by `<DefaultSeo>` component.
Here is an example:
_document.js
![Screen Shot 2020-07-20 at 20 49 12](https://user-images.githubusercontent.com/22182599/87997077-78f8d780-caca-11ea-840e-124f3a4df78a.png)
_app.js
![Screen Shot 2020-07-20 at 20 49 59](https://user-images.githubusercontent.com/22182599/87997121-962da600-caca-11ea-80eb-d33c1edbb06c.png)
What I got:
<img width="842" alt="Screen Shot 2020-07-20 at 20 50 55" src="https://user-images.githubusercontent.com/22182599/87997170-b6f5fb80-caca-11ea-9f07-6dad6ea5b683.png">

I'd like to have the charset and title referenced earlier than manifest and icons. Didn't find anyway of doing that in the docs so just asking out of curiosity. 
Couldn't find any decent data that objectively specified an order for links and metas to be organized in a hurry but I feel like we should always have the assets that should be downloaded quickly and the most relevant information at the top, so that's why its bothering me I guess.
If you feel like this is viable I could work on a PR.

Thanks for the plugin :)

**Comment by jnv** [comment]
Hi, I also ran into this and in general this is not an issue with this plugin, but Next.js' behavior. Anything what goes into _document will be statically rendered and your custom Head declarations go above the defaults (i.e. charset and viewport). One possible workaround is to put all global meta tags into _app, but personally I don't like this either.

It's possible someone opened an issue or discussion about this in Next's repo, so check it out there.

**Comment by igormartimiano** [comment]
Thanks for answering, I'll check it out.
One thing that also might resolve the issue is creating a similar `additionalMetaTags` option for links, as they are very common to be present consistently between pages and also used for SEO. I could work on that.

Thoughts?
