### ISSUE TITLE
Next/head not found

### ISSUE THREAD

**Issue by rb162215** [garmeeh/next-seo#440]
After running  - `npm install --save next-seo`

in my package.json i have ` "next-seo": "^4.7.3",`

Then i run npm install and then 

On running npm start

Module not found: Can't resolve 'next/head' error received.

![Screen Shot 2020-07-27 at 5 32 42 PM](https://user-images.githubusercontent.com/46552717/88539932-bf50b800-d02f-11ea-97d8-51724aeaff36.jpg)

how to fix this? any help on this?

**Comment by jnv** [comment]
Hi, what's your version of `next`?
Or perhaps could you please show us what you have in `dependencies` and `devDependencies` inside your  `package.json`?

**Comment by rb162215** [comment]
i fixed the problem by running -

`npm install next`

documentation says to install `npm install --save next-seo` 

but need to install both next and next seo.

**Comment by jnv** [comment]
Well, I guess this is implied in the description:

> Next SEO is a plugin that makes managing your SEO easier in Next.js projects.

So... :shrug:
