### ISSUE TITLE
`image` attribute set to "undefined" if not provided to `LocalBusinessJsonLd`

### ISSUE THREAD

**Issue by cullylarson** [garmeeh/next-seo#455]
If you use `LocalBusinessJsonLd` and don't include an `images` prop, the schema will be generated with the `image` attribute set to the string `"undefined"`. Same thing happens if no `id` is provided. It seems like it should not be included in the schema output at all, if empty.

For example:

```js
<LocalBusinessJsonLd
  type="Store"
  id="http://davesdeptstore.example.com"
  name="Dave's Department Store"
  description="Dave's latest department store in San Jose, now open"
  url="http://www.example.com/store-locator/sl/San-Jose-Westgate-Store/1427"
  telephone="+14088717984"
  address={{
    streetAddress: '1600 Saratoga Ave',
    addressLocality: 'San Jose',
    addressRegion: 'CA',
    postalCode: '95129',
    addressCountry: 'US',
  }}
/>
```

Will generate:

```
<script type="application/ld+json">{
    "@context": "http://schema.org",
    "@type": "Store",
    "@id": "http://davesdeptstore.example.com",
    ...
    "image":"undefined",
    ...
  }</script>
```

**Comment by gtodd876** [comment]
I'd be happy to make a PR for and make `id` and `images` optional but I noticed in the docs that they are both listed as required properties for Local Business. Is that ok, to still make this change and then update docs to say those props are optional? I might need a little help on what course of action to take on the test for this as I don't have much experience yet with Cypress.

**Comment by garmeeh** [comment]
Hey @gtodd876 a PR would be brilliant. 

So I think for the docs:
- Mark `images` as recommended
- Leave `id` as required

For the code:

I think if the user does not add either prop, then `next-seo` should not output anything. 

I need to refactor the tests a little to allow for multiple scenario testing so in this case I think just manually testing for now will be ok.

**Comment by gtodd876** [comment]
This is still an issue after my PR?

**Comment by garmeeh** [comment]
😬 whoops @gtodd876 my bad. I just seen stale bot closed it and re-opened without checking. I must have forgot to close it after your pull request.

**Comment by gtodd876** [comment]
Oh no problem at all! Just wanted to make sure things were still good.
