### ISSUE TITLE
How can we get a full URL of current page? userRouter look like dont have it

### ISSUE THREAD

**Issue by IRediTOTO** [garmeeh/next-seo#464]
Hi, tag canonical need a full URL, what is the best way to take it? Thank you

**Comment by mshez** [comment]
There are couple of Stackoverflow questions yet unanswered.

https://stackoverflow.com/questions/63805183/nextjs-how-do-i-get-canonical-url-for-dynamic-pages
https://stackoverflow.com/questions/61574405/how-to-access-canonical-url-in-next-js-with-automatic-static-optimization-turned

only way left is is using router.asPath for dynamic routes. (This way it should be rendered on client side and wont be shown in page source i guess)

**Comment by IRediTOTO** [comment]
I must use .env file. I work, but if we want run site on 2 domains this will not ok :( vercel or heroku look like dont have system variable for this. Sad

**Comment by garmeeh** [comment]
Sorry this would be outside the scope of next-seo is very dependent on how you have deployed your site.
