### ISSUE TITLE
incorrect peer dependency 

### ISSUE THREAD

**Issue by decebal** [garmeeh/next-seo#47]
After upgrading to [V8](https://nextjs.org/blog/next-8/) I have this one pestering me about.

One suggestion might be to have a [renovate](https://renovatebot.com/) integration, I have no allegiance but I happen to  know it would solve this particular problem based on the PR seen on [next-nprogress](https://github.com/sergiodxa/next-nprogres)

**Comment by garmeeh** [comment]
Hey @decebal which warning are you getting? 

next@8.0.0 was added to the peer dependencies in `v1.10.1`

**Comment by decebal** [comment]
oh, yes, now it looks solved, maybe still consider renovate for auto resolution ?
