### ISSUE TITLE
Support multiple authors in JSON-LD

### ISSUE THREAD

**Issue by zommerberg** [garmeeh/next-seo#481]
Hello, is there a way to add a richer authors support for articles/blog posts that were written by multiple people?

Right now we only have `authorName={'John Cena'}` , which is just a String. And results to:
```
"author": {
   "@type": "Person",
   "name": "John Cena"
 },
```
Could we have that as a String[] so we can pass `authorName={['John Cena','Scott Steiner']}`

This way the JSON-LD would result to
```
  "author": [{
               "@type": "Person",
               "name": "John Cena"
          },
          {
               "@type": "Person",
               "name": "Scott Steiner"
          }],
```

**Comment by thelovekesh** [comment]
Yes, you can add two authors' names to search results JSON-LD.

For example:

<script type="application/ld+json">
{
     "@context": "http://schema.org",
     "@type": "WebPage",
     "mainEntity": {
          "@type": "Book",
          "author": [{
               "@type": "Person",
               "familyName": "van der Westhuizon",
               "givenName": "Jason",
               "name": "Jason van der Westhuizon"
          },
          {
               "@type": "Person",
               "familyName": "du Toit",
               "givenName": "Jene",
               "name": "Jene du Toit"
          },
         {
               "@type": "Person",
               "familyName": "September",
               "givenName": "Koos",
               "name": "Koos September"
          }],
          "bookFormat": "http://schema.org/Paperback",
          "datePublished": "2014-11",
          "inLanguage": "en",
          "isbn": "1234567890123",
          "name": "My Book Name",
          "numberOfPages": "381",
          "publisher": {
               "@type": "Organization",
               "name": "My Publisher"
          }
     }
}
</script>

**Comment by thelovekesh** [comment]
Yes, you can add two authors' names to search results JSON-LD.

For example:

```
<script type="application/ld+json">
{
     "@context": "http://schema.org",
     "@type": "WebPage",
     "mainEntity": {
          "@type": "Book",
          "author": {
               "@type": "Person",
               "familyName": "van der Westhuizon",
               "givenName": "Jason",
               "name": "Jason van der Westhuizon"
          },
          "author": {
               "@type": "Person",
               "familyName": "du Toit",
               "givenName": "Jene",
               "name": "Jene du Toit"
          },
          "author": {
               "@type": "Person",
               "familyName": "September",
               "givenName": "Koos",
               "name": "Koos September"
          },
          "bookFormat": "http://schema.org/Paperback",
          "datePublished": "2014-11",
          "inLanguage": "en",
          "isbn": "1234567890123",
          "name": "My Book Name",
          "numberOfPages": "381",
          "publisher": {
               "@type": "Organization",
               "name": "My Publisher"
          },
     }
}
</script>
```

**Comment by columbian-chris** [comment]
Shouldn't this actually be this, as an array of authors instead of duplicate entry keys for author?

```
<script type="application/ld+json">
{
     "@context": "http://schema.org",
     "@type": "WebPage",
     "mainEntity": {
          "@type": "Book",
          "author": [{
               "@type": "Person",
               "familyName": "van der Westhuizon",
               "givenName": "Jason",
               "name": "Jason van der Westhuizon"
          },
          "author": {
               "@type": "Person",
               "familyName": "du Toit",
               "givenName": "Jene",
               "name": "Jene du Toit"
          },
          "author": {
               "@type": "Person",
               "familyName": "September",
               "givenName": "Koos",
               "name": "Koos September"
          }],
          "bookFormat": "http://schema.org/Paperback",
          "datePublished": "2014-11",
          "inLanguage": "en",
          "isbn": "1234567890123",
          "name": "My Book Name",
          "numberOfPages": "381",
          "publisher": {
               "@type": "Organization",
               "name": "My Publisher"
          },
     }
}
</script>
```

**Comment by walkerab** [comment]
@columbian-chris I've checked using the schema.org validator and you should use `[]` and list them. If you use the same property multiple times it results in an error.
