### ISSUE TITLE
Open Graph locale:alternate not supported

### ISSUE THREAD

**Issue by ssohymind** [garmeeh/next-seo#491]
https://ogp.me/#optional
I tried to use `<meta property="og:locale:alternate" content="ko-KR">` something like this, to support multi-language for og metadata. However, I cannot find a way to put multiple `og:locale:alternate` property. Is there any way to use it?

**Comment by garmeeh** [comment]
Hey @ssohymind  [additionalMetaTags](https://github.com/garmeeh/next-seo#additional-meta-tags) should do the trick for you.

Please re-open this issue if not.

**Comment by osamasayed** [comment]
The problem with `additionalMetaTags` is that it doesn't allow duplicates and this is problematic since in my specific use-case, I need multiple `og:locale:alternate` tags. This an example of how the tags are supposed to look like:

```
<meta property="og:locale:alternate" content="fr_FR" />
<meta property="og:locale:alternate" content="es_ES" />
```

**Comment by vlapo** [comment]
We have exactly same problem. Is there any workaround?
