### ISSUE TITLE
Add extra json-ld fields outside of google's structured data spec

### ISSUE THREAD

**Issue by hyphmongo** [garmeeh/next-seo#50]
From schema.org there are a lot more properties supported in the json-ld spec, however most are ignored by Google when constructing structured search snippets.

I guess the intention of the library is specifically for SEO but it would be nice to add custom fields into the json-ld components for other use cases. In particular I have a case where I need to add json-ld for analytics with parse.ly https://www.parse.ly/help/integration/jsonld/ and some of their required fields are not included

**Comment by garmeeh** [comment]
Hey @hyphmongo, is it just the required fields that are listed on that page that are missing?

And then the types that Parse.ly support?

**Comment by hyphmongo** [comment]
Hi, sorry was't very clear before! Mainly I need support for the required fields from Parse.ly

But thinking about it some more, they aren't used for SEO purposes, so sort of feels like outside the scope of the module?
