### ISSUE TITLE
defaultTitle not used on initial page load

### ISSUE THREAD

**Issue by tacomanator** [garmeeh/next-seo#507]
Defining `titleTemplate` in a default config file works fine as I browse around the site. However, the first page load seems to ignore the template and display just the `title` as is. I create an example repository to demonstrate:

https://github.com/tacomanator/nextjs-nextseo-defaulttitle

Here is an animation of the problem. Notice how the title is missing "| MySite" initially, and on reload.

![ezgif-3-8373ea0bf4ec](https://user-images.githubusercontent.com/63794/95141500-58c4e480-07ac-11eb-9c46-c51acb69f217.gif)

Note: I may be doing things a little differently. `titleTemplate` is defined, as per the website example `titleTemplate: "%s | MySite"`, in a config file used by `<DefaultSeo />`. However, rather than using `<NextSeo />` directly on each page, I use it on a shared `Layout` component, which receives and forward a `title` prop.

**Comment by modbender** [comment]
I had this problem before but I forgot how I solved it, I'm not sure but try putting `DefaultSeo` before `Component` in `_app.js`?

**Comment by tacomanator** [comment]
@modbender  that did the trick thank you! Not sure if this should be considered working as is and maybe include a note in the docs about the order of 1DefaultSeo` and 1Component`, or as a bug?

**Comment by garmeeh** [comment]
@tacomanator a pull request to add a note to the docs about this would be awesome 😅 

`DefaultSeo` must come before `Component`due to the behavior of next internals.

**Comment by modbender** [comment]
I think it's about time this is closed.
