### ISSUE TITLE
Potential Bug in ProductJsonLd

### ISSUE THREAD

**Issue by joeyorlando** [garmeeh/next-seo#514]
Hi there,

Amazing library. I've been using it in production for a recent ecom site I deployed. I'm using the `ProductJsonLd` component on my `/product/[slug].tsx` page as such:
```jsx
<ProductJsonLd
    sku={id.toString()}
    productName={name}
    images={[featuredImageUrl]}
    description={description}
    brand={brand ? brand.name : ''}
    offers={[
        {
        price: productPriceString,
        priceCurrency: defaultCurrencyCode,
        itemCondition: 'http://schema.org/NewCondition',
        availability: backordered ? 'https://schema.org/OutOfStock' : 'http://schema.org/InStock',
        url: productUrl,
        seller: {
            name: siteName,
        },
        },
    ]}
    mpn={sku}
/>
```

Recently I started noticing some errors being reported in Sentry:
```
Unexpected token T in JSON at position 732
```
Digging a bit deeper locally I see this stack trace:
```
sos-web-app      | SyntaxError: Unexpected token T in JSON at position 733
sos-web-app      |     at JSON.parse (<anonymous>)
sos-web-app      |     at minifyJsonLd (/app/node_modules/next-seo/lib/next-seo.js:623:30)
sos-web-app      |     at ProductJsonLd (/app/node_modules/next-seo/lib/next-seo.js:869:37)
sos-web-app      |     at processChild (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3043:14)
sos-web-app      |     at resolve (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
sos-web-app      |     at ReactDOMServerRenderer.render (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
sos-web-app      |     at ReactDOMServerRenderer.read (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
sos-web-app      |     at renderToString (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
sos-web-app      |     at Object.renderPage (/app/node_modules/next/dist/next-server/server/render.js:50:851)
sos-web-app      |     at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:141:19)
```

I believe I've narrowed down the cause to when the `productName` prop contains a double quote inside of the string. No quotes, or single quote works fine, as soon as I have my product `14x1.5 Spike Lug Nuts 4.5" Tall - Powder Coated`, boom error.

It seems to be coming from [this line](https://github.com/garmeeh/next-seo/blob/master/src/utils/minifyJsonLd.ts#L2). I can try to submit a PR in the coming days if you guys are open to PR submissions.

**Comment by joeyorlando** [comment]
hmm I thought it would be this simple:
```diff
const minifyJsonLd = (jsonld: string) =>
-  JSON.stringify(JSON.parse(jsonld.replace(/[\u0000-\u0019]/g, '')));
+  JSON.stringify(JSON.parse(jsonld.replace(/[\u0000-\u0019]/g, '').replace('"', '\\"')));
```
but that still doesn't work because it also replaces the double quotes that are needed to delimit the strings in the JSON. I think we'd have to escape double quotes, for each piece of data, before calling `minifyJsonLd` (https://stackoverflow.com/a/49428083/3902555)

**Comment by garmeeh** [comment]
@joeyorlando thanks for reporting. 🤔 I am thinking I might temporarily remove the minify method as it may causing issues for people in production without realizing.

**Comment by garmeeh** [comment]
I temporarily removed this functionality in v4.14.0

I opted for minor release just in case anyone had workarounds in that removing this feature breaks.
