### ISSUE TITLE
Move to Typescript

### ISSUE THREAD

**Issue by garmeeh** [garmeeh/next-seo#52]
Currently in the process of moving to Typescript.

**Comment by garmeeh** [comment]
Hey @erickeno, didn't want to highjack that other issue. Some help would be great. What I will do is get what I have into a bit better shape and once I have that up will give you ping here.

**Comment by erickeno** [comment]
okay sounds good

**Comment by ctxquentin** [comment]
hey @garmeeh , i did not know when you planned to move the master to typescript, so i made the job posting json ld in plain javascript, but i can migrate it to typescript if you want :)
