### ISSUE TITLE
next-seo breaks on Next v9.5.4

### ISSUE THREAD

**Issue by schlosser** [garmeeh/next-seo#523]
Due to https://github.com/vercel/next.js/issues/17721, using this library in the Next.js `<Head>` results in `Failed to execute 'createElement' on 'Document'`. 

Is there any workaround for this issue? Or is next-seo not compatible with that version of Next.js?

**Comment by garmeeh** [comment]
Hey @schlosser I haven't had a chance to look into this issue fully just yet, but `next-seo` [returns an array](https://github.com/garmeeh/next-seo/blob/master/src/meta/nextSEO.tsx#L25) as recommended.

My integration tests passed for `v9.5.4` so I managed to give it a very quick test manually and it seems ok. But as I said it was a very quick test. Could you provide me with a simple reproduction to test?

**Comment by schlosser** [comment]
Yeah – looking at the thread it seems like this is on their end. Feel free to close this, or keep it open for folks to find until there is a fix patched in. Thanks!

**Comment by schlosser** [comment]
Looking at my implementation, I think what happened was I was using `<NextSEO>` _inside of_ `<Head>`, which isn't correct.

**Comment by garmeeh** [comment]
Thanks for following up @schlosser 👌 I will leave this open until this has been patched. I also might add a warning in the docs about not nesting NextSeo within head maybe 🤔

**Comment by schlosser** [comment]
That would be great! I definitely glossed over that :)

**Comment by mvgadagi** [comment]
I have tried this on next v10.0.0 and I have having the same issue, is there any work around you suggest for the moment ?

Regards,
Mahesh

**Comment by garmeeh** [comment]
Spent the last while testing this issue and if `next-seo` is not nested within `<Head>` I get no issues with the latest versions.

I have created a small demo app just to verify, please let me know if I have mistaken the issue. 

https://github.com/garmeeh/next-seo-demo
