### ISSUE TITLE
JSON-LD VideoObject missing?

### ISSUE THREAD

**Issue by alexpolicastro** [garmeeh/next-seo#533]
I don' see an option for VideoObject JSON-LD. Is this just named differently or not yet added?
https://developers.google.com/search/docs/data-types/video

Thanks, next-seo is really helpful!

**Comment by johndavidpena** [comment]
Same question for me concerning the VideoObject.

Thanks guys, this is super helpful and much appreciated!

**Comment by garmeeh** [comment]
Will be publishing new version with this this afternoon thanks to @valse
