### ISSUE TITLE
[Bug] key not passed to child element

### ISSUE THREAD

**Issue by modbender** [garmeeh/next-seo#535]
Recently I started seeing this error:
![Error](https://user-images.githubusercontent.com/25717245/96332139-1f2f8b80-1080-11eb-994d-8f0cf518562c.png)

It turned out to be due to `additionalMetaTags`:

```js
additionalMetaTags: [
    {
      name: "author",
      content: 'SiteName',
    },
    {
      httpEquiv: "X-UA-Compatible",
      content: "IE=edge; chrome=1",
    },
  ],
```

The error is especially showing if there are `additionalMetaTags` that has no `name` and `property`.
https://github.com/garmeeh/next-seo/blob/67745207140d2fe00b5c27f721c769045436cec2/src/meta/buildTags.tsx#L619

How about changing
```js
    config.additionalMetaTags.forEach(tag => {
      tagsToRender.push(
        <meta key={tag.name ? tag.name : tag.property} {...tag} />,
      );
    });
```
to
```js
    config.additionalMetaTags.forEach(tag => {
      tagsToRender.push(
        <meta key={Object.values(tag)[0]} {...tag} />,
      );
    });
```
**OR**
```js
    config.additionalMetaTags.forEach(tag => {
      tagsToRender.push(
        <meta key={tag.name || tag.property || tag.httpEquiv} {...tag} />,
      );
    });
```

@garmeeh

**Comment by garmeeh** [comment]
Hey @modbender ah sorry about that. I like the structure of your first solution, but maybe tweaking it to use `Object.keys` for better browser support 🤔

**Comment by modbender** [comment]
I don't understand the difference, value or keys either should have equal support right? Either way I would recommend to go with
```js
config.additionalMetaTags.forEach(tag => {
      tagsToRender.push(
        <meta key={tag.name || tag.property || tag.httpEquiv} {...tag} />,
      );
    });
```
for now, I check online and as I see it, meta tag can have only 3 types `name`, `property` or `httpEquiv` so it should cover everything needed and there's no issue with any compatibility or anything.
