### ISSUE TITLE
How to pass data into the openGraph object? 

### ISSUE THREAD

**Issue by Zrce** [garmeeh/next-seo#536]
I'm stuck with the documentation. How to pass data into the openGraph object. I have string with the title in pageContext.title. I'm able to get in into title but the openGraph title I don't know how to set? 

```
const SEO = ({ pageContext }) => {

  return (
      <GatsbySeo
        title={pageContext.title}
..
        openGraph={{
...
          title: {pageContext.title},
```

**Comment by garmeeh** [comment]
Hey @Zrce, looks like you might be using [GatsbySeo](https://www.npmjs.com/package/gatsby-plugin-next-seo) rather than `next-seo`?

**Comment by Zrce** [comment]
sorry yes
