### ISSUE TITLE
Reviews for Courses 

### ISSUE THREAD

**Issue by qionghuang6** [garmeeh/next-seo#539]
Hi there, before I start, I want to say that this library is really great and has been quite helpful to me. 

Some features that I noticed could be useful additions to the JSON-LD functionality are [Sitelinks Search Boxes](https://developers.google.com/search/docs/data-types/sitelinks-searchbox) and more support for [Review Snippets and Aggregate ratings](https://developers.google.com/search/docs/data-types/review-snippet). This review information could be added to the Course Type and some other types not yet in this library. Since Google also supports reviews and aggregate ratings for other Schema types like [Organizations](https://schema.org/Organization), this could be a helpful feature for sites that want to include reviews/testimonials on their homepage. 

I may be able to help with a PR.

**Comment by garmeeh** [comment]
Hey @qionghuang6 these would be great additions to next-seo if you would like to put a PR forward.

**Comment by omar-dulaimi** [comment]
Hello @qionghuang6 
unless you have already started, can I work on it instead?
it's okay if you want to work on it yourself, there are plenty of other schemas to implement

**Comment by qionghuang6** [comment]
Hey @omar-dulaimi. Are you talking about the sitelinks search box? I haven't done much on it but it seems pretty simple. You can do it.

**Comment by garmeeh** [comment]
SiteLinks has been added so updated title to reflect what is still outstanding.

**Comment by garmeeh** [comment]
Duplicate #968
