### ISSUE TITLE
Add support for remote jobs in JobPostingJsonLD

### ISSUE THREAD

**Issue by mahaveer0496** [garmeeh/next-seo#548]
Right now `jobLocation` is mandatory but for remote jobs its not and `jobLocationType` is needed.

https://developers.google.com/search/docs/data-types/job-posting#structured-data-type-definitions

![image](https://user-images.githubusercontent.com/23198481/97087175-a911c280-1645-11eb-868d-15c32667c9bd.png)

**Comment by garmeeh** [comment]
Available in v4.16.0
