### ISSUE TITLE
issue with localBusiness JSON-LD

### ISSUE THREAD

**Issue by erickeno** [garmeeh/next-seo#56]
https://github.com/garmeeh/next-seo/blob/1c9ed66d900a356d1c72444875cc32ec4dff49a9/src/jsonld/localBusiness.jsx#L8

While in the process of converting `localBusiness` to typescript, I realized that this check is not efficient because both string and array have a length property. If someone passes a string it will throw an error, even though string value is considered a valid value as well.

Maybe check if it's a string or an array
```javascript
Array.isArray(images) ? `"image": [${images.map(image => `"${image}"`)}],` : images;
```

**Comment by garmeeh** [comment]
Good spot. Yeah I think lets check if it's an Array as above.
