### ISSUE TITLE
InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('function SocialProfileJsonLd(_ref) 

### ISSUE THREAD

**Issue by mvgadagi** [garmeeh/next-seo#563]
Hello,

I have upgraded my project to next to v10.0.0 and react to 17.0.1 and I started facing this run time error, can you please take a look

packages used
    "next": "^10.0.0",
    "next": "^10.0.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"

And I am seeing the error as below

Unhandled Runtime Error
InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('function SocialProfileJsonLd(_ref) {
  var keyOverride = _ref.keyOverride,
      type = _ref.type,
      name = _ref.name,
      url = _ref.url,
      _ref$sameAs = _ref.sameAs,
      sameAs = _ref$sameAs === void 0 ? [] : _ref$sameAs;
  var jslonld = "{\n    \"@context\": \"http://schema.org\",\n    \"@type\": \"" + type + "\",\n    \"name\": \"" + name + "\",\n    \"url\": \"" + url + "\",\n    \"sameAs\": [\n      " + sameAs.map(function (socialUrl) {
    return "\"" + socialUrl + "\"";
  }) + "\n     ]\n  }";
  return react__WEBPACK_IMPORTED_MODULE_1___default.a.createElement(next_head__WEBPACK_IMPORTED_MODULE_0___default.a, null, react__WEBPACK_IMPORTED_MODULE_1___default.a.createElement("script", {
    type: "application/ld+json",
    dangerouslySetInnerHTML: markup(jslonld),
    key: "jsonld-social" + (keyOverride ? "-" + keyOverride : '')
  }));
}') is not a valid name.

Please let me know, if you need further details

Thanks and Regards,
Mahesh

**Comment by garmeeh** [comment]
Hey @mvgadagi this is related to #523 and also this upstream issue: https://github.com/vercel/next.js/issues/17721

Can you post how you are using Next Seo? If it is contained within `<Head>` it will cause an error.

**Comment by garmeeh** [comment]
Spent the last while testing this issue and if `next-seo` is not nested within `<Head>` I get no issues with the latest versions.

I have created a small demo app just to verify, please let me know if I have mistaken the issue. 

https://github.com/garmeeh/next-seo-demo

**Comment by mvgadagi** [comment]
Hi @garmeeh sorry  I couldn't respond you soon, I have verified my code and I found that I had used SocialProfileJsonLd inside HEAD, thanks for the demo repo I will follow that and update my project.

Thanks for your good work !!

Regards,
Mahesh
