### ISSUE TITLE
Twitter summary_large_image not working

### ISSUE THREAD

**Issue by geekysrm** [garmeeh/next-seo#569]
Code: https://github.com/geekysrm/soumya.dev/blob/master/src/layouts/index.js#L81
Site: https://soumya.dev/what-is-tailwind-css

As you can see below, it is not displaying the full image though I have used 'summary_large_image"
![image](https://user-images.githubusercontent.com/10224804/98098107-ea129e00-1eb3-11eb-8a14-e67f9b9f532c.png)

**Comment by geekysrm** [comment]
It was an error from my side!

Closing this.

**Comment by jacobedawson** [comment]
@geekysrm can you please post the configuration that is working for you now, I can't seem to get this working properly

**Comment by geekysrm** [comment]
Hey @jacobedawson, just check this link:
https://github.com/geekysrm/soumya.dev/blob/master/src/layouts/index.js#L81
