### ISSUE TITLE
trouble implementing seo correctly in next.js app using next-seo

### ISSUE THREAD

**Issue by jermsam** [garmeeh/next-seo#58]
hi guys...
I am using next-seo to implement seo in my next.js app. This app uses feather.js in the backend api ...

I have implemented a default seo config in _app.js file as per the instruction ... I need to override this in the users' dashboard with user info ... but this info comes from the feathers.js backend api .... so it's fetched asynchronously ...
I fetched the info in ComponentDidMount ...

What baffles me is that much as the overrides are reflected when I go to the users dashboard, when I view page source on the page in the dashboard, the override is not reflected ... the metatags and title in that html remain the same as they were in pages like the landing page which never overrode the seo...

Kindly advise what I should do to fix this. Thanks ....

Here is the gist with my code snippets .....
https://gist.github.com/jermsam/673380b2cf8451d88362c9c1c473e3a1

Thanks so much.

**Comment by econdie** [comment]
hi, in your _app.js you have: 

`import SEO from './next-seo.config';`

that would imply you have next-seo.config saved within your pages folder (which is where _app.js lives) which im guessing would not work. do you actually have it saved in your pages folder there or do you just have a syntax error? it should be like this if the config exists in your root presumably (notice the extra leading period):

`import SEO from '../next-seo.config';`

**Comment by econdie** [comment]
also I may be wrong on this, but i dont think your structuring of using state with componentDidMount to provide SEO attribute values is good practice. in Next.js you should be using getInitialProps to perform API/data feteches and return them as props, as this will ensure SEO data is fetched and available before the page is rendered. (this is definitely true for any data you consider 'required' to actually render your page properly). if you were to for example share a link to your page on social media, the server side fetch to grab meta data would probably not be as you expect and not include that required meta data. (as in your setup thats happening after the component mounts in browser)

 In your setup, you will have the initial page load with your default data, and then componentdidmount would do an async call in the background after component has already mounted, and update/re-render with the proper data. I think this would cause problems with server side loads / crawlers that are looking at your SEO data.

**Comment by jermsam** [comment]
@econdie Thanks so much for the advice and insights, I think they are great and will help. I am going to consider doing my API/data fetches in `getInitialProps` just as you recommend and see how that works. Will give feedback here.

As for the location of my `next-seo.config.js` file, yes it's in the `/pages`
directory ... not in the route as advised in the doc.

**Comment by econdie** [comment]
I dont think you should have that config in your pages directory, that folder is specifically reserved by Next.js for actual pages (and _document, _app, and _error iirc). I'd suggest moving it somewhere else!

**Comment by jermsam** [comment]
Alright Thanks so much for this clarification. Let me start with putting it in the root where it belongs.

**Comment by jermsam** [comment]
@econdie actually this was helpful. The only thing still baffling me is how to deal with realtime events I had in my componentDidMount ... Can you advise how you would go about that please?

**Comment by jermsam** [comment]
I am going to close this issue since it's solved.
