### ISSUE TITLE
Defaults not being overridden on initial page rendering

### ISSUE THREAD

**Issue by grazianodev** [garmeeh/next-seo#61]
Hi, 

I'm using your library in my project and it seems that the default values I have set up only get overridden when I navigate from one page to another; when a certain page is the first page I visit, it uses the default values and ignores its own config object. 

Here's my page (this is the actual page code—I've stripped it down to just Next Seo for testing purposes): 

```
import NextSeo from 'next-seo'

export default class Post extends React.Component {
	render() {
		return(
			<div>
				<p>Booh!</p>
			        <NextSeo config={{
					description: "This is my description",
					title: "This is my title"
			        }} />
			</div>
		)
	}		
}
```

If it's the first page I visit, I don't get "This is my title" and "This is my description" in the meta tags (I get default values instead); if for example I visit the home page first and then navigate to this page, then I do see "This is my title" and "This is my description" in the meta tags. 

Here is my config file where I set up the default values: 

```
export const pageSEO = ( page, noindex ) => {
	return {
		title: stripHTML( page.title ),
		description: stripHTML( page.description ), 
		noindex: noindex, 
		openGraph: {		
			description: stripHTML( page.description ), 
			title: stripHTML( page.title ),
			images: [
				{
					url: page.image
				}
			]		
		}
	}
}
```

Then I add the defaults to all pages in _app.js

```
import NextSeo from 'next-seo'
import { pageSEO } from '../config/SEO'

render() {
        const { Component, pageProps, myPage } = this.props
        return(
            <Container>
                <Provider store={ this.appData }>
                    <AppInterface.Provider value={{ state: this.state, actions: this.actions }}>
                        <Component { ...pageProps } />
                        <NextSeo config={ pageSEO( myPage ) } />
                    </AppInterface.Provider>
                </Provider>
            </Container>                          
        )
}
```

**Comment by garmeeh** [comment]
From looking at the code provided it should be working. Could you recreate a minimal reproduction of it on CodeSandbox. This [link](https://codesandbox.io/s/github/zeit/next.js/tree/canary/examples/with-next-seo) will bootstrap a basic project with `next-seo`.

**Comment by grazianodev** [comment]
I've found the problem, all I had to do was declare the NextSeo config before including the Component. 

I had: 

```
<Component { ...pageProps } />
<NextSeo config={ pageSEO( myPage ) } />
```

Reordering to:

```
<NextSeo config={ pageSEO( myPage ) } />
<Component { ...pageProps } />
```

fixes the issue. Does where you position NextSeo matter? I guess it makes sense if it does since it deals with the <head> tag, but I didn't really think about it...

**Comment by garmeeh** [comment]
I wouldn't have thought it should matter. It uses `next/head` internally. I will do some tests around it to see.
