### ISSUE TITLE
Readme: Version numbers 6.0.0 - 7.0.0-canary.0 unclear

### ISSUE THREAD

**Issue by simonschllng** [garmeeh/next-seo#611]
The README says:

> For versions 6.0.0 - 7.0.0-canary.0 you just need to supply a single item array

The current version is `4.17.0`

Which version numbers is the sentence referring to?

**Comment by yedhink** [comment]
I think the author meant the canary version of `nextjs`. Not confirmed though.

Quoting a sentence from Readme:

> // Multiple Open Graph tags is only available in version `7.0.2-canary.35`+ of next
          tags: ['Tag A', 'Tag B', 'Tag C'],
