### ISSUE TITLE
Feature Request: Make datePublished/dateModified optional values in Blog and Article schemas

### ISSUE THREAD

**Issue by appdevland** [garmeeh/next-seo#612]
These values are not required for blog/article schemas as far as i know so can we make them optional?

I took a look at the code base. It's extremely simple to do and it's a feature I would love to have because some of the blog posts on our website don't have dates (evergreen content).

Cheers!

**Comment by garmeeh** [comment]
`datePublished` is required by Google. `dateModified` is now optional.
