### ISSUE TITLE
Reviews for Software App [Feature Request]

### ISSUE THREAD

**Issue by CedYF** [garmeeh/next-seo#617]
It would be great if we could add software app as a JSON category for Next SEO.

There's more information here: https://developers.google.com/search/docs/data-types/software-app

I could try adding it but I'm not sure where to begin.

**Comment by garmeeh** [comment]
If you are interested in working on this @CedYF and would like some direction let me know and I can add a comment and try give you help on where to start 😅

**Comment by CedYF** [comment]
Yea that would be great

**Comment by garmeeh** [comment]
Ok great. I will give you a brief overview and if you get stuck jump back on here and I can try give more direction. 

1. First step would be to get the project running locally. You can find a guide on how to that [here](https://github.com/garmeeh/next-seo/blob/master/CONTRIBUTING.md) (I should probably update that to say fork the repo and clone from your fork 😅)
2. Next you want to create a file called `softwareApp.tsx` in [this directory](https://github.com/garmeeh/next-seo/tree/master/src/jsonld) This will be where you will code the actual component that you will include onto the page.
3. To start have a look at some of the files in that directory and copy one of those as a starting point. 
4. Once you are happy with what you have and ready to test you need to add export it from [here](https://github.com/garmeeh/next-seo/blob/master/src/index.tsx)
5. Next, to test you will want to include this component in the local end to end app this project uses. You import and add to the page in this [file](https://github.com/garmeeh/next-seo/blob/master/e2e/pages/jsonld.tsx)
6. Now you will want to build `next-seo` by running `yarn build`. This builds all of the changes in the `src` directory yo have made. Then following that run `yarn e2e:dev` this will start the next application where you can navigate to json page and verify in the page source your schema is present. It would be good at this point to copy it from the page source and [validate it](https://search.google.com/test/rich-results?utm_campaign=devsite&utm_medium=jsonld&utm_source=software-app&id=pzsNgAdWPa_gXbIOIv38FQ) It is import to validate it with and without optional as a trailing comma will cause an invalid JSON output
7. Once you are happy it is working next up is to document it by adding it to the README.md
8. Finally then you will need to write a test in this [file](https://github.com/garmeeh/next-seo/blob/master/cypress/e2e/jsonld.spec.js) If you have a look back through closed PR's you will see some examples, but let me know if you get stuck. 

Hopefully that helps.

**Comment by garmeeh** [comment]
Hey @CedYF, just want to check in to see have you started working on this feature? A pull request has been opened with the feature but as you had already stated your intention of working on it I think its only fair to allow you to complete it if you have started on it/would like to. 

Would love to get your thoughts on it.
