### ISSUE TITLE
TypeError: Cannot read property 'tagName' of null

### ISSUE THREAD

**Issue by alexandrzavalii** [garmeeh/next-seo#620]
not sure why it is happening
```
      <NextSeo
        canonical={configs.currentUrl}
        description={configs.description}
        facebook={{
          appId: configs.fbAppId,
        }}
        openGraph={{
          url: configs.currentUrl,
          title: configs.title,
          description: configs.description,
          type: 'website',
          site_name: configs.siteName,
          locale: 'en_IE',
          images: [
            {
              url: 'https://www.example.ie/og-image.jpg',
              width: 800,
              height: 600,
              alt: 'Og Image Alt',
            },
            {
              url: 'https://www.example.ie/og-image-2.jpg',
              width: 800,
              height: 600,
              alt: 'Og Image Alt 2',
            },
          ],
        }}
        title={configs.title}
        twitter={{
          handle: configs.twitterHandler,
          site: configs.twitterHandler,
          cardType: 'summary_large_image',
        }}
      />
    ```

**Comment by garmeeh** [comment]
What version of Next and next-seo are you using?

**Comment by rodzy** [comment]
@alexandrzavalii Do you have a repo so I can try and replicate this behavior?

**Comment by skotchpine** [comment]
Same issue here

**Comment by ThomasGormley** [comment]
Hi, I was experiencing the same issue as above, so if you were interested in this

I managed to reproduce when either `<NextSeo />` or `<DefaultSeo  />` component was within a Next `<Head>` component.
I'm on version ^4.24.0 next-seo, and latest Next.

**Comment by pramam** [comment]
I am getting this error too when <NextSeo/> is within a Next <Head> component. 

```
<Head>
<NextSeo
   title="my title"
   description="my description"
/>
</Head>
```

next-seo ^4.24.0, next ^10.2.0

**Comment by jsjoeio** [comment]
I ran into this error as well. I fixed it by moving `<NextSeo />` outside of `<Head />`

**Comment by nguyentuan1696** [comment]
> I am getting this error too when `<NextSeo/>` is within a Next `<Head>` component.
> 
> ```
> import Head from 'next/head'
> <Head>
> <NextSeo
>    title="my title"
>    description="my description"
> />
> </Head>
> ```
> 
> next-seo ^4.24.0, next ^10.2.0
> 
> Could this be the issue, from here: https://nextjs.org/docs/api-reference/next/head "title, meta or any other elements (e.g. script) need to be contained as direct children of the Head element, or wrapped into maximum one level of <React.Fragment> or arrays—otherwise the tags won't be correctly picked up on client-side navigations."

This solution solved my case!
