### ISSUE TITLE
next-seo & serverless

### ISSUE THREAD

**Issue by romainquellec** [garmeeh/next-seo#63]
I'm using next seo with target: serverless
On dev, I can see this working correctly, but on serverless, I've got nothing related to seo (title, description, ect).

I have no demo repo, but you can check : https://github.com/CuistotduCoin/front

Thanks.

**Comment by garmeeh** [comment]
I haven't tested with serverless target just yet. I will try out this week and get back to you.

**Comment by romainquellec** [comment]
Apparently, its not related to serverless : https://codesandbox.io/s/l9ojn43379
(This is basically what I do in my project)

I have no idea why its not working in prod.

**Comment by romainquellec** [comment]
It seems fix in the last version.
