### ISSUE TITLE
[languageAlternates] hreflang rendered with wrong case (hrefLang)

### ISSUE THREAD

**Issue by romaincointepas** [garmeeh/next-seo#656]
On `4.20.0`:
```html
<link rel="alternate" hrefLang="fr" href="https://example.com/fr" />
```

Should be:
```html
<link rel="alternate" hreflang="fr" href="https://example.com/fr" />
```

**Comment by garmeeh** [comment]
Hey @romaincointepas can you provide an recreation of this? Just checking here and for me it renders correctly.

**Comment by mglavall** [comment]
I can confirm this is still happening

**Comment by AntoineKM** [comment]
> I can confirm this is still happening

i confirm that also
