### ISSUE TITLE
Can't implement NextSeo due to other library

### ISSUE THREAD

**Issue by webdevsyd** [garmeeh/next-seo#66]
I'm encountering this issue on my nextjs app `Unhandled Rejection (Invariant Violation): React.Children.only expected to receive a single React element child.` , looks like `<IntlProvider>` only accepts a single child component. If that's the case where can I put the `<NextSeo />` component.

<img width="899" alt="Screen Shot 2019-04-07 at 10 42 57 AM" src="https://user-images.githubusercontent.com/15810023/55677845-05a57380-5922-11e9-9ab0-bc6f7e449d71.png">

Here's the content of my `_app.js`

<img width="691" alt="Screen Shot 2019-04-07 at 10 46 24 AM" src="https://user-images.githubusercontent.com/15810023/55677863-6cc32800-5922-11e9-882c-5139e19a2c72.png">

**Comment by garmeeh** [comment]
Does `<NextSeo config={SEO} />` need to be within `<IntlProvider>`? If you move up one to be just within `<Provider>` it should still work as expected.

**Comment by garmeeh** [comment]
Please let me know if you are still having issues.
