### ISSUE TITLE
[Bug] additionalMetaTags does not have a unique key prop

### ISSUE THREAD

**Issue by MrNossiom** [garmeeh/next-seo#666]
Hello, I'm using next-seo for a week now and this package is so great, but I found a problem with additional Meta Tags:
They don't always have a key prop that is required by React this result on a useless log and an error in the browser console.

I found the piece of code that do the job, I think that a random key could be provided:
```diff
  if (config.additionalMetaTags && config.additionalMetaTags.length > 0) {
    config.additionalMetaTags.forEach(tag => {
      tagsToRender.push(
-        <meta key={tag.name || tag.property || tag.httpEquiv} {...tag} />,
+        <meta key={tag.name || tag.property || tag.httpEquiv || uuid()} {...tag} />,
      );
    });
  }
```

I can contribute, but I think that adding a package only for that don't worth it...
If any of you, guys, have ideas, please share it with me.

MrNossiom

**Comment by rodzy** [comment]
Hi @MrNossiom thanks for pointing this out

What kind of log or error are you getting? Can you please provide an screenshot of it that would be useful

Based on your insight I think something like this could make the job instead of importing the `uuid` library: 

```js
const makeRandomId = (length: number) => {
  let result = '';
  const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
  const charactersLength = characters.length;
  for (let i = 0; i < length; i++) {
    result += characters.charAt(Math.floor(Math.random() * charactersLength));
  }
  return result;
};

export default makeRandomId;
```

I hope to hear back from you, any more questions I'm here to help 👍

**Comment by MrNossiom** [comment]
Hello @rodzy,
Thanks for your fast answer...

I get the basic error for list keys:
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `_default`. See https://reactjs.org/link/warning-keys for more information.
...
```

I found a UUID generator on a random website, so I made a pull request: #672

**Comment by MrNossiom** [comment]
I found out that I was using additionalMetaTags for what was supposed to be links... 👎🏻
