### ISSUE TITLE
URL encoding breaks AWIN urls 

### ISSUE THREAD

**Issue by mousedown** [garmeeh/next-seo#678]
https://images2.productserve.com/?w=700&h=700&bg=white&trim=5&t=letterbox&url=ssl%3Amedia.static-allbeauty.com%2Fimage%2Fproduct%2F1%2F200%2F1181487-label-m-electrical-tourmaline-dryer-black.jpg&feedId=37617&k=ca32b5eb1817e7f00a6ba99285c345112b8e9450

is encoded to 

https://images2.productserve.com/?w=700&amp;h=700&amp;bg=white&amp;trim=5&amp;t=letterbox&amp;url=ssl%3Amedia.static-allbeauty.com%2Fimage%2Fproduct%2F1%2F200%2F1181487-label-m-electrical-tourmaline-dryer-black.jpg&amp;feedId=37617&amp;k=ca32b5eb1817e7f00a6ba99285c345112b8e9450

..with the only difference being & vs &amp; I have tried 

```
 images: [
            {
              url: `${imageURL).replace(/&amp;/g, '&')}`,
              alt: `${imageALT}`,
            },
          ],

```

but the outputted meta still contains &amp; instead of just &

**Comment by garmeeh** [comment]
Hey @mousedown I think this is an upstream issue with React unfortunately. See https://github.com/facebook/react/issues/13838
