### ISSUE TITLE
Dynamic og:url

### ISSUE THREAD

**Issue by kodermax** [garmeeh/next-seo#68]
It would be convenient to have a function that defines og:url as the current page

**Comment by charles4221** [comment]
@kodermax could you not just use `window.location.href`? Or if you can't use window due to SSR you could wrap your SEO component in the `withRouter()` HOC and use the current `router.asPath` or similar?

**Comment by garmeeh** [comment]
I think this can be achieved via application code and probably would be unneeded within `next-seo` itself. Maybe I am miss-understanding the question. Closing for now.
