### ISSUE TITLE
Change viewport

### ISSUE THREAD

**Issue by matheusqro** [garmeeh/next-seo#687]
I didn't find anything in the documentation to make this change.

I want to change from: 
```html
<meta name="viewport" content="width=device-width">
```

For:  
```html
<meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no" />
```

**Comment by garmeeh** [comment]
Hey @matamatanot this is handled in Next.js itself. The docs for [next/head]https://nextjs.org/docs/api-reference/next/head) should be able to help you.

**Comment by matamatanot** [comment]
Not For me?
It's fine. 😄

**Comment by imangm** [comment]
Hey! 

You can also use additionalMetaTags:

```
additionalMetaTags={[
  {
    name: 'viewport',
    content: 'minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no',
  },
]}
```

Actually, In my experience, when I use NextSeo, if I put other meta tags like `viewport` inside Next.js `<HEAD>` in _app.js file, it will generate them twice. The best way to avoid it is to use NextSeo's `additionalMetaTags` to handle them.
