### ISSUE TITLE
OG:Video

### ISSUE THREAD

**Issue by slowsynapse** [garmeeh/next-seo#69]
Hello,

I am currently using your package and love it, however I noticed the og:video tag is left empty. Is it possible to allow duplicate image url (og:image) to og:video , as I have read that having it identical is fine. I can't figure out how to get a variable copied to og:video at the moment. (server rendering React).

Best regards,

**Comment by garmeeh** [comment]
Sorry about the delay in getting back to you. I am currently working on V2 and will add support for the video tag.

**Comment by garmeeh** [comment]
Now in V2.
