### ISSUE TITLE
Schema for Webpage / Website

### ISSUE THREAD

**Issue by aresrioja10** [garmeeh/next-seo#690]
We need a schema for JSON-LD type "WebSite" and "Webpage".

- https://jsonld.com/web-page/
- https://jsonld.com/website/

**Comment by garmeeh** [comment]
This is now available.

**Comment by thandaanda** [comment]
Hi @garmeeh 
Can you point me to WebSite JSON LD. I don't seem to find it. I cand find WebPageJsonLd in exported members but not Website.

**Comment by akshaybosamiya** [comment]
hi @garmeeh ,

I'm also looking for website JSON LD. Can you please point to documentation? Is it available now?

**Comment by pzi** [comment]
Looks like Website JSON LD is missing -> https://schema.org/WebSite

**Comment by meness** [comment]
@garmeeh The WebSite component is missing
