### ISSUE TITLE
Overriding default canonical property

### ISSUE THREAD

**Issue by kylemh** [garmeeh/next-seo#691]
I've got a Next app that can _often_ presume the canonical is the exact URL as-rendered. I have a few pages that have dynamic paths. I don't want a canonical tag generated for those properties.

Is there course of action here for overriding a default, or am I left with no choice but to avoid a default value for "canonical"?

**Comment by garmeeh** [comment]
Hey @kylemh, I'm not 100% sure I understand your issue 😅 Could you give a small example?

**Comment by kylemh** [comment]
I don't understand 18 days ago me either. Shut up, Kyle.
