### ISSUE TITLE
Feature request: Article type BlogPosting

### ISSUE THREAD

**Issue by tiacop** [garmeeh/next-seo#692]
Would be supercool to have "BlogPosting" as article JSON-LD type.

From the Google Docs (https://developers.google.com/search/docs/data-types/article#non-amp):

`Article objects must be based on one of the following schema.org types: Article, NewsArticle, BlogPosting.` (https://schema.org/BlogPosting)

I tried to use "BlogJsonLd" as type for Blogposts, but the Google Rich Result Test (https://search.google.com/test/rich-results) indicates "Page not eligible for rich results known by this test"  😢
By manually changing the type from "Blog" to "BlogPosting" the rich result test is successful.

Thanks

**Comment by svassaux** [comment]
I would like the same
If we use articles or blog instead, it might not have the desired effect

**Comment by travis-south** [comment]
Would `ArticleJsonLd` be sufficient for your requirement?

**Comment by tiacop** [comment]
hey @travis-south,

not exactly. On our page we have both: articles and blogposts. We would like to be precise with our JSON-LD. We use ArticleJsonLd from next/seo for our articles. For blogposts we bypass next/seo and provide the following JSON:

```JSON
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://example.url/blogposting-slug"
  },
  "headline": "Example Title",
  "image": [
    "https://example.url/image.jpg"
  ],
  "datePublished": "2021-02-10",
  "dateModified": "2021-02-23T13:49:45Z",
  "author": {
    "@type": "Person",
    "name": "Firstname Lastname"
  },
  "publisher": {
    "@type": "Organization",
    "name": "Testorganization",
    "logo": {
      "@type": "ImageObject",
      "url": "https://example.url/logo.svg"
    }
  },
  "description": "Test description"
}

**Comment by aej11a** [comment]
@garmeeh I'd love to implement this but quick question on the approach.

From what I can tell from here [https://schema.org/Article](https://schema.org/Article) and here [https://schema.org/BlogPosting]( https://schema.org/BlogPosting), Article and BlogPosting have the _exact_ same fields.

Is it ok to add this as an option on ArticleJsonLD (like a boolean `isBlogPosting` prop, and change the `@type` based on that prop) or should BlogPosting be a separate component entirely?

**Comment by hammadkh2003** [comment]
What Is SEO / Search Engine Optimization?
Search engines such as Google and Bing use bots to crawl pages on the web, going from site to site, collecting information about those pages and putting them in an index. Think of the….... for such more go through my website. https://spreadsmilesorg.in/blog/

**Comment by marcospassos** [comment]
Same need here

**Comment by marcospassos** [comment]
By the way, I can't find any references about the blog structured data. Does it exist at all?

**Comment by garmeeh** [comment]
Hey @aej11a, Article and Blog have now been merged in the latest release. `@type` is also now a prop. A small pull request to update [this](https://github.com/garmeeh/next-seo/blob/master/src/jsonld/article.tsx#L8) to allow `BlogPosting` should do the trick.

**Comment by moggiex** [comment]
> 

Might be being thick, has this been resolved @garmeeh? 

Tried using 'Blog' and 'BlogPosting' as the type and neither have the required output and get ignored by Google (can be verified in their inspection tool here [](https://search.google.com/search-console/inspect) it doesn't even show up! )

Example input:
```
<ArticleJsonLd
                type="BlogPosting"
                url={`${url}${router.asPath}`}
                headline={`${review.title} | ${process.env.NEXT_PUBLIC_SITE_NAME}`}
                description={`${shorten(clean(description), 250)}`}
                keywords={keywords.toString()}
                image={review.image && `${url}/images/cms/${review.image}`}
                images={[
                    {
                        // "@type": "ImageObject",
                        url: review.image && `${url}/images/cms/${review.image}`
                    }
                ]}
                datePublished={`${review.createdAt}`}
                dateModified={`${review.updatedAt}`}
                authorName={[`${process.env.NEXT_PUBLIC_SITE_NAME}`]}
                publisherName={`${process.env.NEXT_PUBLIC_SITE_NAME}`}

            />
```

And output: [](https://search.google.com/test/rich-results/result/r%2Farticles?id=EFeb3sq2DkHNdPsNoQM0iw)
