### ISSUE TITLE
Make Code more modular to make it open for any react project

### ISSUE THREAD

**Issue by SimonKlausLudwig** [garmeeh/next-seo#704]
I love this project. Its the best I could find. Unfortunatly I can't use it as I cant switch to next currently.

I found out that e.g. all JsonLD element uses the Head component from next therefore I could not import this component.

If we would break the component into two Files:

- Course.tsx
- NextCourse.tsx

we could get rid of the import Head from 'next/head'; import. And therefore use it in any react environment.

**Comment by rodzy** [comment]
Hi, thanks for the feedback.

But I think this cannot be done, because the whole point on the library is to make SEO easier to handle within Next.js doing that break into components for other environments let's say CRA would break the main focus of the package, plus SEO works different on Next because of the per page routing system and wouldn't be much of a hurry to get SEO to work on a SPA like create-react-app because that will not work.

**Comment by SimonKlausLudwig** [comment]
Hey rodys, of course SEO works different on. But at the end of the day First Step is generate valid JSON-LD which you then can use in any way you want.

If you could create a File which only contains the interface and another function which takes all the properties of the interface and returns a valid JSON LD. 

Everybody who wants to use JSON LD can use the library than. 

export interface ArticleJsonLdProps {
  keyOverride?: string;
  url: string;
  title: string;
  images: ReadonlyArray<string>;
  datePublished: string;
  dateModified?: string;
  authorName: string | string[];
  description: string;
  publisherName: string;
  publisherLogo: string;
}

export const toJSON: (props: ArticleJsonLdProps) => any = ({
  url,
  title,
  images = [],
  datePublished,
  dateModified = null,
  authorName,
  description,
  publisherName,
  publisherLogo,
}) => ({
  '@context': 'https://schema.org',
  '@type': 'Article',
  mainEntityOfPage: {
    '@type': 'WebPage',
    '@id': url,
  },
  headline: title,
  image: [
    images.map((image) => `"${image}"`),
  ],
  datePublished,
  dateModified: dateModified || datePublished,
  author: `${authorName}`,
  publisher: {
    '@type': 'Organization',
    name: publisherName,
    logo: {
      '@type': 'ImageObject',
      url: publisherLogo,
    },
  },
  description,
});

const ArticleJsonLd: FC<{ jsonLD: ArticleJsonLdProps, keyOverride: boolean }> = ({ jsonLD, keyOverride }:{ jsonLD: ArticleJsonLdProps, keyOverride: boolean }) => (
  <Head>
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={markup(toJSON(jsonLD))}
      key={`jsonld-article${keyOverride ? `-${keyOverride}` : ''}`}
    />
  </Head>
);

export default ArticleJsonLd;
