### ISSUE TITLE
additionalLinkTags Doesn't Overwrite Default

### ISSUE THREAD

**Issue by rzmay** [garmeeh/next-seo#706]
I've found that using `additionalLinkTags` in my `DefaultSeo` does not work as I expected. When using `additionalLinkTags` in a `NextSeo` component, rather than overwriting the tags used in `DefaultSeo`, they are simply added to the head.

I can see why this would be intended functionality, but, seeing as `additionalLinkTags` is the only way to add a favicon, it makes it impossible to have both a default and dynamic favicon. Because the browser automatically chooses which favicon to display, having both the default and intended favicon in the head leaves which will be displayed entirely out of my control. An option for `additionalLinkTags` to override the default would be really helpful in this regard.

**Comment by kaykdm** [comment]
@rzmay 
I have not tested this, but I think you can use `keyOverride` property to override link tag.
```
// default seo config
additionalLinkTags: [
{
  rel: 'icon',
  href: 'https://www.test.1/favicon.ico',
  keyOverride: 'favicon',
},
```

```
// pages/example.js
<NextSeo
  additionalLinkTags={[
        {
            rel: 'icon',
            href: 'https://www.test.2/favicon.ico',
            keyOverride: 'favicon',
       },
  ]}
/>
```
I think this is not currently documented for `additionalMetaTags` and `additionalLinkTags`

**Comment by rzmay** [comment]
@kaykdm
Thanks so much for your reply, I hadn't thought to use `keyOverride` in my `additionalLinkTags`.  I gave it a shot, and, unfortunately, I was unable to get it working. If you're able to test this code, please let me know if it works for you.

**Comment by garmeeh** [comment]
Hey @rzmay I think the suggestion by @kaykdm should work 🤔 

Could you create a small sandbox with a recreation?
