### ISSUE TITLE
how to add noindex and nofollow to all pages in DefaultSeo.

### ISSUE THREAD

**Issue by EverStarck** [garmeeh/next-seo#710]
I have this on my component: ` <DefaultSeo {...SEO} />` and in `next-seo.config.js` this:
```
export default {
  noindex: true,
  nofollow: true,
  more things here ...
}
  ```
but in the page I have: 
```
<meta name="robots" content="index,follow">
<meta name="googlebot" content="index,follow">```

What can I do?

**Comment by Fi1osof** [comment]
Looks like a bug. I do same and not works as expected. But title property rendered success.

**Comment by garmeeh** [comment]
Hey @EverStarck / @Fi1osof if you check out [this part of the docs](https://github.com/garmeeh/next-seo#no-index) it explains why it doesn't work as expected.

I believe what you might be looking for is [dangerouslysetallpagestonoindex](https://github.com/garmeeh/next-seo#dangerouslysetallpagestonoindex)

**Comment by garmeeh** [comment]
Please re-open if it doesn't solve it for you 😄

**Comment by Fi1osof** [comment]
@garmeeh thanks! 
Yes, params dangerouslySetAllPagesToNoIndex and dangerouslySetAllPagesToNoFollow solves my problem: )

**Comment by EverStarck** [comment]
> Hey @EverStarck / @Fi1osof if you check out [this part of the docs](https://github.com/garmeeh/next-seo#no-index) it explains why it doesn't work as expected.
> 
> I believe what you might be looking for is [dangerouslysetallpagestonoindex](https://github.com/garmeeh/next-seo#dangerouslysetallpagestonoindex)

Yes, it works, I don't like the idea of having       
```
<DefaultSeo {...SEO} />
<NextSeo noindex={true} nofollow={true} />
```
on a component, but meh, it works. Thanks

**Comment by Fi1osof** [comment]
@EverStarck i do just so, without NextSeo: 
```tsx
<DefaultSeo 
  noindex
  nofollow
  dangerouslySetAllPagesToNoIndex
  dangerouslySetAllPagesToNoFollow
 />
```
