### ISSUE TITLE
Why aren't double quotes escaped?

### ISSUE THREAD

**Issue by robrechtme** [garmeeh/next-seo#711]
First of all, amazing library! 

I'm getting malformed JSON errors when strings contain double quotes, it seems like they are not escaped in the JSON. 

```jsx
<ArticleJsonLd 
  // ...
  description={'A string with "double quotes"'}
/>
```

There are already a bunch of issues on this matter: https://github.com/garmeeh/next-seo/issues/215, https://github.com/garmeeh/next-seo/issues/514, https://github.com/garmeeh/next-seo/issues/515, but they aren't really tackled in the lib itself it seems.   
Is there any particular reason to not escape double quotes in this lib? Otherwise **I can look into making a PR** if you want.

**Comment by garmeeh** [comment]
Hey @robrechtme there was something in place for this but led to unexpected behavior and a lot of bugs for people. 

I would be open to a suggestion, but due to how impactful this change can be I would be very cautious about merging it. 

Part of me is leaning towards just allowing the applications handle this on their end and not adding anything to the library. 

Would love to hear your thoughts on it.

**Comment by robrechtme** [comment]
It won't be an easy fix indeed, since it needs to be added everywhere a string prop is injected in the json.

But to be honest I would really expect the library to handle it. Most developers will forget to escape double quotes or just not know this needs to be done. If you have many pages that come from a CMS, it can take a while to find out some of your pages are not parsed properly.

I will implement a suggestion (when I find the time) and write sufficient tests for this. Of course this one will need to be thoroughly checked before merging.

**Comment by cadejscroggins** [comment]
This is how I'm handling it, if it helps anyone:

```javascript
const formatJsonLdString = (string) => JSON.stringify(string).replace(/(^"|"$)/g, '');
```

**Comment by fabien** [comment]
So I only saw about this issue today, after I found out that the components don't actually work based on object serialization but some rather finicky string concatenation (yikes!).

Here's a _hot-fix_ using https://github.com/substack/js-traverse for anyone interested:

```javascript

import * as ns from 'next-seo';
import traverse from 'traverse';

export const escapeJsonLdString = string =>
  JSON.stringify(string).replace(/(^"|"$)/g, '');

export const withJsonLdEscaping = Component => {
  return props => {
    const clean = useMemo(() => {
      return traverse(props).map(function(value) {
        if (isBlank(value)) {
          this.remove();
        } else if (typeof value === 'string') {
          this.update(escapeJsonLdString(value));
        }
      });
    }, [props]);
    return <Component {...clean} />;
  };
};

const {
  ArticleJsonLd,
  BlogJsonLd,
  BreadcrumbJsonLd,
  CarouselJsonLd,
  CollectionPageJsonLd,
  CorporateContactJsonLd,
  CourseJsonLd,
  DatasetJsonLd,
  EventJsonLd,
  FAQPageJsonLd,
  JobPostingJsonLd,
  LocalBusinessJsonLd,
  LogoJsonLd,
  NewsArticleJsonLd,
  ProductJsonLd,
  ProfilePageJsonLd,
  RecipeJsonLd,
  SiteLinksSearchBoxJsonLd,
  SocialProfileJsonLd,
  SoftwareAppJsonLd,
  VideoGameJsonLd,
  VideoJsonLd,
} = Object.entries(ns).reduce((memo, [name, Component]) => {
  if (name.endsWith('JsonLd')) {
    memo[name] = withJsonLdEscaping(Component);
  }
  return memo;
}, {});

export {
  NextSeo,
  DefaultSeo,
  ArticleJsonLd,
  BlogJsonLd,
  BreadcrumbJsonLd,
  CarouselJsonLd,
  CollectionPageJsonLd,
  CorporateContactJsonLd,
  CourseJsonLd,
  DatasetJsonLd,
  EventJsonLd,
  FAQPageJsonLd,
  JobPostingJsonLd,
  LocalBusinessJsonLd,
  LogoJsonLd,
  NewsArticleJsonLd,
  ProductJsonLd,
  ProfilePageJsonLd,
  RecipeJsonLd,
  SiteLinksSearchBoxJsonLd,
  SocialProfileJsonLd,
  SoftwareAppJsonLd,
  VideoGameJsonLd,
  VideoJsonLd,
};

```

**Comment by robrechtme** [comment]
@cadejscroggins if you also want to ignore double quotes that are already escaped, you can use the following:
```ts
input.replace(/\\([\s\S])|(")/g, '\\$1$2');
```

@fabien now that you mention it, serializing JavaScript objects would indeed be a better approach for this lib, I also find the template literals a bit messy. 

However this basically means rewriting the complete code base, which is not something I have time for 😄

**Comment by fabien** [comment]
@robrechtme I don't really see where I would get already escaped double quotes from - would this be from some CMSes?

@garmeeh Regarding the serialization, I have a hard time imagining how/why it started as a concat'd solution in the first place. Seems that serializing from objects into JSON (it's called `json-ld` for a reason ...) would've been the most straightforward.

**Comment by mikestopcontinues** [comment]
@fabien I'm sure there was some reason. This library is pretty solid.

@garmeeh `json.stringify` really seems like the right call here, even if the change warranted a major version number. Are you open to it? Is there any way to expedite a PR?

**Comment by atelog** [comment]
@robrechtme 

RegEx is bad since you cannot predict all special characters that need to be escaped.

A better solution will be to use `JSON.stringify()`

Example:
```
<ArticleJsonLd
  description={JSON.stringify(description).slice(1, -1)}
/>
```
Slice is for removing the duplication of the first and last quote `" "`

**Comment by garmeeh** [comment]
`next-seo` has been re-written to enable to release of V5. A lot of the feedback given here was applied so thanks for contributing.
