### ISSUE TITLE
Missing attributes in OpenGraph images

### ISSUE THREAD

**Issue by lucasvazq** [garmeeh/next-seo#712]
These 2 attributes are missing for OpenGraph images

- **og:image:secure_url**
- **og:image:type**

https://ogp.me/#structured

**Comment by lucasvazq** [comment]
🧐

**Comment by ErnestBrandi** [comment]
Hi, I also think next-seo should automatically (or give the user the possibility to) add the `og:image:url` and `og:image:secure_url` metadata.
