### ISSUE TITLE
Video haspart attribute generates an indesirable geo key

### ISSUE THREAD

**Issue by svassaux** [garmeeh/next-seo#721]
If you look at this line, the parts of a videos are indexed with a `geo` key

https://github.com/garmeeh/next-seo/blob/61e7bfc7c6534c3e7c605f02c4e46a15a35d9aa5/src/utils/buildVideo.ts#L57

This does not comply with the specs : https://developers.google.com/search/docs/data-types/video

And therefore the test for rich elements fails for videos : https://search.google.com/test/rich-results

**Comment by svassaux** [comment]
got his email from the search console

```

Unparsable structured data issues detected on foodmeup.io
To the owner of my website
Search Console has identified that your site is affected by 1 Unparsable structured data issues: 
Top Errors
Errors can prevent your page or feature from appearing in Search results. The following errors were found on your site:
Parsing error: Missing ',' or ']' in array declaration 
We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search.



```

**Comment by garmeeh** [comment]
Hey @svassaux can you provide a link to the page? Or if you inspect your page source can copy & paste the full script tag containing the json-ld object.

**Comment by svassaux** [comment]
sure, this is the code I get on the page


`

<script type="application/ld+json">{
--
  | "@context": "https://schema.org",
  | "@type": "VideoObject",
  | "name": "Finally a modern tool for managing your culinary back office!",
  | "description": "Discover our application interface and the modules that will bring your productivity up",
  | "thumbnailUrl": [
  | "https://www.foodmeup.ioundefined"
  | ],
  | "contentUrl": "https://youtu.be/kSv6dEy1DVc",
  | "duration": "Discover our application interface and the modules that will bring your productivity up",
  | "embedUrl": "https://www.youtube.com/watch?v=kSv6dEy1DVc&t=0s",
  |  
  | "hasPart": [
  | "geo": {
  | "@type": "Clip",
  | "name": "Digitize your ingredient price list",
  | "startOffset": 0,
  | "url": "https://www.youtube.com/watch?v=kSv6dEy1DVc&t=0s"
  | }
  | ,
  | "geo": {
  | "@type": "Clip",
  | "name": "Create data sheets for recipes",
  | "startOffset": 83,
  | "url": "https://www.youtube.com/watch?v=kSv6dEy1DVc&t=83s"
  | }
  | ,
  | "geo": {
  | "@type": "Clip",
  | "name": "Print production notes",
  | "startOffset": 205,
  | "url": "https://www.youtube.com/watch?v=kSv6dEy1DVc&t=205s"
  | }
  | ,
  | "geo": {
  | "@type": "Clip",
  | "name": "Prepare your orders in one click",
  | "startOffset": 261,
  | "url": "https://www.youtube.com/watch?v=kSv6dEy1DVc&t=261s"
  | }
  | ,
  | "geo": {
  | "@type": "Clip",
  | "name": "Send them from FoodMeUp and manage deliveries",
  | "startOffset": 304,
  | "url": "https://www.youtube.com/watch?v=kSv6dEy1DVc&t=304s"
  | }
  | ,
  | "geo": {
  | "@type": "Clip",
  | "name": "Manage your stock and do stocktakes",
  | "startOffset": 345,
  | "url": "https://www.youtube.com/watch?v=kSv6dEy1DVc&t=345s"
  | }
  | ],
  |  
  |  
  |  
  | "uploadDate": ""
  | }</script>

`

from this implementation

`
      <VideoJsonLd
        name={body.primary.videoTitle[0].text}
        description={body.primary.videoDescription}
        contentUrl={videoUrl}
        embedUrl={youtubeUrl(videoId, 0)}
        uploadDate=""
        duration={body.primary.videoDescription}
        thumbnailUrls={[thumbnailUrl]}
        hasPart={body.fields.map((field) => {
          return {
            name: field.stepDescription,
            startOffset: field.stepStartingTime,
            url: youtubeUrl(videoId, field.stepStartingTime),
          };
        })}
      />
`

**Comment by garmeeh** [comment]
Hey @svassaux this should now be fixed as part of the re-write for V5. If not let me know I will can address ASAP.
