### ISSUE TITLE
`dangerouslySetAllPagesToNoIndex` won't be overridden by `noindex: false` in each page

### ISSUE THREAD

**Issue by Monchi** [garmeeh/next-seo#727]
SSIA.

I configured `dangerouslySetAllPagesToNoIndex: true` in `<DefaultSeo>`, then set `noindex: false` in `<NextSeo>` in page component. However, robots are still `noindex,follow`.

**Comment by Monchi** [comment]
I'm working on fixing this

**Comment by Monchi** [comment]
I've already created a PR for this issue. #728

Also, I've published the fork that applied #728 to the latest version(v4.24.0). This would be useful until #728 is merged.
https://github.com/Monchi/next-seo
http://npmjs.com/package/next-seo-yuku-fork

**Comment by Monchi** [comment]
Yes, this is still active. 

@garmeeh Let me friendly ping, please take a look at #728 when you have time!

**Comment by Monchi** [comment]
😢

**Comment by MAfzalKhan1997** [comment]
any update on this ?
