### ISSUE TITLE
& is turned into &amp; in og:images url

### ISSUE THREAD

**Issue by omarhoumz** [garmeeh/next-seo#729]
I'm using the `NextSeo` component to add an `og:image` to my page, my URL contains some query params. When I check the resulting meta tags, the content in this tag `<meta property="og:image" content="..." />` has the correct URL but with the `&` symbol "encoded" to `&amp;`.

Here is a codesandbox that shows the issue: https://codesandbox.io/s/next-seo-amp-43f0m?file=/pages/index.js:299-483

As an example, I'm using an Unsplash image:
`https://images.unsplash.com/photo-1585399000684-d2f72660f092?ixid=MnwxMjA3fDF8MHxlZGl0b3JpYWwtZmVlZHwxMXx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60`

If you check the codesandbox's page source, the image URL turns into
`https://images.unsplash.com/photo-1585399000684-d2f72660f092?ixid=MnwxMjA3fDF8MHxlZGl0b3JpYWwtZmVlZHwxMXx8fGVufDB8fHx8&amp;ixlib=rb-1.2.1&amp;auto=format&amp;fit=crop&amp;w=800&amp;q=60`

Am I doing something wrong?

**Comment by LawJolla** [comment]
Same problem... appreciate any help.

**Comment by RamZallan** [comment]
Hi -- why was this closed? @garmeeh I'm still seeing this issue, in my case when using [Sanity.io](https://www.sanity.io/docs/image-urls)
![image](https://user-images.githubusercontent.com/5818258/129924770-6b8819c2-d66f-4146-8c87-3cec340efc71.png)
