### ISSUE TITLE
Do we need open graph prefix in header? 

### ISSUE THREAD

**Issue by econdie** [garmeeh/next-seo#73]
Do you have any insight on if prefix="og: http://ogp.me/ns#" is required in the <head> markup to specify a page using open graph? It shows this on http://ogp.me/ (it includes it in the <html> tag but from some research  it has the same effect as <head> assuming all of the meta data is within the head). 

I struggle to find a clear answer, I am basically referring to this question: https://stackoverflow.com/questions/48933419/opengraph-prefix-in-header-necessary and if next-seo needs to include this prefix, also depending on the type specified it would include  article: http://ogp.me/ns/article# , or profile, book, etc. 

I couldn't really find a clear answer if it's required or just suggested, and i looked through several news websites for example that do seem to include this prefix markup. If you have any insight I'd be interested to know, or if you think this should be implemented, appreciate it.

**Comment by gunar** [comment]
Apparently it is required. At least for LinkedIn. I couldn't get `next-seo` to make the OG image show up in LinkedIn. [This StackOverflow answer tells me to add the prefix to the meta tag](https://stackoverflow.com/a/25093272/1456173). However, I just learned that setting it as an attribute on the `html` tag works as well:

```html
<html lang="en" prefix="og: http://ogp.me/ns#">
```
