### ISSUE TITLE
Seo metas not appearing

### ISSUE THREAD

**Issue by idiglove** [garmeeh/next-seo#748]
I have deployed my app in Vercel but the metas are not appearing.

Locally, for me to test I do `yarn build` and `yarn start`, but they still dont appear when I view pageSource

<img width="719" alt="Screen Shot 2021-05-11 at 7 16 42 PM" src="https://user-images.githubusercontent.com/29911508/117806841-6fc13d00-b28d-11eb-83a7-3be35238deea.png">
<img width="706" alt="Screen Shot 2021-05-11 at 7 17 06 PM" src="https://user-images.githubusercontent.com/29911508/117806888-7d76c280-b28d-11eb-868a-e98943153160.png">

Pls help thanks

**Comment by mfrohberg** [comment]
That would likely be because you are returning null when window is undefined. Doing so will mean that everything is only being rendered on the client
