### ISSUE TITLE
[Question] TreeShaking the modules, exclude Jsonld package.

### ISSUE THREAD

**Issue by Ktchan825** [garmeeh/next-seo#75]
I am analysing the bundle size of my project. I realised the jsonld is around 17.3 KB parsed while i am using it at all.

Is it possible to import only the NextSeo component?

I tried `import NextSeo from "next-seo/meta/defaultSEO.jsx";` and `import NextSeo from "next-seo/meta/defaultSEO";`, but it doesn't work.

**Comment by garmeeh** [comment]
Hey @Ktchan825, I'm getting close to publishing V2 of this library. Once published I will investigate tree shaking on it.

**Comment by garmeeh** [comment]
Maybe looking at switching to https://www.npmjs.com/package/tsdx for building would be a good first step to simplify.

**Comment by charles4221** [comment]
@Ktchan825 you had the right idea with your import, but you need to import from the `/lib/` directory for it to work correctly, like so:

`import NextSeo from 'next-seo/lib/meta/nextSEO';`

This is how I'm doing it and it works correctly, I'm getting only the main NextSEO component without any of the JSON-LD or other modules in my bundle.

**Comment by Ktchan825** [comment]
Hi @charles4221 , thanks for the response. Your solution would work only with version 2. Version 1.x doesn't have a lib folder and doesn't support tree shaking.
Thanks @garmeeh for the version 2 update.

**Comment by joeyorlando** [comment]
Was trying to accomplish the same thing as @Ktchan825, ended up having to import directly from the ES module file (`/lib/next-seo.modern.js`). In my case looked something like this:
```javascript
import {
  DefaultSeo,
  LogoJsonLd,
  LocalBusinessJsonLd,
  SocialProfileJsonLd,
  CorporateContactJsonLd,
} from 'next-seo/lib/next-seo.modern';
```

I am also using Typescript in my project. After changing my import from `from 'next-seo` to `from 'next-seo/lib/next-seo.modern` it started complaining that it couldn't find the type files for `next-seo/lib/next-seo.modern`. I was able to fix this by modifying my `tsconfig.json` as such: 
```json
{
  "compilerOptions": {
    "baseUrl": ".", // neccessary if paths is specified
    "paths": {
      "next-seo/lib/next-seo.modern": [
        "node_modules/next-seo/lib"
      ]
    }
  },
  ..<rest of config>
}
```
