### ISSUE TITLE
`VideoGame` schema type support

### ISSUE THREAD

**Issue by hsynlms** [garmeeh/next-seo#767]
There is a `VideoGame` schema type that is not supported in `next-seo` as LD-JSON.

It needs to be implemented, documented, and tested as a new LD-JSON type.

**Docs:**
https://schema.org/VideoGame
https://lists.w3.org/Archives/Public/public-vocabs/2014Jul/att-0011/VideoGame5.pdf

**Example:**
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.epicgames.com%2Fstore%2Fen-US%2Fp%2Fgrand-theft-auto-v

**Comment by hsynlms** [comment]
@garmeeh Did you find a chance to take a look at PRs that I sent?

**Comment by garmeeh** [comment]
Apologies @hsynlms I will take care of all open PR's within the next couple of days. Thank you for your contributions 🙏
