### ISSUE TITLE
How to do noindex/follow? index/nofollow?

### ISSUE THREAD

**Issue by geochanto** [garmeeh/next-seo#77]
It seems there is no config for "follow", and just setting `noindex` to `true` sets the meta robots to 'noindex, nofollow'. On certain pages I want to set 'noindex,follow'. How can I achieve this?

Conversely, what about 'index,nofollow'. 

These are rare in use, but I think still important to have the ability to do so.

**Comment by garmeeh** [comment]
Hey @geochanto, very good point. I had overlooked this 😅. I will investigate adding this in V2.

**Comment by geochanto** [comment]
@garmeeh sounds good. Is there a timeline on that? any quick hack or workaround in the meanwhile? :)

**Comment by garmeeh** [comment]
Hoping to publish it before next Monday if all goes well 🤞 Just testing at the moment. 

In the meantime can you try this:


```
import Head from 'next/head';

<Head>
  <meta key="robots" name="robots" content="noindex,follow" />
  <meta key="googlebot" name="googlebot" content="noindex,follow" />
</Head>
```

**Comment by jorjonl** [comment]
Hi @garmeeh, is there any follow-up about this issue? Kind regards

**Comment by whthT** [comment]
```js
import React from 'react';
import NextSeo from 'next-seo';

export default () => (
  <>
    <NextSeo noindex={true} />
    <p>This page is no indexed</p>
  </>
);
```

[https://github.com/garmeeh/next-seo#no-index](https://github.com/garmeeh/next-seo#no-index)

**Comment by dkrish** [comment]
> ```js
> import React from 'react';
> import NextSeo from 'next-seo';
> 
> export default () => (
>   <>
>     <NextSeo noindex={true} />
>     <p>This page is no indexed</p>
>   </>
> );
> ```
> 
> https://github.com/garmeeh/next-seo#no-index

this sets to noindex, nofollow, when the question is asking how to set noindex, follow.

**Comment by nik-john** [comment]
@garmeeh Did this feature end up getting released? If so I would love to raise a PR for updating the docs

**Comment by nik-john** [comment]
@garmeeh Raised a [PR](https://github.com/garmeeh/next-seo/pull/117) to address this. I'm facing this exact issue on my codebase and would love it if we can roll this out soon 🤓
