### ISSUE TITLE
Meta Conflict using withAmp in Next 8.1

### ISSUE THREAD

**Issue by ezramorse** [garmeeh/next-seo#78]
> Found conflicting amp tag "meta" with conflicting prop name="viewport"

This happens during validation when using the new withAmp HOC in conjunction with NextSeo

Expected Behavior: No warning message during AMP validation

**Comment by garmeeh** [comment]
If you inspect the output in the dom is there 2 tags with `name="viewport"?

**Comment by garmeeh** [comment]
Please re-open if the issue persists.
