### ISSUE TITLE
NextSeo Components not working on iOS devices

### ISSUE THREAD

**Issue by the-mgi** [garmeeh/next-seo#786]
I used NextSEO for our application, which worked perfectly fine for desktop windows, mac and android devices but not for iOS. Regardless of browser platform on iOS it was not loading the pages with the component on it, straight away just went on loading when clicked on the link for that page and displaying blank page when directly try to route to the page.

**Comment by garmeeh** [comment]
Hey @the-mgi can you provide an example? I have this in production and have no issues on any device.
