### ISSUE TITLE
SEO doesn't work

### ISSUE THREAD

**Issue by biggywk** [garmeeh/next-seo#788]
The problem is my website didn't be organized in the first 100-page ranking on google.
my lighthouse score average is better than 85.
mobile-friendly.
have site-map.
I use the keyword "ประกันภัยรถยนต์", include the keyword in the title tag and meta tag description.
deploy on Vercel.
and this is a stack
I need help, please. I stuck in SEO for a long time

"dependencies": {
    "@material-ui/core": "^4.11.4",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/lab": "*",
    "next": "^10.0.7",
    "next-seo": "^4.24.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "swr": "^0.3.11"
  },
  "devDependencies": {
    "typescript": "^3.9.9",
    "@types/node": "^12.20.4",
    "@types/react": "^16.14.4",
    "@types/react-dom": "^16.9.11"
  }

**Comment by garmeeh** [comment]
Hey @biggywk all next-seo can do is enable you to put SEO best practices in place. It can take some time for Google to rank your site and there are number of factors that taken into account.
