### ISSUE TITLE
Sitemap still matters

### ISSUE THREAD

**Issue by ducdev** [garmeeh/next-seo#80]
Hi, please consider supporting sitemap.xml and robots.txt in your lovely package. It's neccessary for SEO.

**Comment by garmeeh** [comment]
Hi @ducdev, thanks for the suggestion.

I agree, a `sitemap.xml` is very important for SEO. I'm not sure it would fit in with this library though. I have thought of creating a separate package for generating one however, but haven't had time 😢 

As for the `robots.txt`, it is generally very specific to the site so wouldn't be aided by a library I don't think.
