### ISSUE TITLE
Client side fetching

### ISSUE THREAD

**Issue by ErnestBrandi** [garmeeh/next-seo#808]
Hi, 
it might sounds silly but can I populate NextSeo with data fetched client side (I use SWR).
When I check metadata (with the Facebook sharing debugger for instance), it seems it uses default values (therefore before data is fecthed on client).
I know I could use getStaticProps to address this problem.
Thanks.

**Comment by garmeeh** [comment]
Hey @ErnestBrandi for the best SEO outcome all data needs to be available on page load without relying on JavaScript. This is normally achieved via server rendering or static generation. It will not work with client side fetching unfortunately

**Comment by ErnestBrandi** [comment]
Ok, got it ;)
