### ISSUE TITLE
Use stricter enum types to match schema.org definition

### ISSUE THREAD

**Issue by jsakas** [garmeeh/next-seo#809]
According to schema.org an Offer's `itemCondition` can be one of four values: `'DamagedCondition' | 'NewCondition' | 'RefurbishedCondition' | 'UsedCondition'`.

https://schema.org/OfferItemCondition

It seems like it would be helpful for developers using TypeScript to be able to see this in the types, so for example:

```
export declare type Offers = {
    itemCondition?: string;
};
```

Would become:

```
export declare type Offers = {
    itemCondition?: 'DamagedCondition' | 'NewCondition' | 'RefurbishedCondition' | 'UsedCondition';
};
```

That way developers could construct proper structured data without needing to dig through Schema.org to figure out which values to use.

As I was writing this issue it got me thinking - what if all typings were generated from schema.org, including enums, so we always know its accurate with the latest json-ld spec? We could start with the JSON representation: https://schema.org/version/latest/schemaorg-current-https.jsonld

**Comment by gregg-cbs** [comment]
@jsakas Thats an interesting thought (the json representation).. I would like to see how that pans out.
Let me know if you start working on it and want to meet up on a call to hash it out.
