### ISSUE TITLE
Using nextSeo to manage opengraph I receive a warning from Facebook in Debugger

### ISSUE THREAD

**Issue by qina83** [garmeeh/next-seo#81]
Using this configuration

```
 <NextSeo
          config={{
            title: 'my title',
            description: 'A short description goes here.',
            openGraph: {
              url: 'my url',
              title: 'my og title',
              description: 'my og description',
              images: [
                {
                  url: 'https://cdn.hasselblad.com/c81e7ee74fdc106a965f51b35c8dd87503a16f0e_tom-oldham-h6d-50c-sample1.jpg',
                  alt: 'Og Image Alt',
                }
              ],
              site_name: 'my site name',
            }
          }}
        />

```

I receive these warning 

Extraneous Property | Objects of this type do not allow properties named 'og:title'.
Extraneous Property | Objects of this type do not allow properties named 'og:description'.
Extraneous Property | Objects of this type do not allow properties named 'og:image'.
Extraneous Property | Objects of this type do not allow properties named 'og:image:alt'.
Extraneous Property | Objects of this type do not allow properties named 'og:site_name'.

**Comment by garmeeh** [comment]
Could you post the meta tags that are in the head of your page?

**Comment by garmeeh** [comment]
Please re-open if the issue is on going.

**Comment by dpashovski** [comment]
I'm having this issue with Facebook Debugger , also reflects the posts that are posted ... 
weird thing is that when i check some link with Facebook Debugged it shows that everything is okey , but if i rescrape the link few more times , at some point it gives me those warnings...  
It's random.... if i check in the sourcecode i can see the meta tags but i'm still getting this warnings from time to time from facebook debugger.... this is the object that i send to <NextSeo> :

```
   "seoObj":{
      "title":"....",
      "description":".....",
      "canonical":"...",
      "noindex":false,
      "openGraph":{
         "title":"....",
         "description":"....",
         "url":".......",
         "publishedTime":"2020-12-10 17:58:49",
         "modifiedTime":"2020-12-15T16:32:32Z",
         "type":"article",
         "images":[
            {
               "url":"...",
               "alt":"..."
            }
         ],
         "authors":[
            "...."
         ]
      },
      "twitter":{
         "cardType":"summary_large_image",
         "title":"...",
         "description":".....",
         "url":"......",
         "image":"....."
      },
      "additionalMetaTags":[
         {
            "name":"article:publisher",
            "property":"article:publisher",
            "content":"........."
         }
      ]
   }
```
