### ISSUE TITLE
Twitter not picking up OG tags

### ISSUE THREAD

**Issue by simpleshadow** [garmeeh/next-seo#82]
Super grateful for the package @garmeeh!

I see you mention in a few issues (#14) that Twitter uses the OG tags but it's not.

Would be good if `next-seo` allowed setting of any OG tag provided so we can provide tags as necessary.

**Comment by garmeeh** [comment]
Hey @simpleshadow, thanks 😄 

V2 will have the option to add additional tags. Because of breaking changes in V2 I am thinking about adding the "missing" twitter tags in V1.

**Comment by garmeeh** [comment]
Can you share your site or example of the meta tags rendered for the issue you are having?

**Comment by simpleshadow** [comment]
As an example — https://coreygwin.com/newsletter.

I ended up using `next/head` to implement the additonal meta `twitter:*` tags to get the title, description, and image working on Twitter. 

Look forward to V2!

**Comment by garmeeh** [comment]
Thanks. Yeah from looking at that removing the `twitter:*` tags and adding the equivalent `og:*` ones should work. On my own personal site I only use `og:*` and it shares on Twitter as expected. 

Not too sure why it wasn't working for you.

**Comment by swilgosz** [comment]
I've the same issue in my https://hanamimastery.com articles links. Twitter (and reddit) - does not pick-up the og:images - while all the facebook-related media (pinterset, instagram, facebook), even LinkedIn - have No issues at all.

Does anyone have an idea why this could be happening?

**Comment by swilgosz** [comment]
I've solved it! for anyone encountering this issue in the future, In my case, it was related to the fact, that I"ve used the relative path in the image instead of URL prefixed with a host. After changing this to absolute URL of the image, twitter started to behave as expected.
