### ISSUE TITLE
Include `productID` and `url` in ProductJsonLd props

### ISSUE THREAD

**Issue by Guneetgstar** [garmeeh/next-seo#825]
This is a great lib especially to deal with JSON-ld structured data but for my use case I couldn't make it work for me because as per for [Facebook Marketing API](https://developers.facebook.com/docs/marketing-api/catalog/reference/#json-ld) `productID ` and `url` is among one of the fields required which are the only field missing from `next-seo`'s `ProductJsonLd` component. 

It would be very great if we can include `productID` and `url` in `ProductJsonLd` props and make the required changes to reflect it in the JSON-ld as well.

I can make a PR for the same if someone approves it.

**Comment by Guneetgstar** [comment]
Another way would be to make the whole `next-seo` props extensible which is going to be a little more time taking but the result would good for everyone.

**Comment by gregg-cbs** [comment]
@Guneetgstar I think what you are talking about with props extensibility is mentioned here: 
https://github.com/garmeeh/next-seo/pull/802

Which might also solve this issue entirely.

**Comment by Guneetgstar** [comment]
> @Guneetgstar I think what you are talking about with props extensibility is mentioned here:
> #802
> 
> Which might also solve this issue entirely.

It seems like you got my point but I can't find anything relevant to props extensibility in the mentioned issue. What I see is @akshatmittal has given a fix to remove the line breaks from the JSON-LD strings which may reduce the overall size of the page.

**Comment by gregg-cbs** [comment]
@Guneetgstar

It is also mentioned that changing the stringified version to objects would make the schemas extendable.
https://github.com/garmeeh/next-seo/pull/802#issuecomment-867624629

**Comment by emmekappa** [comment]
having the same issue: i would like to pass `productID` in order to be compliant with Facebook Marketing API

**Comment by ElegantSoft** [comment]
Any updates in this?
