### ISSUE TITLE
Ampersand turned into "&amp;" in og:image URLs

### ISSUE THREAD

**Issue by RamZallan** [garmeeh/next-seo#847]
Note, this duplicates #729, which was closed automatically and I can't seem to reopen.

I'm using [Sanity.io](https://www.sanity.io/docs/image-urls) to host my images and construct URLs to serve them with specific crops/sizes. Next-seo seems to be url-formatting the ampersands for the query parameters.

![image](https://user-images.githubusercontent.com/5818258/129925161-b16e9011-163f-4acb-bc6b-a411fc2d676e.png)

**Comment by RamZallan** [comment]
@garmeeh still relevant- any insight?

**Comment by ccorda** [comment]
Can confirm we also have this issue.

Original variable before being passed in to next SEO works without trouble:
`/_next/image?url=file.png&w=1200&h=628&q=75`

But when it gets processed by NextSEO, it's converted to this which doesn't work: `/_next/image?url=file.png&amp;w=1200&amp;h=628&amp;q=75`

specific error from next/image:
`"w" parameter (width) is required`

**Comment by ccorda** [comment]
Apologies, found this related thread and it is indeed an upstream React issue:
https://github.com/garmeeh/next-seo/issues/678
