### ISSUE TITLE
How to deal with HTML entities in page titles?

### ISSUE THREAD

**Issue by geochanto** [garmeeh/next-seo#85]
My page titles are coming from Wordpress and some contain HTML entities (like `&#8211;`).

How can I convert this inside NextSEO config? Normally I would use dangerouslySetInnerHtml, but I don't think that syntax would work inside the config.

**Comment by geochanto** [comment]
Any word on this?

**Comment by garmeeh** [comment]
Hey @geochanto, I would say what you could do is call a function for the title that returns the html. Haven't tried it but should work. It might look something like:

```
getTitle(title) {
    return {
      __html: `${title}`,
    };
  }
```

```
config={{
  title: this.getTitle(this.props.title)
}}
```

**Comment by geochanto** [comment]
@garmeeh hmm that looks like it actually returns an object for some reason. I'm getting `[object object]`

**Comment by carly-cloud** [comment]
Do we have a solution for this?

**Comment by IlirBajrami** [comment]
I need a solution for thi one too. any news?
