### ISSUE TITLE
Duplicated openGraph meta tags

### ISSUE THREAD

**Issue by danestves** [garmeeh/next-seo#864]
![image](https://user-images.githubusercontent.com/31737273/133879866-ee880ee3-3fba-4b90-8573-f957a3884ab4.png)

I'm using `DefaultSeo` & `NextSeo` to override the current tags, but inspecting the code I see that some tags was overridden but title, description, and image not

**Comment by jawil003** [comment]
Hey can you provide an example? So you mean the `<link as="image" ... />` tags, right?

**Comment by jawil003** [comment]
I created an example where `og:title` and `og:description` are set and they override each other like expected. 
<img width="1440" alt="CleanShot 2021-10-07 at 22 15 57@2x" src="https://user-images.githubusercontent.com/47473728/136455831-38b444ed-e53c-4983-9f44-802435be2155.png">
<img width="1438" alt="CleanShot 2021-10-07 at 22 16 47@2x" src="https://user-images.githubusercontent.com/47473728/136455922-c80349c4-66a3-4a2b-b61e-ff6de55e1bc4.png">
Can you may provide an full example of this issue?

**Comment by brenopolanski** [comment]
> I created an example where `og:title` and `og:description` are set and they override each other like expected.

I have the same issue with duplication of `og:title` and `og:description`. In local development it works fine, but in production mode the meta tags are duplicated.

To reproduce @jawil003, try run:

1. `yarn build`
2. `yarn start`

**Comment by brenopolanski** [comment]
> > I created an example where `og:title` and `og:description` are set and they override each other like expected.
> 
> I have the same issue with duplication of `og:title` and `og:description`. In local development it works fine, but in production mode the meta tags are duplicated.
> 
> To reproduce @jawil003, try run:
> 
> 1. `yarn build`
> 2. `yarn start`

I realized that the problem is with my build in `next.config.js`. Because I'm using Preact to replace React with the webpack alias config:

```tsx
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  webpack: (config, { dev, isServer }) => {
    if (!dev && !isServer) {
      // Replace React with Preact only in client production build
      Object.assign(config.resolve.alias, {
        'react/jsx-runtime.js': 'preact/compat/jsx-runtime',
        react: 'preact/compat',
        'react-dom/test-utils': 'preact/test-utils',
        'react-dom': 'preact/compat',
      });
    }

    return config;
  },
};

module.exports = nextConfig;
```

If I remove the code above, there will be no duplicate meta tags when I use next-seo.

**Comment by selenecodes** [comment]
Having the same issue as @brenopolanski when using preact

**Comment by blankart** [comment]
I'm also having the same issue. [This](https://github.com/preactjs/preact/issues/3403) might be related to this issue.

**Comment by aonawale** [comment]
also having this issue

**Comment by ing-ivan-31** [comment]
I am facing the same issue.

**Comment by yangxiling** [comment]
also having this issue
