### ISSUE TITLE
Can we bring in bingbot as well?

### ISSUE THREAD

**Issue by ben1one** [garmeeh/next-seo#871]

**Comment by jawil003** [comment]
According to the [docs](https://www.bing.com/webmasters/help/which-robots-metatags-does-bing-support-5198d240) Bing uses the same meta tags as google crawler do, f.e. `<meta name="robots" content="noindex">`

The default in next-seo is always index and follow when you use `<DefaultSeo/>` in your app. So it should be fine. When you want a page to be not crawled you have the nofollow and noIndex props on the `<NextSeo/>`tag.
