### ISSUE TITLE
Global state make it impossible to use DefaultSEO in a multitenant app

### ISSUE THREAD

**Issue by jomarl** [garmeeh/next-seo#872]
If a page is rendered once with the following options, e.g. in _app:

```
<DefaultSeo dangerouslySetAllPagesToNoFollow={true}
                       dangerouslySetAllPagesToNoIndex={true}/>
```

then a preceding rendering rendering/request with:

```
<DefaultSeo dangerouslySetAllPagesToNoFollow={false}
                       dangerouslySetAllPagesToNoIndex={false}/>
```

will have no effect due to the use of the globally scoped "defaults" structure that is updated on server and persistent between requests. This might be a bit of an edge case.

**Comment by caseBread** [comment]
any updates in this?

**Comment by caseBread** [comment]
I've encountered an issue while using the library in a multi-tenant environment (different URLs but same server instance), similar to what's described in the issue above. When deploying a Next.js instance on a single server, it seems that the initial default value is shared across different users, as the server memory retains it upon initialization.

I'm interested in addressing this, but before proceeding, I wanted to check if there was a specific reason for configuring the default value to be shared in a server environment.
