### ISSUE TITLE
paths with query get escaped

### ISSUE THREAD

**Issue by equinusocio** [garmeeh/next-seo#88]
Hi, i use a generated image containing query parameters as og image, but the path in the final output include escaped `&` making the path invalid:

**path**:
```
https://images.ctfassets.net/gz0sygvqczyz/1LlU2yNbXooedOqW3UeNA1/b1d427094354ac34cf9dc4f8a319957a/fieldset.png?fit=pad&f=top&w=1200&h=630&bg=rgb:F3F6F9
```

**output**:

```
https://images.ctfassets.net/gz0sygvqczyz/1LlU2yNbXooedOqW3UeNA1/b1d427094354ac34cf9dc4f8a319957a/fieldset.png?fit=pad&amp;f=top&amp;w=1200&amp;h=630&amp;bg=rgb:F3F6F9
```

The original path is working, while the second one nope, causing a wrong parsing by crawlers.

**Comment by equinusocio** [comment]
Found that is a React bug. Track https://github.com/facebook/react/issues/13838

**Comment by namevalues** [comment]
```
import React from "react";
import { NextSeo } from "next-seo";

export default () => (
  <>
    <NextSeo
      openGraph={{
        images: [
          {
            url: "https://images.ctfassets.net/gz0sygvqczyz/1LlU2yNbXooedOqW3UeNA1/b1d427094354ac34cf9dc4f8a319957a/fieldset.png?fit=pad&f=top&w=1200&h=630&bg=rgb:F3F6F9",
            width: 800,
            height: 600,
            alt: "Og Image Alt"
          }
        ],
      }}
      
    />
    <p>SEO Added to Page</p>
  </>
);
```

![스크린샷 2019-08-08 오후 6 09 59](https://user-images.githubusercontent.com/28758696/62690519-c8540e00-ba07-11e9-953c-560d2bbfa6a9.png)

Is this what you want??
I dont know your code, but i think query string makes some bug..?

**Comment by equinusocio** [comment]
@namevalues From the inspector you see the correct path. If you check the page source, you will see the original and encoded path. The code is exactly the same as your.

**Comment by garmeeh** [comment]
Hey @equinusocio, really sorry I only got some time now to really look into this. After doing some digging it seems like this is an issue in React itself. I don't think there is anything I can on this end.

**Comment by equinusocio** [comment]
@garmeeh I had to switch to Nuxt because this issue. vue-head for example has a `__dangerouslyDisableSanitizers` to disable string encoding inside **all** meta or 
`__dangerouslyDisableSanitizersByTagID` to disable encoding on specific elements.

```js
__dangerouslyDisableSanitizersByTagID: {
   'ip:image': ['content'],
   'og:image': ['content'],
   'twitter:image': ['content']
}
```
