### ISSUE TITLE
noindex does not work

### ISSUE THREAD

**Issue by geochanto** [garmeeh/next-seo#881]
Setting **noindex** to true should produce `<meta name ="robots" content="noindex,nofollow">`. 

Instead, it's still `index,follow`

next-seo v4.28.1, nextJS v10.2.3

**Comment by riccardogiorato** [comment]
Can you create a codesanbox with this example?

**Comment by GandharvJaggi** [comment]
@geochanto hi, i faced the same issue, so i went over the code and it's perfectly fine. 

what i can tell you after my research and debugging is that, <NextSeo /> runs in a sequential manner, hence keep in mind if the page you want noIndex on, doesnt have more than one "instances" of NextSeo, else if the last instance in compilation doesn't have noIndex, it will be treated as false.
I solved it by moving the instance to the end of the HTML code in the outer most file of the page, which made sure that the last instance has the noIndex set to true. 

Hope it help :)

**Comment by geochanto** [comment]
OK, I think I narrowed down the issue.

`noindex` and `nofollow` don't work when used in the `DefaultSeo` component. They work fine in `NextSeo` component.

So this still seems like a legit bug, although not as severe.

**Comment by kevin-and-dev** [comment]
In case someone still looking for solution, this is how I fix it

```
// next.config.js
const withNextra = require('nextra')({
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.tsx',
})
module.exports = withNextra()
```

```
// theme.config.tsx
import React from 'react'
import { DocsThemeConfig } from 'nextra-theme-docs'

const config: DocsThemeConfig = {
  useNextSeoProps() {
    return {
      noindex: true,
      nofollow: true,
    }
  },
  // ...
}
// ...
```
