### ISSUE TITLE
```og:title``` is empty when ```defaultTitle``` is provided

### ISSUE THREAD

**Issue by ekrzeptowski** [garmeeh/next-seo#886]
When ```defaultTitle``` prop is supplied in ```<DefaultSEO />``` component ```og:title``` is not being correctly set

**Comment by mathieutu** [comment]
For a quickfix, you can reset `titleTemplate` just were you need  it:

```jsx
<NextSeo
  titleTemplate="%s"
  title="My title"
/>
```

**Comment by mathieutu** [comment]
Still and always... 🙄

**Comment by garmeeh** [comment]
This has now been fixed in V5. Please let me know if it is not working as expected and I can fix.
