### ISSUE TITLE
Wrong type for field brand

### ISSUE THREAD

**Issue by gm-rebricker** [garmeeh/next-seo#896]
Hello,
I set the brand in the product like this:
<ProductJsonLd
....
brand="LEGO"
/>
The generated JSON looks like:
"brand": {
      "@type": "Thing",
      "name": "Lego"
    },

The problem is google shows me the following warning:
Wrong type for field brand.
Supported types: [http://schema.org/Brand,http://schema.org/Organization]

How can I fix this?

**Comment by chrillep** [comment]
ping!

**Comment by mercteil** [comment]
ping!

![image](https://user-images.githubusercontent.com/36293774/149097079-4d3f0cf1-fe0f-4771-94e6-5f4de1b8ee52.png)
!

**Comment by chrillep** [comment]
yay :)

**Comment by garmeeh** [comment]
This should now be fixed in V5.
