### ISSUE TITLE
noindex, nofollow, disableGooglebots, robotsProps props dose not working in DefaultSeo

### ISSUE THREAD

**Issue by vreality64** [garmeeh/next-seo#897]
These props are invalid in `DefaultSeoProps`.
1. noindex
2. nofollow
3. disableGooglebots
4. robotsProps

https://github.com/garmeeh/next-seo/blob/abfeb47e77c5815fd32bb8441f3368aa97fef96d/src/types.ts#L267-L275

it's not bypassed into `DefaultSeo.tsx`

https://github.com/garmeeh/next-seo/blob/abfeb47e77c5815fd32bb8441f3368aa97fef96d/src/meta/defaultSEO.tsx#L32-L52

I think these props have to be omit in DefaultSeoProps.

**Comment by vreality64** [comment]
it's not stale :)

**Comment by vreality64** [comment]
From v5 version, defaultSEOProps no longer extends NextSeoProps and is declared as an independent type. Thank you :)

**Comment by moshethebeadle** [comment]
I have this same issue... sounds like maybe I should upgrade :)
