### ISSUE TITLE
Cannot Find   "isAccessibleForFree" prop in next-seo.

### ISSUE THREAD

**Issue by heli-solutelabs** [garmeeh/next-seo#902]

**Comment by nyedidikeke** [comment]
@heli-solutelabs Please provide context, current behaviour and expected one.

**Comment by garmeeh** [comment]
@heli-solutelabs please provide desired behviour and example output along with relevant docs relating to `isAccessibleForFree`

**Comment by msahajwani** [comment]
Hi @garmeeh 

This is required for subscription paywall content - https://developers.google.com/search/docs/advanced/structured-data/paywalled-content

Basically, two properties are required:

`"isAccessibleForFree": "False",
      "hasPart":
        {
        "@type": "WebPageElement",
        "isAccessibleForFree": "False",
        "cssSelector" : ".paywall"
        }`

**Comment by edoardolincetto** [comment]
Hi @garmeeh, I need this feature, is really useful when working with paywalled articles.
I can work on this! 🙋🏻‍♂️
