### ISSUE TITLE
mutiple data in ProductJsonLd

### ISSUE THREAD

**Issue by vinay07A** [garmeeh/next-seo#91]
how can loop the productjsonld if i have mutiple products in same page. map function is overriding.if i do loop.

i want display like this.
`[  
   {  
      "@context":"https://schema.org/",
      "image":[  
         "https://lssdsdsdsds"
      ],
      "@type":"Product",
      "name":"Product name"
   },
  {  
      "@context":"https://schema.org/",
      "image":[  
         "https://lssdsdsdsds"
      ],
      "@type":"Product",
      "name":"Product name 2"
   },
{  
      "@context":"https://schema.org/",
      "image":[  
         "https://lssdsdsdsds"
      ],
      "@type":"Product",
      "name":"Product name 3"
   },
]`

**Comment by garmeeh** [comment]
Hey @vinay07A, the spec for product is for an individual product. So if you have a page that lists all of your products, as long as you can click through to the product detail page and this detail page implements the Product JSON-LD you should be covered. 

You can read more about the spec here: https://developers.google.com/search/docs/data-types/product
