### ISSUE TITLE
Disable Googlebots was removed?

### ISSUE THREAD

**Issue by tobiasorosa** [garmeeh/next-seo#927]
We had the option to disable googlebots with a boolean prop (implemented here #869)  until version 4.29.0, which has been removed in v5.0.0, specifically at this PR #873. It must have been for better maintenance of the code, but if not, it would be great to know why, and if possible, to be re-added so that it stays up-to-date.

**Comment by garmeeh** [comment]
Hey @tobiasorosa what is the issue you are having? 

`googlebots` is now not included by default so the props have been remove.

**Comment by garmeeh** [comment]
Hey @tobiasorosa apologies about that. It was listed as a breaking change in the release notes: https://github.com/garmeeh/next-seo/releases/tag/v5.0.0

If needed you can add it back in via `additionalMetaTags`
