### ISSUE TITLE
Optional chaining operator doesn't compile and doesn't work in older browsers

### ISSUE THREAD

**Issue by iipanda** [garmeeh/next-seo#932]
**Describe the bug**
The `?.` somehow doesn't get compiled by TypeScript (it is normally replaced during compilation, see the compiled code [here](https://www.typescriptlang.org/play?#code/MYewdgzgLgBCBGArGBeGBvAhgLhgRgBoZ5cAmAXwChRIQAbAUwDo6QBzACgUQH4nMAlEA)), and it ends up in the bundle, causing the app using `next-seo` to crash in older browsers that don't support that operator.

Here's our Sentry error message caused by this:
```
SyntaxError: Unexpected token .
  at ? (./node_modules/next-seo/lib/next-seo.module.js:210:14)
  ```

**Reproduction**
Just open this CodeSandbox in new tab, and search `chunks/pages/index[garbage].js` for `?.`
I set up this CodeSandbox to run a production build and not in dev mode
https://codesandbox.io/s/pensive-danny-5s7mzd

**Comment by medv** [comment]
Can confirm this is an issue. Development builds without issue, fails to compile with the same error in vercel.

**Comment by futantan** [comment]
Got the same issue

**Comment by alexstanbury** [comment]
Had the same issue, I solved deploying to Vercel by upgrading the version of node used from 12 to 14 in the Vercel settings.

**Comment by snelsi** [comment]
![image](https://user-images.githubusercontent.com/15171036/157460328-0861d989-2bfc-46f0-a90e-107f8040a8fe.png)
Firefox 72, Windows 11

**Comment by prince272** [comment]
I also experience the same issue on older browsers

**Comment by futantan** [comment]
Maybe this can help:
```js
const withTM = require('next-transpile-modules')(['next-seo']); // pass the modules you would like to see transpiled

module.exports = withTM(nextConfig)
```

**Comment by sos0** [comment]
I'm unable to use this library due this same error.

**Comment by technion** [comment]
I've been looking into this. I'm fairly sure a more specific fix than Babel, is with Typescript here:

https://github.com/garmeeh/next-seo/blob/master/tsconfig.json#L3

If you write something with optional chaining in the typescript playground:

https://www.typescriptlang.org/play

You'll see you need to set the target to ES2019 or lower to get it to compile the chaining out. The current "ESNext" doesn't do any downgrading.

**Comment by technion** [comment]
I've confirmed the issue doesn't exist the below older version, temporary workaround:

npm install next-seo@4.29.0 --save

I had the same issue as @sos0 , if I try to use the patch suggested it doesn't actually end up exporting the module.

**Comment by snelsi** [comment]
@sos0 @technion 
This package has an extra build step when it's published, so you can't use Github repo directly as a package declaration.

Try this, I published my fork as a npm package:
`npm i @snelsi/next-seo`

Swap all imports of `next-seo` with `@snelsi/next-seo`. You can swap back once original package is patched.

**Comment by garmeeh** [comment]
Can someone test `v5.2.0`? This contains a fix added by @snelsi 💪

**Comment by snelsi** [comment]
Can confirm **5.2.0** fixed issue in my project 🎉

**Comment by armandabric** [comment]
I was getting the same issue. Upgrading to 5.2 solve the issue :+1:
