### ISSUE TITLE
Build Error at Nextjs deployment

### ISSUE THREAD

**Issue by Sakthisivaprakash** [garmeeh/next-seo#936]
**Describe the bug**
Faced build Error at Vercel Deployment:

`<html>
<body>

> Build error occurred at deployment
--
01:41:53.477 | /vercel/path0/node_modules/next-seo/lib/next-seo.js:215
01:41:53.477 | if (config.openGraph?.title \|\| updatedTitle) {

</body>
</html>`

**Reproduction**
For issues to be triaged in a timely manner please provide a Codesandbox/Github of the issue in it's simplest reproduction. 
error occurred at vercel deployment:
belowe are versions: 
"next": "^12.1.0",
    "next-seo": "^5.1.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",

**Expected behavior**

**Additional context**

**Comment by nyedidikeke** [comment]
@Sakthisivaprakash Kindly share content of your `package.json` file and the command run and full error message.

**Comment by christofferberg** [comment]
@Sakthisivaprakash 

What is your Node version on Vercel?
If 12, try 14. 🤞

**Comment by dkast** [comment]
@christofferberg I had the same issue just today and changing the Node version to 14 fixed the error. Thanks!

**Comment by Sakthisivaprakash** [comment]
> @Sakthisivaprakash
> 
> What is your Node version on Vercel? If 12, try 14. 🤞

**Comment by Sakthisivaprakash** [comment]
Bug solved after changing node version from 12 to 14 in Vercel deployment settings

**Comment by Sakthisivaprakash** [comment]
> @Sakthisivaprakash
> 
> What is your Node version on Vercel? If 12, try 14. 🤞

Thanks for your solution @christofferberg

**Comment by Kerim-Willem** [comment]
Had the same issue. This thread fixed it for me, upgrading to v14. Thanks!
