### ISSUE TITLE
meta tags on Linkedin not working as it requires both name and property to be in meta tags.

### ISSUE THREAD

**Issue by GorvGoyl** [garmeeh/next-seo#938]
Meta tags on Linkedin are not working as it requires both `name` and `property` to be in meta tags.

URL to inspect OG tags on Linkedin: https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fgourav.io%2Fblog%2Fautohotkey-scripts-windows

Tags which are not working: title, Image, Description, Author

All three `name`, `property`, and `content` should be there.

<img width="542" alt="CleanShot 2022-03-14 at 15 24 37@2x" src="https://user-images.githubusercontent.com/7106086/158148600-d2b42935-b3fc-4b17-aad4-35e1d6f0893c.png">

<img width="518" alt="CleanShot 2022-03-14 at 15 22 15@2x" src="https://user-images.githubusercontent.com/7106086/158148142-32ca57ab-0a73-4533-a3ea-2338239c5731.png">

<img width="533" alt="CleanShot 2022-03-14 at 15 22 31@2x" src="https://user-images.githubusercontent.com/7106086/158148189-d34456f2-3849-48dc-af86-270b50630fcb.png">

Also, the author tags needs to be name instead of property

<img width="530" alt="CleanShot 2022-03-14 at 15 22 56@2x" src="https://user-images.githubusercontent.com/7106086/158148304-eb4dcfdd-d9db-4ec3-832e-b2170ec3f391.png">

**Comment by philohelp** [comment]
I'm facing the same situation here. Pretty embarassing.

**Comment by ernests** [comment]
Anyone update on this issue?

**Comment by GorvGoyl** [comment]
@ernests it's taking props from the homepage instead of that specific link

**Comment by ernests** [comment]
Solved the problem.
First of all I had a typo in canonical url tag (og:url). Apparently linkedin fetch this url and then checks all the tags. 
Second, I used NextSeo additionalMetaTags option to add tags it wouldn't see.

**Comment by GorvGoyl** [comment]
@ernests, I'm still facing the issue... could you share that page link so that I can match my metatags and find the root cause

**Comment by 0xjessel** [comment]
I had the same issue and for me, it was realizing that my `og:url` property was missing the `https://` prefix.  Without it, LinkedIn was ingesting my canonical URL incorrectly (it led to my 404 page, which meant the og:tags that were being read were my homepage's).   Hope this helps somebody.

**Comment by garmeeh** [comment]
Thanks for the follow up info everyone. Always very helpful.
