### ISSUE TITLE
Meta keywords - how do I add them?

### ISSUE THREAD

**Issue by willvlad** [garmeeh/next-seo#94]
The docs seem silent on that...

**Comment by garmeeh** [comment]
Hey @willvlad, you can leverage the [additionalMetaTags](https://github.com/garmeeh/next-seo#additional-meta-tags) key to add keywords. 

It doesn't have it's own key as it used less frequently these days.

**Comment by smith558** [comment]
I think `keywords` should be added as a separate key; they're still required even nowadays.
