### ISSUE TITLE
NextSeo doesn't render tags in heads on SSR in React 18

### ISSUE THREAD

**Issue by joemckenney** [garmeeh/next-seo#945]
**Describe the bug**
Happy users of NextSeo in a very simple webpage.  After an upgrade of react from 17.0.2 to 18.0.0 NextSeo no longer rendered SEO tags in the `<head />` on SSR.

**Reproduction**
Created minimal branches that repro the issue:
Not working w/ React 18.0.0, see  https://github.com/joemckenney/next-seo-bug
Working w/ React 17.0.2, see https://github.com/joemckenney/next-seo-bug/tree/react-17.0.2

**Expected behavior**
SEO related tags are rendered on SSR.

**Comment by garmeeh** [comment]
I will investigate this ASAP. I’m AFK right now but will look when I’m back. Should have an update on the issue tomorrow.

**Comment by garmeeh** [comment]
Probably related to #930

**Comment by garmeeh** [comment]
Hey @joemckenney can you try updating to the latest version of `next`. I think it was an upstream issue. 

And also thank you for submitting a good reproduction, would have lost hours trying to debug this one without it!

**Comment by joemckenney** [comment]
@garmeeh updating next seems to fix the issue.  Thanks for the help!
