### ISSUE TITLE
Breadcrumb JSON-LD missing 'id' field 

### ISSUE THREAD

**Issue by 0x54321** [garmeeh/next-seo#95]
Google Search Console is reporting that the breadcrumb data is missing the 'id' field. Apparently the schema has changed a bit.

Instead of:
```
        {
          position: 1,
          name: 'Books',
          item: 'https://example.com/books',
        },
        {
          position: 2,
          name: 'Authors',
          item: 'https://example.com/books/authors',
        }, ...
```

It should now be:
```
        {
          position: 1,
          item:
                  {
                   '@id': 'https://example.com/books',
                    name: "Books"
                   }
        },
        {
          position: 2,
          item:
                  {
                   '@id': 'https://example.com/authors',
                    name: "Authors"
                   }
        }, ...
```

Documentation:
https://schema.org/item
https://jsonld.com/breadcrumb/

Thanks for the great package!

**Comment by garmeeh** [comment]
Hey @0x54321, that's an interesting one..

I went with Google's own recommended approach: 

https://developers.google.com/search/docs/data-types/breadcrumb 

I will do a little digging on this and see can I find the correct approach.
