### ISSUE TITLE
It does not change the default values.

### ISSUE THREAD

**Issue by ahalaburda** [garmeeh/next-seo#952]
**Describe the bug**
When you set a default for SEO like https://github.com/garmeeh/next-seo#default-seo-configuration, create a custom _app.js file with a default configuration there, and then try to modify that default values on other pages. In production, it works only by checking in your browser, but when using a meta tags inspector or sharing the link via Twitter, FB or Slack it is always the default.

I tried creating a small project setting that to production in a private server o even using ngrok and is always the same behavior, the new values aren't settings into the prerendering heads value so always are by default.

To replicate create a new project, use ngrok and check with sites like [https://metatags.io/](https://metatags.io/)

**Comment by ahalaburda** [comment]
`// import "bootstrap/dist/css/bootstrap.css";
import "../styles/base.scss";
import "../styles/app.scss";
import React, { useEffect } from "react";
import { ContextProvider } from "../context/main-context";
import RouterContext from "../context/router";
import TagManager from 'react-gtm-module'

import { DefaultSeo } from 'next-seo';
import SEO from '../next-seo.config';

const tagManagerArgs = {
  gtmId: 'GTM-XXXXXXX'
}

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    import("bootstrap/dist/js/bootstrap");
    TagManager.initialize(tagManagerArgs)
  });
  return (
   <>
     <DefaultSeo {...SEO}/>
    <ContextProvider>
      <RouterContext>
        <Component {...pageProps} />
      </RouterContext>
    </ContextProvider>
    </>
  );
}

export default MyApp;
`

**Comment by garmeeh** [comment]
Hey 👋 

What you are describing usually indicates you are not fully server rendering the page in question. To test in the browser disable JavaScript or view page source.

Usually it’s due to rendering being blocked by state being set in a useEffect or maybe even a global context that is waiting on state from client.

**Comment by ahalaburda** [comment]
Hi @garmeeh,
I also tried disabling javascript, but the same behavior. And after creating new projects for testing and changing the <DefaultSeo {...SEO}/> inside the RouterContext and ContextProvider it doesn't work as it should be.  The cause is the useEffect of the contexts.
