### ISSUE TITLE
Can I use next-seo in angular app ?

### ISSUE THREAD

**Issue by sunysunysuny** [garmeeh/next-seo#959]
Hey Guys,

I just want to know that can we use next-seo in angular app ??
Please reply as soon as possible.

Thanks

**Comment by jrandallw** [comment]
This package seems to be built to work exclusively within a Next.js context, so unfortunately no. There seem to be similar libraries built for Angular on npm, I'd recommend taking a look there. A quick search turned this up, might get you started:

[https://www.npmjs.com/package/ngx-seo](https://www.npmjs.com/package/ngx-seo)
