### ISSUE TITLE
Fully custom meta like from API

### ISSUE THREAD

**Issue by Anjianto** [garmeeh/next-seo#964]
**Is your feature request related to a problem? Please describe.**
Currently i have some jobs that requires fully custom meta and i found that next-seo doesn't have support children for fully custom SEO. i know it will make many problem like XSS attack while you can prevent and duplication meta tag

**Describe the solution you'd like**
it will support children to render fully custom meta. User can be use their tools to render dynamic tag to HTML/React Component

**Describe alternatives you've considered**
1. use JavaScript for enject the script. But, it make not friendly SEO.
2. manually write/inject aka make your own

**Additional context**
<img width="267" alt="Screen Shot 2022-05-30 at 19 16 13" src="https://user-images.githubusercontent.com/61521141/170990523-e572c27b-4c28-422d-a0cc-cec78dd000c7.png">

**Comment by garmeeh** [comment]
Hey @Anjianto you should be able to use [next/head](https://nextjs.org/docs/api-reference/next/head) directly to achieve this.
