### ISSUE TITLE
mobileAlternate & languageAlternate doesn't work with <NextSeo>

### ISSUE THREAD

**Issue by yxwu** [garmeeh/next-seo#97]
For ver 2.1.0, the following code snippet doesn't work:
`          <NextSeo
            mobileAlternate={{
              media: "only screen and (max-width: 640px)",
              href: "https://m.canonical.ie"
            }}
          />`

But it works with `<DefaultSeo>`:
` <DefaultSeo
            mobileAlternate={{
              media: "only screen and (max-width: 640px)",
              href: "https://m.canonical.ie"
            }}
          />`

The same thing happens with languageAlternate.
Please help check, thanks.

**Comment by econdie** [comment]
i opened a fix for this, @garmeeh can you review when you get a chance
