### ISSUE TITLE
Support for og:title by default

### ISSUE THREAD

**Issue by indicozy** [garmeeh/next-seo#973]
**Is your feature request related to a problem? Please describe.**
The problem is that I could not find whether the use of `og:image` is implemented as a default option or not so have to use it as additional meta tag:

```js
additionalMetaTags={[
{
  property: 'og:image', 
  content: `${process.env.NEXTAUTH_URL}/static/images/twitter-card.png`,
  },
]}
```

**Describe the solution you'd like**
Add `og:image` to default options for `next-seo`:
```js
<DefaultSeo
  openGraph={{
  type: 'website',
  image: 'link-to-image' }}
/>
```

**Describe alternatives you've considered**
I'm already using an alternative

**Additional context**
None

**Comment by indicozy** [comment]
another issue that it comes with is that because it is not added to default options it cannot be set as default image in `DefaultSeo`

**Comment by garmeeh** [comment]
So would something like `baseUrl` work? 

```
<DefaultSeo
  baseUrl="https://www.mywebsite.com"
/>
```

Docs:
`baseUrl` should be your top level domain. This will be used for fields that require a full URL such as og:image

**Comment by indicozy** [comment]
Gotcha, I just missed the point. Closing the issue
