### ISSUE TITLE
og:image not setting twitter:image

### ISSUE THREAD

**Issue by pedrorolando** [garmeeh/next-seo#974]
**Describe the bug**
The og:image property is not setting the twitter:image property by default, as the docs claim.

**Reproduction**
Set an og:image - then view page head in console and see there is no twitter image set. 

**Expected behavior**
Expect the twitter image to be set automatically by default seo component.

**Comment by UrusuLambda** [comment]
(For someone who come here)

NextSEO doesn't set `twitter:image` but it works, cause Twitter first check `twitter:` specific tags, but after that, they will check `og:image`.


> When using Open Graph protocol to describe data on a page, it is easy to generate a Twitter card without duplicating tags and data. When the Twitter card processor looks for tags on a page, it first checks for the Twitter-specific property, and if not present, falls back to the supported Open Graph property.

Ref : https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started#opengraph

Also check here NextSEO code 

https://github.com/garmeeh/next-seo/blob/37dda3c3ae7391904323462e79d1d8972a8d9da1/src/meta/buildTags.tsx#L221-L251
