### ISSUE TITLE
Support for multiple addresses in jsonLD

### ISSUE THREAD

**Issue by richardcornelissen** [garmeeh/next-seo#983]
**Is your feature request related to a problem? Please describe.**
Businesses can have multiple addresses, which [is supported in JSON-LD](https://webmasters.stackexchange.com/questions/81735/multiple-addresses-in-json-ld-schema-org), but cannot be added in `LocalBusinessJsonLd`.

**Describe the solution you'd like**
Support for multiple addresses for local businesses and organizations.

**Describe alternatives you've considered**
Currently generating JSON using next-seo and copying it to a hardcoded JSON file.

**Additional context**
N/A

I am willing to create a pull request for support of multiple addresses if convenient.

**Comment by garmeeh** [comment]
@richardcornelissen I think if we can add this as a non breaking change that would be ideal.
