### ISSUE TITLE
Remove meta robots inserted by default

### ISSUE THREAD

**Issue by joao-pedrozo** [garmeeh/next-seo#985]
**Describe the bug**
It is by default adding meta robots with follow, index and I cant remove
![image](https://user-images.githubusercontent.com/40037644/184190709-fb9139a5-85e1-40aa-99bc-64ae40e2294e.png)

**Reproduction**
Just by inserting the component in a page this already happens

**Expected behavior**
I would like to remove this meta tag

**Additional context**
N/A

**Comment by mcrider** [comment]
Would love to have this ability as well. Our use case is on pages with query parameters, we set a canonical tag for the page without query params -- We don't want to explicitly tell search engines to not index the page with query params, but don't want to noindex them.

**Comment by garmeeh** [comment]
I would be open to adding some sort of override but Search Engines by default `index,follow` and more than likely don't even read that tag anymore. So removing would likely have zero effect 🤔

**Comment by garmeeh** [comment]
Closing this for now. Please respond here with further comments.

**Comment by rachelcg** [comment]
Hi. Experiencing the same problem and would love to have an option to remove the default robots meta tag

@garmeeh Opened a PR #1166 to support this feature. PTAL when you have time. Thanks! 🙏🏻
