### ISSUE TITLE
NextSeo is not overriden in each component when I use DefaultSeo.

### ISSUE THREAD

**Issue by arp55** [garmeeh/next-seo#99]
Issue with overriding Defaultseo in next application. I have implemented DefaultSeo in _app.js and trying to override the DefaultSeo using NextSeo in the other components as mentioned by the documentation of Next js. But the meta tags are not getting overriden as mentioned in the docs when I view the page source and instead the changes are reflecting only in the elements when I inspect the site. I have shared the code. Can anyone please help me out with this issue?

[View the code here](https://gist.github.com/arp55/0c2a3516edc5c07bc17a749d459e9b5c/fc655a3496345622b1ca178bde9307e44e6b8a48)

**Comment by arp55** [comment]
[](https://gist.github.com/arp55/0c2a3516edc5c07bc17a749d459e9b5c/fc655a3496345622b1ca178bde9307e44e6b8a48)

**Comment by garmeeh** [comment]
Hey @arp55, can you try this for your `_app.js`:

```
import App, { Container } from 'next/app'
import React from 'react'
import { Provider } from 'react-redux'
import withRedux from 'next-redux-wrapper'
import CssBaseline from '@material-ui/core/CssBaseline';
import NProgress from 'nprogress'
import Router from 'next/router'
import { withTheme } from '@material-ui/styles';
import withReduxStore from '../lib/with-redux-store'
import { persistStore } from 'redux-persist'
import { PersistGate } from 'redux-persist/integration/react'

// import for next-seo
import SEO from '../next-seo.config';
import { DefaultSeo } from 'next-seo';


Router.events.on('routeChangeStart', url => {
  NProgress.set(0.2)
  NProgress.start()
})
Router.events.on('routeChangeComplete', () => NProgress.done())
Router.events.on('routeChangeError', () => NProgress.done())



class MyApp extends App {

  constructor(props) {
    super(props)
    this.persistor = persistStore(props.reduxStore)
  }


  static async getInitialProps({ Component, router, ctx }) {
    let pageProps = {}
    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx)
    }


    return { pageProps }
  }


  componentDidMount() {
    const { asPath } = this.props.router;
  }

  componentDidUpdate() {
    const { asPath } = this.props.router;
  }

  render() {
    const { Component, pageProps, reduxStore } = this.props;
    const { loc } = this.state;

    return (
      <>
        <DefaultSeo
          openGraph={{
            type: 'website',
            title: 'XXXXXX',
            description: 'XXXXXXXX',
            url: "www.XXXXX.com",
            site_name: 'XXXXXXXX',
            images: [
              {
                url: 'XXXXXXXX',
                width: 800,
                height: 600,
                alt: 'XXXXXXXX',
              },
            ],
          }}
          facebook={{
            appId: XXXXXXXXXX
          }}
        />
        <Container>
          <Provider store={reduxStore}>
            <PersistGate loading={null} persistor={this.persistor}>
              <MuiThemeProvider theme={theme}>
                <CssBaseline />
                <Component his={this.state.history} {...pageProps} />
              </MuiThemeProvider>
            </PersistGate>
          </Provider>
        </Container>
      </>
    )
  }
}

export default withTheme(withReduxStore(NextApp))
```

**Comment by arp55** [comment]
Hi @garmeeh ,
Thanks for the reply. I tried the solution which you have given and tried making the same changes to login.js too. But still the DefaultSeo is not overriden by NextSeo. The NextSeo attributes are not showing in the view source.

**Comment by BennettStaley** [comment]
same thing happening on our site... can't seem to get any meta tags to change unless you hard refresh.

**Comment by garmeeh** [comment]
I have created a small sample app to see if the overriding is working as expected. 

I could not re-create the issue. You can see it in action here:

Sandbox Browser: https://tchh3.sse.codesandbox.io/

Sandbox: https://codesandbox.io/s/github/garmeeh/next-seo-test

Could you take a look and see if your issue is present on that app?

Would you both also be able to confirm the version you are using of `next-seo`?

**Comment by BennettStaley** [comment]
Actually it looks like it might have been an issue within `next/head`. Upgrading `next` and `next-seo` seems to have fixed it without any side effects.

**Comment by arp55** [comment]
Hey @garmeeh ,
I am using next-seo v2. But the problem is that I'm using Es6  and not typescript. Will it work the same way in Es6? if not then can you suggest me a solution.

**Comment by garmeeh** [comment]
Hey @arp55, yeah the position of it could affect it. Hard to say from just looking at the code example. Have you tried moving the <DefaultSEO/> to be within the provider maybe?

**Comment by brijeshborkar** [comment]
Hey @garmeeh , even i'm facing the same issue as i'm also using redux in my project, tried moving 'default seo' within the provider and tried different possibilities of putting it in many positions, didn't work?

**Comment by garmeeh** [comment]
Could someone provide a code sandbox example of the issue so that I can investigate?

**Comment by mercteil** [comment]
next 9.1.5
next-seo 3.2.0

I use redux and my DefaultSEO is set within a Fragment before the Provider component in _app.js.

The title is overridden whenever I set it in a subPage. 

_app.js
```javascript
import React from 'react';
import App from 'next/app';
import { DefaultSeo } from 'next-seo';
import { Provider } from 'react-redux';
import { ToastContainer } from 'react-toastify';
import createStore from '@root/store';
import SEO from '@root/next-seo.config';
import withRedux from 'next-redux-wrapper';
import { appWithTranslation } from '@root/i18n';
import withReduxSaga from 'apphocs/withReduxSaga';

class MyApp extends App {
  static async getInitialProps({ Component, ctx }) {
    const pageProps = Component.getInitialProps ? (await Component.getInitialProps(ctx)) || {} : {};
    const { namespacesRequired = [] } = pageProps;
    const defaultNamespaces = ['footer', 'home', 'error', 'api', 'validation'];

    return {
      pageProps: {
        ...pageProps,
        namespacesRequired: [...defaultNamespaces, ...namespacesRequired],
      },
    };
  }

  render() {
    const { Component, store, pageProps } = this.props;

    return (
      <>
        <DefaultSeo {...SEO} />
        <Provider store={store}>
          <Component {...pageProps} />
          <ToastContainer />
        </Provider>
      </>
    );
  }
}

export default withRedux(createStore)(appWithTranslation(withReduxSaga(MyApp)));

```

**Comment by mercteil** [comment]
PS: I saw the next/container in the code samples above. It is not supported in the newer Nextjs versions and should be replaced by react fragments.

**Comment by garmeeh** [comment]
If this issue is still happening, please open a new issue with an example that I can debug.

**Comment by mbruggenwirth** [comment]
Got still this isssue.
"next-seo": "^4.5.0",
"next": "^9.4.4",

Works when:  DefaultSeo(title, description, openGraph config) + NextSeo(title, description)
Fails when: DefaultSeo(title, description, openGraph config) + NextSeo(title, description, openGraph config)

**Comment by pbassut** [comment]
I had the same issue and I solved it by making sure any data fetching work happened before the response was written.

SEOs engines will make a simple request to your server and use the html given *on first render*. 
What happened in my case was: I was fetching some data client-side and expected SEO engines to pick up.

So essentially changing this:

```javascript
function Page() {
  const { data, error, loading } = await apolloClient.query({
    // ...
  })
  return (
    <React.Fragment>
      <NextSeo
        // ...
      />
      <MyComponent data={data} />
    </React.Fragment>
  )
}
```

To this:
```javascript
function Page({ data} ) {
  return (
    <React.Fragment>
      <NextSeo
        // ...
      />
      <MyComponent data={data} />
    </React.Fragment>
  )
}

Page.getInitialProps = async ({ apolloClient }) => {
  // do the data fetching here
  const { data, error, loading } = await apolloClient.query({
    // ...
  })

  return { data }
}
```

From 9.3 onwards, of course, you can use `getStaticProps` or `getServerSideProps` to have the same effect.

**Comment by anoonoll** [comment]
The same problem is occurring on my site.
Browser validation reflects NEXTSeo on individual pages, but the default next-seo-config.js corresponds with Twitter, Firebase's Card validator, etc.
I tried using getServerSideProps but no improvement.
Does anyone know what to do?

**Comment by anoonoll** [comment]
I found the cause!
The cause of not being reflected was redux-persist.

Reference ↓
 https://qiita.com/miyabiya/items/14e4f133d5df5d53cd77

**Comment by nguyenvuhoang** [comment]
My case. I try fixed value on component. But the web still load Default. Although the web show on "Inspect". But when I share to telegram or any social network. it still display from DefaultSEO

**Comment by nehas-cn** [comment]
same issue i am also facing, Is there any fix already????
