### ISSUE TITLE
Schema JSON-LD Next SEO - Organization Schema

### ISSUE THREAD

**Issue by dkrefta** [garmeeh/next-seo#998]
I'm coming here to ask for some help with the schema JSON-LD with the library next-seo, I created this function to handle the Organization Schema

```
import { OrganizationJsonLd } from 'next-seo';
import asset from '/lib/asset';

const OrganizationSchema = () => (
    <>
        <OrganizationJsonLd
            type="Corporation"
            id="https://www.test.com"
            logo={asset('/logos/gradient/logo-144.png')}
            legalName="test.com"
            name="test.com"
            email="help@test.com"
            address={{
                streetAddress: 'test 12321',
                addressLocality: 'test city',
                addressRegion: 'test region',
                postalCode: '',
                addressCountry: 'EU',
            }}
            sameAs={['https://www.test.com']}
            url="https://www.test.com"
        />
    </>
);

```
export default OrganizationSchema;
then I did the import at the pages/_app.js and inserted the component inside the (next/head) Also, the SiteLinksSearchBoxJsonLd is also there in the Head component

It is right because now I'm testing with the Google schema tester and is not showing, there is something that I'm doing wrong?

**Comment by garmeeh** [comment]
@dkrefta next-seo already includes `next/head` so no need to nest again. This may be the issue. 

If you are still experiencing issues, the most common issue is client side rendering as google schema tester only checks server rendered and/or static pages.

**Comment by dkrefta** [comment]
@garmeeh exactly, was this problem, thanks very much (:
